// Custom exercises with full metadata for sprints, plyometrics, gymnastics, and enhanced strength exercises

export interface CustomExercise {
  name: string;
  description: string;
  instructions: string;
  category: string;
  muscleGroups: string[];
  secondaryMuscles: string[];
  equipment: string[];
  difficulty: string;
  force: string;
  mechanic: string;
  benefits: string[];
  progressions: string[];
}

// ============================================================================
// SPRINT & SPEED EXERCISES
// ============================================================================
export const sprintExercises: CustomExercise[] = [
  {
    name: "100m Sprint",
    description: "Maximum velocity sprint over 100 meters. The ultimate test of speed and acceleration.",
    instructions: "1. Start in blocks or standing start position\n2. Drive explosively off the start\n3. Transition to upright running by 30m\n4. Maintain top speed through finish\n5. Focus on arm drive and hip extension",
    category: "sport",
    muscleGroups: ["quadriceps", "hamstrings", "glutes"],
    secondaryMuscles: ["calves", "hip flexors", "core"],
    equipment: ["track"],
    difficulty: "advanced",
    force: "dynamic",
    mechanic: "compound",
    benefits: ["speed", "power", "explosiveness", "anaerobic capacity"],
    progressions: ["faster 100m time", "better acceleration", "higher top speed"],
  },
  {
    name: "200m Sprint",
    description: "Speed endurance sprint requiring both acceleration and the ability to maintain speed.",
    instructions: "1. Explosive start from blocks\n2. Build to maximum speed through the curve\n3. Maintain form entering the straight\n4. Fight to hold speed through finish\n5. Relax shoulders while maintaining turnover",
    category: "sport",
    muscleGroups: ["quadriceps", "hamstrings", "glutes"],
    secondaryMuscles: ["calves", "hip flexors", "core", "obliques"],
    equipment: ["track"],
    difficulty: "advanced",
    force: "dynamic",
    mechanic: "compound",
    benefits: ["speed endurance", "lactate tolerance", "power", "mental toughness"],
    progressions: ["faster 200m time", "better curve running", "improved finish"],
  },
  {
    name: "400m Sprint",
    description: "One-lap sprint requiring speed, endurance, and race strategy.",
    instructions: "1. Controlled start - not maximum effort\n2. Run relaxed through first 200m\n3. Maintain form through 300m\n4. Give everything in final 100m\n5. Focus on arm drive when legs fatigue",
    category: "sport",
    muscleGroups: ["quadriceps", "hamstrings", "glutes"],
    secondaryMuscles: ["calves", "hip flexors", "core"],
    equipment: ["track"],
    difficulty: "advanced",
    force: "dynamic",
    mechanic: "compound",
    benefits: ["speed endurance", "lactate tolerance", "mental toughness", "anaerobic capacity"],
    progressions: ["faster 400m time", "better pacing", "stronger finish"],
  },
  {
    name: "Flying 30m Sprint",
    description: "Maximum velocity sprint after a running start. Tests pure top-end speed.",
    instructions: "1. Build up over 20-30m approach\n2. Hit maximum velocity entering timing zone\n3. Maintain relaxed maximum effort for 30m\n4. Focus on quick ground contact and high knees\n5. Keep arms driving forward, not across body",
    category: "sport",
    muscleGroups: ["quadriceps", "hamstrings", "glutes"],
    secondaryMuscles: ["calves", "hip flexors"],
    equipment: ["track", "timing system"],
    difficulty: "intermediate",
    force: "dynamic",
    mechanic: "compound",
    benefits: ["top-end speed", "running mechanics", "stride frequency"],
    progressions: ["faster flying sprint time", "higher top speed", "better mechanics"],
  },
  {
    name: "Hill Sprints",
    description: "Uphill sprinting for power development and acceleration mechanics.",
    instructions: "1. Find a hill with 5-15% grade\n2. Sprint up for 20-60 meters\n3. Focus on driving knees high\n4. Pump arms aggressively\n5. Walk back down for recovery",
    category: "cardio",
    muscleGroups: ["glutes", "quadriceps", "hamstrings"],
    secondaryMuscles: ["calves", "hip flexors", "core"],
    equipment: ["hill"],
    difficulty: "intermediate",
    force: "push",
    mechanic: "compound",
    benefits: ["power", "acceleration", "strength endurance", "sprint mechanics"],
    progressions: ["faster sprint times", "better acceleration", "stronger drive phase"],
  },
  {
    name: "Resisted Sprints (Sled)",
    description: "Sprinting while pulling a weighted sled to develop acceleration power.",
    instructions: "1. Attach sled with waist harness\n2. Use 10-30% bodyweight on sled\n3. Sprint 20-40 meters\n4. Focus on forward lean and knee drive\n5. Keep ground contact quick despite resistance",
    category: "sport",
    muscleGroups: ["glutes", "quadriceps", "hamstrings"],
    secondaryMuscles: ["calves", "hip flexors", "core"],
    equipment: ["sled", "harness"],
    difficulty: "intermediate",
    force: "push",
    mechanic: "compound",
    benefits: ["acceleration", "power", "horizontal force production"],
    progressions: ["faster acceleration", "more explosive starts", "better drive phase"],
  },
  {
    name: "A-Skips",
    description: "Running drill emphasizing knee drive and ground contact for sprint mechanics.",
    instructions: "1. Skip forward driving one knee up to hip height\n2. Keep support leg straight at contact\n3. Drive arms in opposition\n4. Land on ball of foot\n5. Maintain rhythm and posture",
    category: "sport",
    muscleGroups: ["hip flexors", "calves"],
    secondaryMuscles: ["quadriceps", "core"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    force: "dynamic",
    mechanic: "compound",
    benefits: ["sprint mechanics", "coordination", "hip flexor strength"],
    progressions: ["better sprint form", "higher knee drive", "faster turnover"],
  },
  {
    name: "B-Skips",
    description: "Advanced running drill with leg extension for hamstring activation.",
    instructions: "1. Perform A-skip with knee drive\n2. Extend lower leg forward at top\n3. Pull leg down and back actively\n4. Strike ground with ball of foot\n5. Maintain tall posture throughout",
    category: "sport",
    muscleGroups: ["hip flexors", "hamstrings", "calves"],
    secondaryMuscles: ["quadriceps", "core"],
    equipment: ["bodyweight"],
    difficulty: "intermediate",
    force: "dynamic",
    mechanic: "compound",
    benefits: ["sprint mechanics", "hamstring activation", "ground contact"],
    progressions: ["faster sprinting", "better ground contact", "reduced injury risk"],
  },
  {
    name: "High Knees",
    description: "Running in place or moving forward with exaggerated knee lift.",
    instructions: "1. Run with knees driving up to hip height\n2. Stay on balls of feet\n3. Keep core tight and posture tall\n4. Pump arms in coordination\n5. Maintain quick ground contacts",
    category: "cardio",
    muscleGroups: ["hip flexors", "calves"],
    secondaryMuscles: ["quadriceps", "core"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    force: "dynamic",
    mechanic: "compound",
    benefits: ["hip flexor strength", "coordination", "conditioning"],
    progressions: ["faster sprint cadence", "higher knee lift", "better running form"],
  },
  {
    name: "Butt Kicks",
    description: "Running drill with heels kicking up toward glutes for hamstring activation.",
    instructions: "1. Jog forward or in place\n2. Kick heels up toward glutes\n3. Keep knees pointing down\n4. Stay on balls of feet\n5. Maintain quick cadence",
    category: "cardio",
    muscleGroups: ["hamstrings", "calves"],
    secondaryMuscles: ["quadriceps", "hip flexors"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    force: "dynamic",
    mechanic: "compound",
    benefits: ["hamstring activation", "leg speed", "running mechanics"],
    progressions: ["faster leg recovery", "better sprint form", "reduced hamstring injuries"],
  },
];

// ============================================================================
// PLYOMETRIC EXERCISES
// ============================================================================
export const plyometricExercises: CustomExercise[] = [
  {
    name: "Box Jumps",
    description: "Explosive jump onto an elevated platform. Develops lower body power.",
    instructions: "1. Stand facing box in athletic stance\n2. Dip into quarter squat\n3. Explode upward swinging arms\n4. Land softly on box with bent knees\n5. Step down and repeat",
    category: "plyometric",
    muscleGroups: ["quadriceps", "glutes", "calves"],
    secondaryMuscles: ["hamstrings", "core"],
    equipment: ["plyo box"],
    difficulty: "intermediate",
    force: "push",
    mechanic: "compound",
    benefits: ["power", "explosiveness", "vertical jump height"],
    progressions: ["higher vertical jump", "better athletic performance", "dunking"],
  },
  {
    name: "Depth Jumps",
    description: "Step off box and immediately jump for maximum height. Elite plyometric.",
    instructions: "1. Stand on box 30-50cm high\n2. Step off (don't jump off)\n3. Land on both feet and immediately explode up\n4. Minimize ground contact time\n5. Reach for maximum height",
    category: "plyometric",
    muscleGroups: ["quadriceps", "glutes", "calves"],
    secondaryMuscles: ["hamstrings", "core"],
    equipment: ["plyo box"],
    difficulty: "advanced",
    force: "push",
    mechanic: "compound",
    benefits: ["reactive strength", "power", "rate of force development"],
    progressions: ["higher vertical jump", "faster sprints", "more explosive movements"],
  },
  {
    name: "Broad Jumps",
    description: "Maximum distance horizontal jump from standing position.",
    instructions: "1. Stand with feet shoulder-width apart\n2. Swing arms back while dipping hips\n3. Explode forward and up at 45 degrees\n4. Drive arms forward\n5. Land softly and stick the landing",
    category: "plyometric",
    muscleGroups: ["quadriceps", "glutes", "hamstrings"],
    secondaryMuscles: ["calves", "core"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    force: "push",
    mechanic: "compound",
    benefits: ["horizontal power", "acceleration ability", "explosiveness"],
    progressions: ["better acceleration", "more explosive movements", "improved athletic performance"],
  },
  {
    name: "Tuck Jumps",
    description: "Vertical jump bringing knees to chest at peak height.",
    instructions: "1. Start in athletic stance\n2. Explode upward\n3. Pull knees to chest at top\n4. Extend legs for landing\n5. Land softly and repeat immediately",
    category: "plyometric",
    muscleGroups: ["quadriceps", "hip flexors", "calves"],
    secondaryMuscles: ["glutes", "core"],
    equipment: ["bodyweight"],
    difficulty: "intermediate",
    force: "push",
    mechanic: "compound",
    benefits: ["power", "hip flexor strength", "air awareness"],
    progressions: ["higher jumps", "back tuck preparation", "better body control"],
  },
  {
    name: "Bounding",
    description: "Exaggerated running with maximum stride length and height.",
    instructions: "1. Run forward with exaggerated strides\n2. Drive knee up and out\n3. Maximize time in air\n4. Land on opposite foot and repeat\n5. Focus on horizontal and vertical displacement",
    category: "plyometric",
    muscleGroups: ["glutes", "quadriceps", "hamstrings"],
    secondaryMuscles: ["hip flexors", "calves", "core"],
    equipment: ["bodyweight"],
    difficulty: "intermediate",
    force: "dynamic",
    mechanic: "compound",
    benefits: ["power", "stride length", "sprint speed"],
    progressions: ["faster sprinting", "longer strides", "more explosive running"],
  },
  {
    name: "Single Leg Hops",
    description: "Consecutive hops on one leg for unilateral power development.",
    instructions: "1. Stand on one leg\n2. Hop forward with maximum effort\n3. Land on same leg\n4. Immediately hop again\n5. Complete reps then switch legs",
    category: "plyometric",
    muscleGroups: ["quadriceps", "glutes", "calves"],
    secondaryMuscles: ["hamstrings", "core"],
    equipment: ["bodyweight"],
    difficulty: "intermediate",
    force: "push",
    mechanic: "compound",
    benefits: ["unilateral power", "balance", "ankle stability"],
    progressions: ["single leg strength", "injury prevention", "better sprint power"],
  },
  {
    name: "Lateral Bounds",
    description: "Explosive side-to-side jumping for lateral power.",
    instructions: "1. Stand on one leg\n2. Push off latecircle\n3. Land on opposite leg\n4. Absorb and immediately push back\n5. Minimize ground contact time",
    category: "plyometric",
    muscleGroups: ["glutes", "quadriceps", "adductors"],
    secondaryMuscles: ["abductors", "calves", "core"],
    equipment: ["bodyweight"],
    difficulty: "intermediate",
    force: "push",
    mechanic: "compound",
    benefits: ["lateral power", "stability", "change of direction"],
    progressions: ["faster cutting", "better agility", "reduced knee injuries"],
  },
  {
    name: "Hurdle Hops",
    description: "Consecutive jumps over hurdles for reactive strength.",
    instructions: "1. Set up 3-5 hurdles at appropriate height\n2. Jump over first hurdle\n3. Land and immediately jump over next\n4. Minimize ground contact between hurdles\n5. Keep hips high throughout",
    category: "plyometric",
    muscleGroups: ["quadriceps", "calves", "glutes"],
    secondaryMuscles: ["hamstrings", "core"],
    equipment: ["hurdles"],
    difficulty: "advanced",
    force: "push",
    mechanic: "compound",
    benefits: ["reactive strength", "stiffness", "power endurance"],
    progressions: ["faster ground contacts", "higher jumps", "better sprint performance"],
  },
  {
    name: "Squat Jumps",
    description: "Jump from a deep squat position for maximum power development.",
    instructions: "1. Squat down until thighs parallel\n2. Pause briefly at bottom\n3. Explode upward as high as possible\n4. Land softly back into squat\n5. Pause and repeat",
    category: "plyometric",
    muscleGroups: ["quadriceps", "glutes"],
    secondaryMuscles: ["hamstrings", "calves", "core"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    force: "push",
    mechanic: "compound",
    benefits: ["power", "vertical jump", "leg strength"],
    progressions: ["higher vertical jump", "better athletic performance", "stronger legs"],
  },
  {
    name: "Plyo Push-ups",
    description: "Explosive push-ups with hands leaving ground at top.",
    instructions: "1. Start in push-up position\n2. Lower chest to ground\n3. Explode up pushing hands off ground\n4. Land softly and immediately descend\n5. Maintain body alignment throughout",
    category: "plyometric",
    muscleGroups: ["chest", "triceps"],
    secondaryMuscles: ["shoulders", "core"],
    equipment: ["bodyweight"],
    difficulty: "intermediate",
    force: "push",
    mechanic: "compound",
    benefits: ["upper body power", "pushing speed", "chest strength"],
    progressions: ["more powerful push", "clapping push-ups", "better pressing power"],
  },
];

// ============================================================================
// GYMNASTICS & SKILL EXERCISES
// ============================================================================
export const gymnasticsExercises: CustomExercise[] = [
  {
    name: "Back Tuck",
    description: "Standing backflip with tucked position. Fundamental gymnastics skill.",
    instructions: "1. Stand tall with arms overhead\n2. Dip and swing arms down\n3. Jump straight up while throwing arms up\n4. Tuck knees to chest after leaving ground\n5. Spot landing and extend for landing",
    category: "skill",
    muscleGroups: ["quadriceps", "glutes", "core"],
    secondaryMuscles: ["hip flexors", "calves"],
    equipment: ["tumbling mat", "spring floor"],
    difficulty: "advanced",
    force: "push",
    mechanic: "compound",
    benefits: ["power", "air awareness", "body control", "courage"],
    progressions: ["back tuck mastery", "back layout", "back full"],
  },
  {
    name: "Front Tuck",
    description: "Standing front flip with tucked position.",
    instructions: "1. Take a few approach steps\n2. Punch off both feet\n3. Drive arms up and forward\n4. Tuck immediately and rotate forward\n5. Spot landing and stick",
    category: "skill",
    muscleGroups: ["quadriceps", "hip flexors", "core"],
    secondaryMuscles: ["calves", "glutes"],
    equipment: ["tumbling mat", "spring floor"],
    difficulty: "advanced",
    force: "push",
    mechanic: "compound",
    benefits: ["power", "air awareness", "body control"],
    progressions: ["front tuck mastery", "front layout", "front full"],
  },
  {
    name: "Handstand",
    description: "Inverted vertical balance on hands. Foundation for many skills.",
    instructions: "1. Start in lunge with arms overhead\n2. Kick up one leg while pushing off other\n3. Stack shoulders over wrists\n4. Point toes and squeeze legs together\n5. Hold position with controlled breathing",
    category: "skill",
    muscleGroups: ["shoulders", "core"],
    secondaryMuscles: ["triceps", "forearms", "wrists"],
    equipment: ["bodyweight"],
    difficulty: "intermediate",
    force: "push",
    mechanic: "compound",
    benefits: ["balance", "body awareness", "shoulder strength", "core stability"],
    progressions: ["freestanding handstand", "handstand walk", "press to handstand"],
  },
  {
    name: "Handstand Walk",
    description: "Walking on hands while maintaining handstand position.",
    instructions: "1. Kick up into handstand\n2. Find balance point\n3. Shift weight to one hand\n4. Take small 'steps' with hands\n5. Keep core tight and look at ground",
    category: "skill",
    muscleGroups: ["shoulders", "core"],
    secondaryMuscles: ["triceps", "forearms", "wrists"],
    equipment: ["bodyweight"],
    difficulty: "advanced",
    force: "push",
    mechanic: "compound",
    benefits: ["balance", "shoulder endurance", "body control"],
    progressions: ["longer handstand walks", "obstacle navigation", "pirouettes"],
  },
  {
    name: "Muscle-Up",
    description: "Pulling from hang to dip support in one movement. Advanced pull-up progression.",
    instructions: "1. Hang from bar with false grip\n2. Pull explosively while leaning back slightly\n3. As chest reaches bar height, throw elbows over\n4. Transition to dip position\n5. Press to full lockout",
    category: "skill",
    muscleGroups: ["back", "chest", "triceps"],
    secondaryMuscles: ["biceps", "shoulders", "core"],
    equipment: ["pull-up bar", "rings"],
    difficulty: "advanced",
    force: "pull",
    mechanic: "compound",
    benefits: ["pulling power", "upper body strength", "coordination"],
    progressions: ["strict muscle-up", "ring muscle-up", "weighted muscle-up"],
  },
  {
    name: "L-Sit",
    description: "Holding body off ground with legs extended parallel to floor.",
    instructions: "1. Sit on floor with legs extended\n2. Place hands beside hips\n3. Press down to lift entire body\n4. Keep legs straight and together\n5. Hold position with pointed toes",
    category: "skill",
    muscleGroups: ["hip flexors", "core", "triceps"],
    secondaryMuscles: ["quadriceps", "shoulders"],
    equipment: ["parallettes", "floor"],
    difficulty: "intermediate",
    force: "push",
    mechanic: "compound",
    benefits: ["core strength", "hip flexor strength", "body control"],
    progressions: ["longer L-sit hold", "V-sit", "manna"],
  },
  {
    name: "Pistol Squat",
    description: "Full depth single-leg squat. Requires strength, balance, and mobility.",
    instructions: "1. Stand on one leg, other extended forward\n2. Squat down on standing leg\n3. Keep heel flat and torso upright\n4. Descend until hip crease below knee\n5. Stand back up under control",
    category: "skill",
    muscleGroups: ["quadriceps", "glutes"],
    secondaryMuscles: ["hamstrings", "hip flexors", "core"],
    equipment: ["bodyweight"],
    difficulty: "advanced",
    force: "push",
    mechanic: "compound",
    benefits: ["unilateral strength", "balance", "mobility", "leg strength"],
    progressions: ["pistol squat mastery", "weighted pistol", "shrimp squat"],
  },
  {
    name: "Skin the Cat",
    description: "Rotating through full shoulder range of motion while hanging.",
    instructions: "1. Hang from bar or rings\n2. Tuck knees and roll backwards\n3. Pass through inverted hang\n4. Continue until arms behind back\n5. Reverse the movement to return",
    category: "skill",
    muscleGroups: ["shoulders", "back", "core"],
    secondaryMuscles: ["biceps", "chest"],
    equipment: ["rings", "pull-up bar"],
    difficulty: "intermediate",
    force: "pull",
    mechanic: "compound",
    benefits: ["shoulder mobility", "back flexibility", "body awareness"],
    progressions: ["German hang", "back lever", "front lever"],
  },
  {
    name: "Back Lever",
    description: "Holding horizontal body position while hanging inverted.",
    instructions: "1. Hang from rings or bar\n2. Rotate into inverted position\n3. Lower body until horizontal\n4. Keep arms straight and body tight\n5. Hold position with body parallel to ground",
    category: "skill",
    muscleGroups: ["back", "shoulders", "core"],
    secondaryMuscles: ["biceps", "chest", "glutes"],
    equipment: ["rings", "pull-up bar"],
    difficulty: "advanced",
    force: "pull",
    mechanic: "compound",
    benefits: ["straight-arm strength", "body control", "core strength"],
    progressions: ["back lever mastery", "front lever", "iron cross progressions"],
  },
  {
    name: "Front Lever",
    description: "Holding horizontal body position while hanging from arms.",
    instructions: "1. Hang from bar or rings\n2. Engage lats and retract shoulders\n3. Raise body to horizontal\n4. Keep arms straight and body rigid\n5. Hold position parallel to ground",
    category: "skill",
    muscleGroups: ["back", "core"],
    secondaryMuscles: ["shoulders", "biceps", "glutes"],
    equipment: ["pull-up bar", "rings"],
    difficulty: "advanced",
    force: "pull",
    mechanic: "compound",
    benefits: ["lat strength", "core strength", "body control"],
    progressions: ["front lever mastery", "front lever pulls", "one-arm progressions"],
  },
  {
    name: "Planche Lean",
    description: "Leaning forward in push-up position for planche preparation.",
    instructions: "1. Start in push-up position\n2. Lean forward shifting shoulders past wrists\n3. Keep arms straight\n4. Point fingers forward or slightly out\n5. Hold lean position with core engaged",
    category: "skill",
    muscleGroups: ["shoulders", "chest", "core"],
    secondaryMuscles: ["triceps", "forearms", "wrists"],
    equipment: ["bodyweight", "parallettes"],
    difficulty: "intermediate",
    force: "push",
    mechanic: "compound",
    benefits: ["shoulder strength", "wrist conditioning", "planche preparation"],
    progressions: ["tuck planche", "advanced tuck planche", "straddle planche"],
  },
  {
    name: "Ring Dips",
    description: "Dips on gymnastics rings requiring stability and strength.",
    instructions: "1. Support on rings with arms locked\n2. Turn rings out slightly\n3. Lower until shoulders below elbows\n4. Press back to full lockout\n5. Maintain control and stability",
    category: "strength",
    muscleGroups: ["chest", "triceps", "shoulders"],
    secondaryMuscles: ["core", "biceps"],
    equipment: ["rings"],
    difficulty: "intermediate",
    force: "push",
    mechanic: "compound",
    benefits: ["pressing strength", "stability", "muscle-up preparation"],
    progressions: ["ring muscle-up", "weighted ring dips", "impossible dips"],
  },
];

// ============================================================================
// ENHANCED STRENGTH EXERCISES WITH PROGRESSIONS
// ============================================================================
export const enhancedStrengthExercises: CustomExercise[] = [
  {
    name: "Pull-ups",
    description: "Vertical pulling from dead hang to chin over bar. Fundamental back exercise.",
    instructions: "1. Hang from bar with overhand grip\n2. Engage lats and retract shoulder blades\n3. Pull until chin clears bar\n4. Lower with control to dead hang\n5. Avoid kipping or swinging",
    category: "strength",
    muscleGroups: ["back", "biceps"],
    secondaryMuscles: ["forearms", "shoulders", "core"],
    equipment: ["pull-up bar"],
    difficulty: "intermediate",
    force: "pull",
    mechanic: "compound",
    benefits: ["back strength", "pulling power", "grip strength"],
    progressions: ["weighted pull-ups", "muscle-up", "one-arm pull-up progressions"],
  },
  {
    name: "Chin-ups",
    description: "Vertical pulling with underhand grip emphasizing biceps.",
    instructions: "1. Hang with supinated (underhand) grip\n2. Pull until chin clears bar\n3. Squeeze biceps at top\n4. Lower with control\n5. Full dead hang between reps",
    category: "strength",
    muscleGroups: ["biceps", "back"],
    secondaryMuscles: ["forearms", "core"],
    equipment: ["pull-up bar"],
    difficulty: "intermediate",
    force: "pull",
    mechanic: "compound",
    benefits: ["bicep strength", "back development", "grip strength"],
    progressions: ["weighted chin-ups", "one-arm chin-up", "muscle-up"],
  },
  {
    name: "Archer Pull-ups",
    description: "Pull-up with one arm doing most of the work while other assists.",
    instructions: "1. Grip bar wide\n2. Pull toward one hand\n3. Working arm bends while other stays straighter\n4. Touch shoulder to hand\n5. Lower and repeat on other side",
    category: "strength",
    muscleGroups: ["back", "biceps"],
    secondaryMuscles: ["forearms", "core"],
    equipment: ["pull-up bar"],
    difficulty: "advanced",
    force: "pull",
    mechanic: "compound",
    benefits: ["unilateral strength", "one-arm pull-up preparation"],
    progressions: ["one-arm pull-up", "weighted archer pull-ups"],
  },
  {
    name: "Inverted Row",
    description: "Horizontal pulling movement using body weight.",
    instructions: "1. Hang from bar or rings at waist height\n2. Keep body straight\n3. Pull chest to bar\n4. Squeeze shoulder blades together\n5. Lower with control",
    category: "strength",
    muscleGroups: ["back", "biceps"],
    secondaryMuscles: ["rear delts", "core"],
    equipment: ["bar", "rings"],
    difficulty: "beginner",
    force: "pull",
    mechanic: "compound",
    benefits: ["horizontal pulling strength", "posture", "pull-up preparation"],
    progressions: ["pull-ups", "front lever rows", "one-arm rows"],
  },
  {
    name: "Push-ups",
    description: "Fundamental horizontal pushing exercise using bodyweight.",
    instructions: "1. Start in plank with hands shoulder-width\n2. Lower chest to floor\n3. Keep elbows at 45 degrees\n4. Press back to starting position\n5. Maintain straight body throughout",
    category: "strength",
    muscleGroups: ["chest", "triceps", "shoulders"],
    secondaryMuscles: ["core", "serratus anterior"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    force: "push",
    mechanic: "compound",
    benefits: ["pushing strength", "chest development", "core stability"],
    progressions: ["one-arm push-up", "planche push-up", "handstand push-up"],
  },
  {
    name: "Diamond Push-ups",
    description: "Push-up with hands together targeting triceps.",
    instructions: "1. Form diamond shape with hands under chest\n2. Lower chest to hands\n3. Keep elbows close to body\n4. Press back up\n5. Maintain tight core",
    category: "strength",
    muscleGroups: ["triceps", "chest"],
    secondaryMuscles: ["shoulders", "core"],
    equipment: ["bodyweight"],
    difficulty: "intermediate",
    force: "push",
    mechanic: "compound",
    benefits: ["tricep strength", "pushing power"],
    progressions: ["one-arm push-up", "pseudo planche push-up"],
  },
  {
    name: "Pike Push-ups",
    description: "Push-up in pike position for shoulder emphasis.",
    instructions: "1. Start in downward dog position\n2. Lower head toward ground between hands\n3. Push back up to starting position\n4. Keep legs straight\n5. Progress by elevating feet",
    category: "strength",
    muscleGroups: ["shoulders", "triceps"],
    secondaryMuscles: ["upper chest", "core"],
    equipment: ["bodyweight"],
    difficulty: "intermediate",
    force: "push",
    mechanic: "compound",
    benefits: ["shoulder strength", "overhead pressing power"],
    progressions: ["handstand push-up", "90-degree push-up"],
  },
  {
    name: "Handstand Push-ups",
    description: "Inverted vertical pressing. Advanced shoulder exercise.",
    instructions: "1. Kick up to handstand against wall\n2. Lower head to ground\n3. Press back to full extension\n4. Keep core tight\n5. Control descent",
    category: "strength",
    muscleGroups: ["shoulders", "triceps"],
    secondaryMuscles: ["upper chest", "core", "upper back"],
    equipment: ["wall"],
    difficulty: "advanced",
    force: "push",
    mechanic: "compound",
    benefits: ["overhead strength", "shoulder development", "balance"],
    progressions: ["freestanding HSPU", "90-degree push-up", "planche"],
  },
  {
    name: "Dips",
    description: "Vertical pushing movement between parallel bars.",
    instructions: "1. Support yourself on parallel bars\n2. Lower until shoulders below elbows\n3. Lean forward slightly for chest emphasis\n4. Press back to lockout\n5. Keep shoulders down",
    category: "strength",
    muscleGroups: ["chest", "triceps", "shoulders"],
    secondaryMuscles: ["core"],
    equipment: ["dip bars", "parallel bars"],
    difficulty: "intermediate",
    force: "push",
    mechanic: "compound",
    benefits: ["pressing strength", "chest and tricep development"],
    progressions: ["weighted dips", "ring dips", "impossible dips"],
  },
];

// Combine all exercises
export const allCustomExercises: CustomExercise[] = [
  ...sprintExercises,
  ...plyometricExercises,
  ...gymnasticsExercises,
  ...enhancedStrengthExercises,
];
