/**
 * Seed 200+ exercises with comprehensive metadata
 * Run: npx tsx scripts/seed-exercises.ts
 */

// Exercise data organized by category
export const EXERCISES = [
  // ============================================================================
  // STRENGTH - COMPOUND (30 exercises)
  // ============================================================================
  {
    name: "Barbell Back Squat",
    description: "The king of leg exercises. A compound movement targeting the entire lower body.",
    instructions: "Place barbell on upper back, feet shoulder-width apart, squat down until thighs are parallel, drive through heels to stand.",
    category: "strength",
    muscleGroups: ["quadriceps", "glutes", "hamstrings"],
    secondaryMuscles: ["core", "lower back", "calves"],
    equipment: ["barbell", "squat rack"],
    difficulty: "intermediate",
    force: "push",
    mechanic: "compound",
    benefits: ["strength", "power", "muscle growth"],
    tags: ["legs", "powerlifting", "fundamental"],
  },
  {
    name: "Conventional Deadlift",
    description: "Full body posterior chain exercise. Builds overall strength and mass.",
    instructions: "Stand with feet hip-width, grip bar outside knees, keep back flat, drive through heels and hips to stand.",
    category: "strength",
    muscleGroups: ["hamstrings", "glutes", "lower back"],
    secondaryMuscles: ["traps", "forearms", "core", "quadriceps"],
    equipment: ["barbell"],
    difficulty: "intermediate",
    force: "pull",
    mechanic: "compound",
    benefits: ["strength", "power", "grip strength"],
    tags: ["back", "powerlifting", "fundamental"],
  },
  {
    name: "Barbell Bench Press",
    description: "Primary horizontal pushing movement for upper body strength and mass.",
    instructions: "Lie on bench, grip bar slightly wider than shoulders, lower to chest, press up to lockout.",
    category: "strength",
    muscleGroups: ["chest", "triceps", "anterior deltoids"],
    secondaryMuscles: ["core"],
    equipment: ["barbell", "bench"],
    difficulty: "intermediate",
    force: "push",
    mechanic: "compound",
    benefits: ["strength", "muscle growth"],
    tags: ["chest", "powerlifting", "fundamental"],
  },
  {
    name: "Overhead Press",
    description: "Vertical pressing movement for shoulder development and overhead strength.",
    instructions: "Stand with feet hip-width, grip bar at shoulders, press overhead to lockout, lower with control.",
    category: "strength",
    muscleGroups: ["shoulders", "triceps"],
    secondaryMuscles: ["core", "upper chest", "traps"],
    equipment: ["barbell"],
    difficulty: "intermediate",
    force: "push",
    mechanic: "compound",
    benefits: ["strength", "shoulder stability"],
    tags: ["shoulders", "powerlifting"],
  },
  {
    name: "Barbell Row",
    description: "Horizontal pulling movement for back thickness and strength.",
    instructions: "Hinge at hips, grip bar slightly wider than shoulders, pull to lower chest, squeeze back, lower with control.",
    category: "strength",
    muscleGroups: ["lats", "rhomboids", "rear deltoids"],
    secondaryMuscles: ["biceps", "lower back", "core"],
    equipment: ["barbell"],
    difficulty: "intermediate",
    force: "pull",
    mechanic: "compound",
    benefits: ["strength", "posture"],
    tags: ["back", "rowing"],
  },
  {
    name: "Front Squat",
    description: "Quad-dominant squat variation with more upright torso position.",
    instructions: "Rest barbell on front delts, elbows high, squat deep with upright torso, drive up.",
    category: "strength",
    muscleGroups: ["quadriceps", "glutes"],
    secondaryMuscles: ["core", "upper back"],
    equipment: ["barbell", "squat rack"],
    difficulty: "advanced",
    force: "push",
    mechanic: "compound",
    benefits: ["strength", "mobility"],
    tags: ["legs", "olympic lifting"],
  },
  {
    name: "Romanian Deadlift",
    description: "Hip hinge movement emphasizing hamstring and glute development.",
    instructions: "Hold bar at hips, push hips back while lowering bar along legs, feel hamstring stretch, drive hips forward to stand.",
    category: "strength",
    muscleGroups: ["hamstrings", "glutes"],
    secondaryMuscles: ["lower back", "core"],
    equipment: ["barbell"],
    difficulty: "intermediate",
    force: "pull",
    mechanic: "compound",
    benefits: ["strength", "flexibility"],
    tags: ["legs", "hamstrings"],
  },
  {
    name: "Incline Bench Press",
    description: "Upper chest focused pressing variation.",
    instructions: "Set bench to 30-45 degrees, grip bar, lower to upper chest, press to lockout.",
    category: "strength",
    muscleGroups: ["upper chest", "anterior deltoids", "triceps"],
    secondaryMuscles: ["core"],
    equipment: ["barbell", "incline bench"],
    difficulty: "intermediate",
    force: "push",
    mechanic: "compound",
    benefits: ["strength", "muscle growth"],
    tags: ["chest", "pressing"],
  },
  {
    name: "Sumo Deadlift",
    description: "Wide stance deadlift variation emphasizing quads and adductors.",
    instructions: "Wide stance, toes out, grip inside knees, drive through heels, keep chest up.",
    category: "strength",
    muscleGroups: ["glutes", "quadriceps", "adductors"],
    secondaryMuscles: ["hamstrings", "lower back", "traps"],
    equipment: ["barbell"],
    difficulty: "intermediate",
    force: "pull",
    mechanic: "compound",
    benefits: ["strength", "hip mobility"],
    tags: ["legs", "powerlifting"],
  },
  {
    name: "Close Grip Bench Press",
    description: "Triceps-focused bench press variation.",
    instructions: "Grip bar shoulder-width or narrower, lower to lower chest, press up focusing on triceps.",
    category: "strength",
    muscleGroups: ["triceps", "chest"],
    secondaryMuscles: ["anterior deltoids"],
    equipment: ["barbell", "bench"],
    difficulty: "intermediate",
    force: "push",
    mechanic: "compound",
    benefits: ["strength", "lockout power"],
    tags: ["arms", "triceps"],
  },
  {
    name: "Weighted Pull-up",
    description: "Vertical pulling with added resistance for advanced back development.",
    instructions: "Hang from bar with weight attached, pull chin over bar, lower with control.",
    category: "strength",
    muscleGroups: ["lats", "biceps"],
    secondaryMuscles: ["rhomboids", "rear deltoids", "core"],
    equipment: ["pull-up bar", "weight belt"],
    difficulty: "advanced",
    force: "pull",
    mechanic: "compound",
    benefits: ["strength", "grip strength"],
    tags: ["back", "calisthenics"],
  },
  {
    name: "Weighted Dip",
    description: "Compound pressing for chest and triceps with added resistance.",
    instructions: "Support on parallel bars with weight, lower until upper arms parallel, press up.",
    category: "strength",
    muscleGroups: ["triceps", "chest", "anterior deltoids"],
    secondaryMuscles: ["core"],
    equipment: ["parallel bars", "weight belt"],
    difficulty: "advanced",
    force: "push",
    mechanic: "compound",
    benefits: ["strength", "muscle growth"],
    tags: ["chest", "arms", "calisthenics"],
  },
  {
    name: "Pendlay Row",
    description: "Strict barbell row from dead stop for explosive back strength.",
    instructions: "Bar on floor each rep, explosive pull to lower chest, return to floor.",
    category: "strength",
    muscleGroups: ["lats", "rhomboids"],
    secondaryMuscles: ["biceps", "lower back"],
    equipment: ["barbell"],
    difficulty: "intermediate",
    force: "pull",
    mechanic: "compound",
    benefits: ["strength", "power"],
    tags: ["back", "rowing"],
  },
  {
    name: "Bulgarian Split Squat",
    description: "Unilateral leg exercise for strength and balance.",
    instructions: "Rear foot elevated, front foot forward, lower until rear knee near floor, drive up.",
    category: "strength",
    muscleGroups: ["quadriceps", "glutes"],
    secondaryMuscles: ["hamstrings", "core"],
    equipment: ["bench", "dumbbells"],
    difficulty: "intermediate",
    force: "push",
    mechanic: "compound",
    benefits: ["strength", "balance", "mobility"],
    tags: ["legs", "unilateral"],
  },
  {
    name: "Leg Press",
    description: "Machine-based compound leg exercise.",
    instructions: "Feet shoulder-width on platform, lower weight until knees at 90 degrees, press up.",
    category: "strength",
    muscleGroups: ["quadriceps", "glutes"],
    secondaryMuscles: ["hamstrings"],
    equipment: ["leg press machine"],
    difficulty: "beginner",
    force: "push",
    mechanic: "compound",
    benefits: ["strength", "muscle growth"],
    tags: ["legs", "machine"],
  },
  {
    name: "T-Bar Row",
    description: "Back thickness builder with neutral grip option.",
    instructions: "Straddle bar or use landmine, row to chest, squeeze back, lower with control.",
    category: "strength",
    muscleGroups: ["lats", "rhomboids", "rear deltoids"],
    secondaryMuscles: ["biceps", "lower back"],
    equipment: ["barbell", "landmine"],
    difficulty: "intermediate",
    force: "pull",
    mechanic: "compound",
    benefits: ["strength", "muscle growth"],
    tags: ["back", "rowing"],
  },
  {
    name: "Hack Squat",
    description: "Machine squat variation for quad development.",
    instructions: "Back against pad, feet forward on platform, squat down, drive up through heels.",
    category: "strength",
    muscleGroups: ["quadriceps", "glutes"],
    secondaryMuscles: ["hamstrings"],
    equipment: ["hack squat machine"],
    difficulty: "beginner",
    force: "push",
    mechanic: "compound",
    benefits: ["strength", "muscle growth"],
    tags: ["legs", "machine"],
  },
  {
    name: "Dumbbell Bench Press",
    description: "Dumbbell pressing for chest with greater range of motion.",
    instructions: "Lie on bench with dumbbells, lower to chest level, press up and together.",
    category: "strength",
    muscleGroups: ["chest", "triceps", "anterior deltoids"],
    secondaryMuscles: ["core"],
    equipment: ["dumbbells", "bench"],
    difficulty: "beginner",
    force: "push",
    mechanic: "compound",
    benefits: ["strength", "stability"],
    tags: ["chest", "dumbbell"],
  },
  {
    name: "Dumbbell Row",
    description: "Unilateral back exercise for strength and muscle balance.",
    instructions: "One hand on bench, row dumbbell to hip, squeeze back, lower with control.",
    category: "strength",
    muscleGroups: ["lats", "rhomboids"],
    secondaryMuscles: ["biceps", "rear deltoids"],
    equipment: ["dumbbell", "bench"],
    difficulty: "beginner",
    force: "pull",
    mechanic: "compound",
    benefits: ["strength", "muscle balance"],
    tags: ["back", "unilateral"],
  },
  {
    name: "Goblet Squat",
    description: "Beginner-friendly squat variation with dumbbell or kettlebell.",
    instructions: "Hold weight at chest, squat deep with elbows inside knees, drive up.",
    category: "strength",
    muscleGroups: ["quadriceps", "glutes"],
    secondaryMuscles: ["core", "hamstrings"],
    equipment: ["dumbbell", "kettlebell"],
    difficulty: "beginner",
    force: "push",
    mechanic: "compound",
    benefits: ["strength", "mobility"],
    tags: ["legs", "beginner"],
  },
  {
    name: "Lat Pulldown",
    description: "Cable-based vertical pulling for lat development.",
    instructions: "Grip wide, pull bar to upper chest, squeeze lats, control the return.",
    category: "strength",
    muscleGroups: ["lats", "biceps"],
    secondaryMuscles: ["rhomboids", "rear deltoids"],
    equipment: ["cable machine", "lat pulldown bar"],
    difficulty: "beginner",
    force: "pull",
    mechanic: "compound",
    benefits: ["strength", "muscle growth"],
    tags: ["back", "cable"],
  },
  {
    name: "Seated Cable Row",
    description: "Horizontal cable pulling for back thickness.",
    instructions: "Sit with feet braced, pull handle to stomach, squeeze back, extend with control.",
    category: "strength",
    muscleGroups: ["lats", "rhomboids"],
    secondaryMuscles: ["biceps", "rear deltoids"],
    equipment: ["cable machine", "v-bar"],
    difficulty: "beginner",
    force: "pull",
    mechanic: "compound",
    benefits: ["strength", "posture"],
    tags: ["back", "cable"],
  },
  {
    name: "Trap Bar Deadlift",
    description: "Deadlift variation with neutral grip, easier on lower back.",
    instructions: "Stand inside trap bar, grip handles, drive through heels to stand, lower with control.",
    category: "strength",
    muscleGroups: ["quadriceps", "glutes", "hamstrings"],
    secondaryMuscles: ["traps", "core", "lower back"],
    equipment: ["trap bar"],
    difficulty: "beginner",
    force: "pull",
    mechanic: "compound",
    benefits: ["strength", "power"],
    tags: ["legs", "back"],
  },
  {
    name: "Landmine Press",
    description: "Angled pressing variation for shoulder-friendly overhead work.",
    instructions: "Hold end of barbell at shoulder, press up and forward at angle, lower with control.",
    category: "strength",
    muscleGroups: ["shoulders", "upper chest", "triceps"],
    secondaryMuscles: ["core"],
    equipment: ["barbell", "landmine"],
    difficulty: "intermediate",
    force: "push",
    mechanic: "compound",
    benefits: ["strength", "shoulder health"],
    tags: ["shoulders", "pressing"],
  },
  {
    name: "Pause Squat",
    description: "Squat with pause at bottom for strength out of the hole.",
    instructions: "Squat to depth, pause 2-3 seconds, drive up explosively.",
    category: "strength",
    muscleGroups: ["quadriceps", "glutes"],
    secondaryMuscles: ["core", "hamstrings"],
    equipment: ["barbell", "squat rack"],
    difficulty: "advanced",
    force: "push",
    mechanic: "compound",
    benefits: ["strength", "power"],
    tags: ["legs", "powerlifting"],
  },
  {
    name: "Deficit Deadlift",
    description: "Deadlift from elevated position for increased range of motion.",
    instructions: "Stand on 2-4 inch platform, deadlift with increased ROM.",
    category: "strength",
    muscleGroups: ["hamstrings", "glutes", "lower back"],
    secondaryMuscles: ["quadriceps", "traps"],
    equipment: ["barbell", "plates"],
    difficulty: "advanced",
    force: "pull",
    mechanic: "compound",
    benefits: ["strength", "pulling power"],
    tags: ["back", "powerlifting"],
  },
  {
    name: "Floor Press",
    description: "Bench press from floor for triceps and lockout strength.",
    instructions: "Lie on floor, lower bar until triceps touch floor, pause, press up.",
    category: "strength",
    muscleGroups: ["triceps", "chest"],
    secondaryMuscles: ["anterior deltoids"],
    equipment: ["barbell"],
    difficulty: "intermediate",
    force: "push",
    mechanic: "compound",
    benefits: ["strength", "lockout power"],
    tags: ["chest", "powerlifting"],
  },
  {
    name: "Good Morning",
    description: "Hip hinge with bar on back for posterior chain development.",
    instructions: "Bar on back, push hips back with slight knee bend, feel hamstring stretch, return upright.",
    category: "strength",
    muscleGroups: ["hamstrings", "glutes", "lower back"],
    secondaryMuscles: ["core"],
    equipment: ["barbell"],
    difficulty: "intermediate",
    force: "pull",
    mechanic: "compound",
    benefits: ["strength", "flexibility"],
    tags: ["hamstrings", "accessory"],
  },
  {
    name: "Safety Bar Squat",
    description: "Squat variation with specialty bar for reduced shoulder stress.",
    instructions: "Use safety squat bar handles, squat with neutral grip position.",
    category: "strength",
    muscleGroups: ["quadriceps", "glutes"],
    secondaryMuscles: ["core", "upper back"],
    equipment: ["safety squat bar", "squat rack"],
    difficulty: "intermediate",
    force: "push",
    mechanic: "compound",
    benefits: ["strength", "shoulder health"],
    tags: ["legs", "specialty"],
  },
  {
    name: "Zercher Squat",
    description: "Front-loaded squat holding bar in elbow crooks.",
    instructions: "Cradle bar in elbow crooks, squat deep, drive up maintaining upright torso.",
    category: "strength",
    muscleGroups: ["quadriceps", "glutes", "core"],
    secondaryMuscles: ["biceps", "upper back"],
    equipment: ["barbell"],
    difficulty: "advanced",
    force: "push",
    mechanic: "compound",
    benefits: ["strength", "core stability"],
    tags: ["legs", "specialty"],
  },

  // ============================================================================
  // STRENGTH - ISOLATION (40 exercises)
  // ============================================================================
  {
    name: "Barbell Curl",
    description: "Classic bicep builder with barbell.",
    instructions: "Stand with barbell, curl to shoulders keeping elbows stationary, lower with control.",
    category: "strength",
    muscleGroups: ["biceps"],
    secondaryMuscles: ["forearms"],
    equipment: ["barbell"],
    difficulty: "beginner",
    force: "pull",
    mechanic: "isolation",
    benefits: ["muscle growth"],
    tags: ["arms", "biceps"],
  },
  {
    name: "Dumbbell Curl",
    description: "Unilateral bicep exercise with dumbbells.",
    instructions: "Curl dumbbells alternating or together, supinate wrists at top.",
    category: "strength",
    muscleGroups: ["biceps"],
    secondaryMuscles: ["forearms"],
    equipment: ["dumbbells"],
    difficulty: "beginner",
    force: "pull",
    mechanic: "isolation",
    benefits: ["muscle growth", "balance"],
    tags: ["arms", "biceps"],
  },
  {
    name: "Hammer Curl",
    description: "Neutral grip curl for brachialis and forearm development.",
    instructions: "Hold dumbbells with palms facing each other, curl maintaining neutral grip.",
    category: "strength",
    muscleGroups: ["biceps", "brachialis"],
    secondaryMuscles: ["forearms"],
    equipment: ["dumbbells"],
    difficulty: "beginner",
    force: "pull",
    mechanic: "isolation",
    benefits: ["muscle growth", "grip strength"],
    tags: ["arms", "biceps"],
  },
  {
    name: "Preacher Curl",
    description: "Strict bicep isolation with arm support.",
    instructions: "Rest arms on preacher bench pad, curl weight, squeeze at top, lower with control.",
    category: "strength",
    muscleGroups: ["biceps"],
    secondaryMuscles: ["forearms"],
    equipment: ["preacher bench", "barbell"],
    difficulty: "beginner",
    force: "pull",
    mechanic: "isolation",
    benefits: ["muscle growth", "peak contraction"],
    tags: ["arms", "biceps"],
  },
  {
    name: "Incline Dumbbell Curl",
    description: "Bicep stretch position curl on incline bench.",
    instructions: "Lie back on incline bench, let arms hang, curl dumbbells.",
    category: "strength",
    muscleGroups: ["biceps"],
    secondaryMuscles: ["forearms"],
    equipment: ["dumbbells", "incline bench"],
    difficulty: "intermediate",
    force: "pull",
    mechanic: "isolation",
    benefits: ["muscle growth", "stretch"],
    tags: ["arms", "biceps"],
  },
  {
    name: "Tricep Pushdown",
    description: "Cable exercise for tricep development.",
    instructions: "Push cable attachment down, squeeze triceps at bottom, control the return.",
    category: "strength",
    muscleGroups: ["triceps"],
    secondaryMuscles: [],
    equipment: ["cable machine"],
    difficulty: "beginner",
    force: "push",
    mechanic: "isolation",
    benefits: ["muscle growth"],
    tags: ["arms", "triceps"],
  },
  {
    name: "Skull Crusher",
    description: "Lying tricep extension with barbell or EZ bar.",
    instructions: "Lie on bench, lower bar to forehead, extend arms, keep elbows stationary.",
    category: "strength",
    muscleGroups: ["triceps"],
    secondaryMuscles: [],
    equipment: ["EZ bar", "bench"],
    difficulty: "intermediate",
    force: "push",
    mechanic: "isolation",
    benefits: ["muscle growth"],
    tags: ["arms", "triceps"],
  },
  {
    name: "Overhead Tricep Extension",
    description: "Tricep isolation in stretched position.",
    instructions: "Hold weight overhead, lower behind head, extend up, keep elbows close.",
    category: "strength",
    muscleGroups: ["triceps"],
    secondaryMuscles: [],
    equipment: ["dumbbell", "cable machine"],
    difficulty: "beginner",
    force: "push",
    mechanic: "isolation",
    benefits: ["muscle growth"],
    tags: ["arms", "triceps"],
  },
  {
    name: "Tricep Kickback",
    description: "Isolation exercise for tricep contraction.",
    instructions: "Hinge forward, extend arm back squeezing tricep, lower with control.",
    category: "strength",
    muscleGroups: ["triceps"],
    secondaryMuscles: [],
    equipment: ["dumbbell"],
    difficulty: "beginner",
    force: "push",
    mechanic: "isolation",
    benefits: ["muscle growth"],
    tags: ["arms", "triceps"],
  },
  {
    name: "Lateral Raise",
    description: "Isolation exercise for side deltoid development.",
    instructions: "Raise dumbbells to sides until arms parallel to floor, lower with control.",
    category: "strength",
    muscleGroups: ["lateral deltoids"],
    secondaryMuscles: ["traps"],
    equipment: ["dumbbells"],
    difficulty: "beginner",
    force: "pull",
    mechanic: "isolation",
    benefits: ["muscle growth", "shoulder width"],
    tags: ["shoulders", "deltoids"],
  },
  {
    name: "Front Raise",
    description: "Isolation for anterior deltoid.",
    instructions: "Raise dumbbells to front until arms parallel to floor.",
    category: "strength",
    muscleGroups: ["anterior deltoids"],
    secondaryMuscles: ["upper chest"],
    equipment: ["dumbbells"],
    difficulty: "beginner",
    force: "push",
    mechanic: "isolation",
    benefits: ["muscle growth"],
    tags: ["shoulders", "deltoids"],
  },
  {
    name: "Rear Delt Fly",
    description: "Isolation for posterior deltoid development.",
    instructions: "Bend forward, raise dumbbells to sides squeezing rear delts.",
    category: "strength",
    muscleGroups: ["rear deltoids"],
    secondaryMuscles: ["rhomboids", "traps"],
    equipment: ["dumbbells"],
    difficulty: "beginner",
    force: "pull",
    mechanic: "isolation",
    benefits: ["muscle growth", "posture"],
    tags: ["shoulders", "rear delts"],
  },
  {
    name: "Face Pull",
    description: "Cable exercise for rear delts and external rotators.",
    instructions: "Pull rope to face, separate ends at ears, squeeze rear delts.",
    category: "strength",
    muscleGroups: ["rear deltoids", "external rotators"],
    secondaryMuscles: ["traps", "rhomboids"],
    equipment: ["cable machine", "rope attachment"],
    difficulty: "beginner",
    force: "pull",
    mechanic: "isolation",
    benefits: ["posture", "shoulder health"],
    tags: ["shoulders", "prehab"],
  },
  {
    name: "Dumbbell Fly",
    description: "Chest isolation with dumbbells.",
    instructions: "Lie on bench, lower dumbbells in arc, squeeze chest to bring together.",
    category: "strength",
    muscleGroups: ["chest"],
    secondaryMuscles: ["anterior deltoids"],
    equipment: ["dumbbells", "bench"],
    difficulty: "beginner",
    force: "push",
    mechanic: "isolation",
    benefits: ["muscle growth", "stretch"],
    tags: ["chest", "isolation"],
  },
  {
    name: "Cable Crossover",
    description: "Cable fly for chest isolation with constant tension.",
    instructions: "Stand between cables, bring handles together in arc motion.",
    category: "strength",
    muscleGroups: ["chest"],
    secondaryMuscles: ["anterior deltoids"],
    equipment: ["cable machine"],
    difficulty: "beginner",
    force: "push",
    mechanic: "isolation",
    benefits: ["muscle growth"],
    tags: ["chest", "cable"],
  },
  {
    name: "Pec Deck",
    description: "Machine fly for chest isolation.",
    instructions: "Sit in machine, bring pads together squeezing chest.",
    category: "strength",
    muscleGroups: ["chest"],
    secondaryMuscles: [],
    equipment: ["pec deck machine"],
    difficulty: "beginner",
    force: "push",
    mechanic: "isolation",
    benefits: ["muscle growth"],
    tags: ["chest", "machine"],
  },
  {
    name: "Leg Extension",
    description: "Quad isolation machine exercise.",
    instructions: "Sit in machine, extend legs fully, squeeze quads, lower with control.",
    category: "strength",
    muscleGroups: ["quadriceps"],
    secondaryMuscles: [],
    equipment: ["leg extension machine"],
    difficulty: "beginner",
    force: "push",
    mechanic: "isolation",
    benefits: ["muscle growth"],
    tags: ["legs", "machine"],
  },
  {
    name: "Leg Curl",
    description: "Hamstring isolation machine exercise.",
    instructions: "Lie face down, curl legs, squeeze hamstrings, lower with control.",
    category: "strength",
    muscleGroups: ["hamstrings"],
    secondaryMuscles: ["calves"],
    equipment: ["leg curl machine"],
    difficulty: "beginner",
    force: "pull",
    mechanic: "isolation",
    benefits: ["muscle growth"],
    tags: ["legs", "machine"],
  },
  {
    name: "Calf Raise",
    description: "Standing calf isolation exercise.",
    instructions: "Stand on edge of platform, raise onto toes, squeeze calves, lower with stretch.",
    category: "strength",
    muscleGroups: ["calves"],
    secondaryMuscles: [],
    equipment: ["calf raise machine", "smith machine"],
    difficulty: "beginner",
    force: "push",
    mechanic: "isolation",
    benefits: ["muscle growth"],
    tags: ["legs", "calves"],
  },
  {
    name: "Seated Calf Raise",
    description: "Soleus-focused calf exercise.",
    instructions: "Sit with pad on knees, raise heels, squeeze, lower with stretch.",
    category: "strength",
    muscleGroups: ["calves", "soleus"],
    secondaryMuscles: [],
    equipment: ["seated calf raise machine"],
    difficulty: "beginner",
    force: "push",
    mechanic: "isolation",
    benefits: ["muscle growth"],
    tags: ["legs", "calves"],
  },
  {
    name: "Hip Abduction",
    description: "Outer hip/glute isolation.",
    instructions: "Sit in machine, push legs apart against resistance.",
    category: "strength",
    muscleGroups: ["glutes", "hip abductors"],
    secondaryMuscles: [],
    equipment: ["hip abduction machine"],
    difficulty: "beginner",
    force: "push",
    mechanic: "isolation",
    benefits: ["muscle growth", "stability"],
    tags: ["legs", "glutes"],
  },
  {
    name: "Hip Adduction",
    description: "Inner thigh isolation.",
    instructions: "Sit in machine, squeeze legs together against resistance.",
    category: "strength",
    muscleGroups: ["adductors"],
    secondaryMuscles: [],
    equipment: ["hip adduction machine"],
    difficulty: "beginner",
    force: "pull",
    mechanic: "isolation",
    benefits: ["muscle growth", "stability"],
    tags: ["legs", "adductors"],
  },
  {
    name: "Glute Kickback",
    description: "Glute isolation with cable or machine.",
    instructions: "Kick leg back squeezing glute at top, lower with control.",
    category: "strength",
    muscleGroups: ["glutes"],
    secondaryMuscles: ["hamstrings"],
    equipment: ["cable machine", "ankle strap"],
    difficulty: "beginner",
    force: "push",
    mechanic: "isolation",
    benefits: ["muscle growth"],
    tags: ["legs", "glutes"],
  },
  {
    name: "Hip Thrust",
    description: "Glute builder with barbell across hips.",
    instructions: "Upper back on bench, bar on hips, drive hips up squeezing glutes.",
    category: "strength",
    muscleGroups: ["glutes"],
    secondaryMuscles: ["hamstrings"],
    equipment: ["barbell", "bench"],
    difficulty: "intermediate",
    force: "push",
    mechanic: "compound",
    benefits: ["strength", "muscle growth"],
    tags: ["legs", "glutes"],
  },
  {
    name: "Shrug",
    description: "Trap isolation with barbell or dumbbells.",
    instructions: "Hold weight at sides, raise shoulders towards ears, squeeze traps.",
    category: "strength",
    muscleGroups: ["traps"],
    secondaryMuscles: [],
    equipment: ["barbell", "dumbbells"],
    difficulty: "beginner",
    force: "pull",
    mechanic: "isolation",
    benefits: ["muscle growth"],
    tags: ["back", "traps"],
  },
  {
    name: "Wrist Curl",
    description: "Forearm flexor isolation.",
    instructions: "Rest forearms on bench, curl wrists up with barbell or dumbbells.",
    category: "strength",
    muscleGroups: ["forearms"],
    secondaryMuscles: [],
    equipment: ["barbell", "dumbbells"],
    difficulty: "beginner",
    force: "pull",
    mechanic: "isolation",
    benefits: ["grip strength"],
    tags: ["arms", "forearms"],
  },
  {
    name: "Reverse Wrist Curl",
    description: "Forearm extensor isolation.",
    instructions: "Rest forearms on bench palms down, extend wrists up.",
    category: "strength",
    muscleGroups: ["forearms"],
    secondaryMuscles: [],
    equipment: ["barbell", "dumbbells"],
    difficulty: "beginner",
    force: "pull",
    mechanic: "isolation",
    benefits: ["grip strength"],
    tags: ["arms", "forearms"],
  },
  {
    name: "Concentration Curl",
    description: "Strict bicep isolation with elbow braced.",
    instructions: "Sit with elbow braced on inner thigh, curl dumbbell, squeeze bicep.",
    category: "strength",
    muscleGroups: ["biceps"],
    secondaryMuscles: [],
    equipment: ["dumbbell"],
    difficulty: "beginner",
    force: "pull",
    mechanic: "isolation",
    benefits: ["muscle growth", "peak contraction"],
    tags: ["arms", "biceps"],
  },
  {
    name: "Cable Curl",
    description: "Bicep curl with constant cable tension.",
    instructions: "Curl cable attachment, squeeze biceps, lower with control.",
    category: "strength",
    muscleGroups: ["biceps"],
    secondaryMuscles: ["forearms"],
    equipment: ["cable machine"],
    difficulty: "beginner",
    force: "pull",
    mechanic: "isolation",
    benefits: ["muscle growth"],
    tags: ["arms", "biceps"],
  },
  {
    name: "Spider Curl",
    description: "Bicep curl on incline bench facing down.",
    instructions: "Lie face down on incline bench, curl dumbbells, squeeze at top.",
    category: "strength",
    muscleGroups: ["biceps"],
    secondaryMuscles: [],
    equipment: ["dumbbells", "incline bench"],
    difficulty: "intermediate",
    force: "pull",
    mechanic: "isolation",
    benefits: ["muscle growth"],
    tags: ["arms", "biceps"],
  },
  {
    name: "Reverse Curl",
    description: "Brachialis and forearm focused curl.",
    instructions: "Curl with overhand grip, keep elbows stationary.",
    category: "strength",
    muscleGroups: ["brachialis", "forearms"],
    secondaryMuscles: ["biceps"],
    equipment: ["barbell", "EZ bar"],
    difficulty: "beginner",
    force: "pull",
    mechanic: "isolation",
    benefits: ["muscle growth", "grip strength"],
    tags: ["arms", "forearms"],
  },
  {
    name: "Straight Arm Pulldown",
    description: "Lat isolation with arms extended.",
    instructions: "Stand at cable, push bar down with straight arms, squeeze lats.",
    category: "strength",
    muscleGroups: ["lats"],
    secondaryMuscles: ["triceps"],
    equipment: ["cable machine"],
    difficulty: "beginner",
    force: "pull",
    mechanic: "isolation",
    benefits: ["muscle growth", "mind-muscle connection"],
    tags: ["back", "isolation"],
  },
  {
    name: "Pullover",
    description: "Lat and serratus exercise with dumbbell.",
    instructions: "Lie on bench, lower dumbbell behind head, pull over chest.",
    category: "strength",
    muscleGroups: ["lats", "serratus"],
    secondaryMuscles: ["chest", "triceps"],
    equipment: ["dumbbell", "bench"],
    difficulty: "intermediate",
    force: "pull",
    mechanic: "isolation",
    benefits: ["muscle growth", "flexibility"],
    tags: ["back", "chest"],
  },
  {
    name: "Cable Lateral Raise",
    description: "Lateral raise with constant cable tension.",
    instructions: "Stand beside cable, raise arm to side with handle behind body.",
    category: "strength",
    muscleGroups: ["lateral deltoids"],
    secondaryMuscles: [],
    equipment: ["cable machine"],
    difficulty: "beginner",
    force: "pull",
    mechanic: "isolation",
    benefits: ["muscle growth"],
    tags: ["shoulders", "cable"],
  },
  {
    name: "Upright Row",
    description: "Shoulder and trap exercise with barbell.",
    instructions: "Pull bar up close to body to chin level, elbows high.",
    category: "strength",
    muscleGroups: ["lateral deltoids", "traps"],
    secondaryMuscles: ["biceps"],
    equipment: ["barbell"],
    difficulty: "intermediate",
    force: "pull",
    mechanic: "compound",
    benefits: ["muscle growth"],
    tags: ["shoulders", "traps"],
  },
  {
    name: "Arnold Press",
    description: "Rotating dumbbell press for complete delt development.",
    instructions: "Start with dumbbells at shoulders palms facing you, press up while rotating palms out.",
    category: "strength",
    muscleGroups: ["shoulders", "triceps"],
    secondaryMuscles: ["upper chest"],
    equipment: ["dumbbells"],
    difficulty: "intermediate",
    force: "push",
    mechanic: "compound",
    benefits: ["muscle growth", "shoulder health"],
    tags: ["shoulders", "arnold"],
  },
  {
    name: "Machine Shoulder Press",
    description: "Shoulder press with machine stability.",
    instructions: "Sit in machine, press handles overhead, lower with control.",
    category: "strength",
    muscleGroups: ["shoulders", "triceps"],
    secondaryMuscles: [],
    equipment: ["shoulder press machine"],
    difficulty: "beginner",
    force: "push",
    mechanic: "compound",
    benefits: ["strength", "muscle growth"],
    tags: ["shoulders", "machine"],
  },
  {
    name: "Lying Leg Curl",
    description: "Prone hamstring curl on machine.",
    instructions: "Lie face down, curl legs, squeeze hamstrings at top.",
    category: "strength",
    muscleGroups: ["hamstrings"],
    secondaryMuscles: [],
    equipment: ["lying leg curl machine"],
    difficulty: "beginner",
    force: "pull",
    mechanic: "isolation",
    benefits: ["muscle growth"],
    tags: ["legs", "hamstrings"],
  },
  {
    name: "Seated Leg Curl",
    description: "Seated hamstring curl on machine.",
    instructions: "Sit in machine, curl legs under seat, squeeze hamstrings.",
    category: "strength",
    muscleGroups: ["hamstrings"],
    secondaryMuscles: [],
    equipment: ["seated leg curl machine"],
    difficulty: "beginner",
    force: "pull",
    mechanic: "isolation",
    benefits: ["muscle growth"],
    tags: ["legs", "hamstrings"],
  },

  // ============================================================================
  // OLYMPIC LIFTING (10 exercises)
  // ============================================================================
  {
    name: "Power Clean",
    description: "Explosive pull from floor to rack position.",
    instructions: "Start in deadlift position, explosively extend hips and pull bar to shoulders, catch in partial squat.",
    category: "strength",
    muscleGroups: ["hamstrings", "glutes", "traps"],
    secondaryMuscles: ["quadriceps", "shoulders", "core"],
    equipment: ["barbell"],
    difficulty: "advanced",
    force: "pull",
    mechanic: "compound",
    benefits: ["power", "explosiveness", "athleticism"],
    tags: ["olympic lifting", "power"],
  },
  {
    name: "Clean and Jerk",
    description: "Full Olympic lift: clean to shoulders, jerk overhead.",
    instructions: "Clean bar to shoulders, dip and drive bar overhead with split or push jerk.",
    category: "strength",
    muscleGroups: ["full body"],
    secondaryMuscles: [],
    equipment: ["barbell"],
    difficulty: "advanced",
    force: "pull",
    mechanic: "compound",
    benefits: ["power", "strength", "coordination"],
    tags: ["olympic lifting", "competition"],
  },
  {
    name: "Snatch",
    description: "Full Olympic lift: floor to overhead in one motion.",
    instructions: "Wide grip, pull from floor, extend hips explosively, catch overhead in squat.",
    category: "strength",
    muscleGroups: ["full body"],
    secondaryMuscles: [],
    equipment: ["barbell"],
    difficulty: "advanced",
    force: "pull",
    mechanic: "compound",
    benefits: ["power", "mobility", "coordination"],
    tags: ["olympic lifting", "competition"],
  },
  {
    name: "Power Snatch",
    description: "Snatch caught in partial squat position.",
    instructions: "Wide grip, explosive pull, catch overhead without full squat.",
    category: "strength",
    muscleGroups: ["hamstrings", "glutes", "shoulders"],
    secondaryMuscles: ["core", "traps"],
    equipment: ["barbell"],
    difficulty: "advanced",
    force: "pull",
    mechanic: "compound",
    benefits: ["power", "explosiveness"],
    tags: ["olympic lifting", "power"],
  },
  {
    name: "Hang Clean",
    description: "Clean starting from hang position above knees.",
    instructions: "Start with bar at thighs, hinge slightly, explosively clean to shoulders.",
    category: "strength",
    muscleGroups: ["hamstrings", "glutes", "traps"],
    secondaryMuscles: ["quadriceps", "core"],
    equipment: ["barbell"],
    difficulty: "intermediate",
    force: "pull",
    mechanic: "compound",
    benefits: ["power", "technique"],
    tags: ["olympic lifting"],
  },
  {
    name: "Hang Snatch",
    description: "Snatch starting from hang position.",
    instructions: "Start with bar at thighs, explosively snatch to overhead.",
    category: "strength",
    muscleGroups: ["full body"],
    secondaryMuscles: [],
    equipment: ["barbell"],
    difficulty: "advanced",
    force: "pull",
    mechanic: "compound",
    benefits: ["power", "technique"],
    tags: ["olympic lifting"],
  },
  {
    name: "Push Press",
    description: "Overhead press with leg drive assistance.",
    instructions: "Dip knees slightly, drive bar overhead using leg power.",
    category: "strength",
    muscleGroups: ["shoulders", "triceps"],
    secondaryMuscles: ["quadriceps", "core"],
    equipment: ["barbell"],
    difficulty: "intermediate",
    force: "push",
    mechanic: "compound",
    benefits: ["power", "strength"],
    tags: ["olympic lifting", "pressing"],
  },
  {
    name: "Push Jerk",
    description: "Jerk with both feet landing simultaneously.",
    instructions: "Dip and drive, re-dip under bar catching with slight knee bend.",
    category: "strength",
    muscleGroups: ["shoulders", "triceps", "quadriceps"],
    secondaryMuscles: ["core"],
    equipment: ["barbell"],
    difficulty: "advanced",
    force: "push",
    mechanic: "compound",
    benefits: ["power", "overhead strength"],
    tags: ["olympic lifting"],
  },
  {
    name: "Split Jerk",
    description: "Jerk with split stance landing.",
    instructions: "Dip and drive, split feet to catch overhead in lunge position.",
    category: "strength",
    muscleGroups: ["shoulders", "triceps", "quadriceps"],
    secondaryMuscles: ["core", "hip flexors"],
    equipment: ["barbell"],
    difficulty: "advanced",
    force: "push",
    mechanic: "compound",
    benefits: ["power", "stability"],
    tags: ["olympic lifting", "competition"],
  },
  {
    name: "Clean Pull",
    description: "First and second pull of clean without catch.",
    instructions: "Perform clean pull through full extension without catching bar.",
    category: "strength",
    muscleGroups: ["hamstrings", "glutes", "traps"],
    secondaryMuscles: ["lower back"],
    equipment: ["barbell"],
    difficulty: "intermediate",
    force: "pull",
    mechanic: "compound",
    benefits: ["power", "technique"],
    tags: ["olympic lifting", "accessory"],
  },

  // ============================================================================
  // PLYOMETRICS (15 exercises)
  // ============================================================================
  {
    name: "Box Jump",
    description: "Explosive jump onto elevated box.",
    instructions: "Stand before box, explosively jump up, land softly with both feet, step down.",
    category: "plyometric",
    muscleGroups: ["quadriceps", "glutes", "calves"],
    secondaryMuscles: ["hamstrings", "core"],
    equipment: ["plyo box"],
    difficulty: "intermediate",
    force: "push",
    mechanic: "compound",
    benefits: ["power", "explosiveness"],
    tags: ["plyometrics", "jumping"],
  },
  {
    name: "Burpee",
    description: "Full body explosive movement combining squat, plank, and jump.",
    instructions: "Drop to squat, kick feet back to plank, push up, jump feet forward, explosive jump up.",
    category: "plyometric",
    muscleGroups: ["full body"],
    secondaryMuscles: [],
    equipment: ["bodyweight"],
    difficulty: "intermediate",
    force: "push",
    mechanic: "compound",
    benefits: ["conditioning", "power"],
    tags: ["plyometrics", "conditioning", "crossfit"],
  },
  {
    name: "Jump Squat",
    description: "Bodyweight squat with explosive jump at top.",
    instructions: "Squat down, explosively jump up, land softly into next rep.",
    category: "plyometric",
    muscleGroups: ["quadriceps", "glutes"],
    secondaryMuscles: ["calves", "hamstrings"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    force: "push",
    mechanic: "compound",
    benefits: ["power", "conditioning"],
    tags: ["plyometrics", "jumping"],
  },
  {
    name: "Depth Jump",
    description: "Step off box and immediately jump upon landing.",
    instructions: "Step off box, land and immediately explode into maximum height jump.",
    category: "plyometric",
    muscleGroups: ["quadriceps", "glutes", "calves"],
    secondaryMuscles: ["hamstrings"],
    equipment: ["plyo box"],
    difficulty: "advanced",
    force: "push",
    mechanic: "compound",
    benefits: ["reactive power", "explosiveness"],
    tags: ["plyometrics", "advanced"],
  },
  {
    name: "Broad Jump",
    description: "Horizontal explosive jump for maximum distance.",
    instructions: "Stand with feet together, swing arms and jump forward as far as possible.",
    category: "plyometric",
    muscleGroups: ["quadriceps", "glutes", "hamstrings"],
    secondaryMuscles: ["calves", "core"],
    equipment: ["bodyweight"],
    difficulty: "intermediate",
    force: "push",
    mechanic: "compound",
    benefits: ["power", "horizontal force"],
    tags: ["plyometrics", "jumping"],
  },
  {
    name: "Tuck Jump",
    description: "Jump bringing knees to chest at peak.",
    instructions: "Jump explosively, tuck knees to chest at top, extend for landing.",
    category: "plyometric",
    muscleGroups: ["quadriceps", "hip flexors"],
    secondaryMuscles: ["calves", "core"],
    equipment: ["bodyweight"],
    difficulty: "intermediate",
    force: "push",
    mechanic: "compound",
    benefits: ["power", "coordination"],
    tags: ["plyometrics", "jumping"],
  },
  {
    name: "Split Jump",
    description: "Alternating lunge with explosive jump between switches.",
    instructions: "Start in lunge, explosively jump and switch legs mid-air, land in opposite lunge.",
    category: "plyometric",
    muscleGroups: ["quadriceps", "glutes"],
    secondaryMuscles: ["hamstrings", "calves"],
    equipment: ["bodyweight"],
    difficulty: "intermediate",
    force: "push",
    mechanic: "compound",
    benefits: ["power", "coordination"],
    tags: ["plyometrics", "lunges"],
  },
  {
    name: "Plyo Push-up",
    description: "Push-up with explosive push to leave ground.",
    instructions: "Lower in push-up, explosively push so hands leave ground, land softly.",
    category: "plyometric",
    muscleGroups: ["chest", "triceps"],
    secondaryMuscles: ["shoulders", "core"],
    equipment: ["bodyweight"],
    difficulty: "intermediate",
    force: "push",
    mechanic: "compound",
    benefits: ["upper body power"],
    tags: ["plyometrics", "upper body"],
  },
  {
    name: "Medicine Ball Slam",
    description: "Explosive overhead throw of medicine ball to ground.",
    instructions: "Lift ball overhead, slam down forcefully, catch on bounce, repeat.",
    category: "plyometric",
    muscleGroups: ["core", "lats", "shoulders"],
    secondaryMuscles: ["triceps"],
    equipment: ["medicine ball"],
    difficulty: "beginner",
    force: "push",
    mechanic: "compound",
    benefits: ["power", "conditioning"],
    tags: ["plyometrics", "core"],
  },
  {
    name: "Medicine Ball Throw",
    description: "Chest pass or rotational throw with medicine ball.",
    instructions: "Throw ball explosively from chest or with rotation to partner or wall.",
    category: "plyometric",
    muscleGroups: ["chest", "core"],
    secondaryMuscles: ["shoulders", "triceps"],
    equipment: ["medicine ball"],
    difficulty: "beginner",
    force: "push",
    mechanic: "compound",
    benefits: ["power", "rotational strength"],
    tags: ["plyometrics", "throws"],
  },
  {
    name: "Lateral Bound",
    description: "Side-to-side explosive jumping.",
    instructions: "Stand on one leg, explosively jump laterally to other leg, stick landing.",
    category: "plyometric",
    muscleGroups: ["glutes", "quadriceps"],
    secondaryMuscles: ["adductors", "calves"],
    equipment: ["bodyweight"],
    difficulty: "intermediate",
    force: "push",
    mechanic: "compound",
    benefits: ["lateral power", "stability"],
    tags: ["plyometrics", "lateral"],
  },
  {
    name: "Skater Jump",
    description: "Lateral hopping mimicking skating motion.",
    instructions: "Hop side to side, landing on outside leg, swing opposite leg behind.",
    category: "plyometric",
    muscleGroups: ["glutes", "quadriceps"],
    secondaryMuscles: ["calves", "core"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    force: "push",
    mechanic: "compound",
    benefits: ["lateral power", "balance"],
    tags: ["plyometrics", "lateral"],
  },
  {
    name: "Single Leg Box Jump",
    description: "Box jump taking off from one leg.",
    instructions: "Stand on one leg before box, jump up, land on both feet.",
    category: "plyometric",
    muscleGroups: ["quadriceps", "glutes"],
    secondaryMuscles: ["calves", "core"],
    equipment: ["plyo box"],
    difficulty: "advanced",
    force: "push",
    mechanic: "compound",
    benefits: ["unilateral power"],
    tags: ["plyometrics", "advanced"],
  },
  {
    name: "Hurdle Hop",
    description: "Continuous jumping over hurdles.",
    instructions: "Jump over low hurdles consecutively with minimal ground contact time.",
    category: "plyometric",
    muscleGroups: ["calves", "quadriceps"],
    secondaryMuscles: ["glutes"],
    equipment: ["hurdles"],
    difficulty: "intermediate",
    force: "push",
    mechanic: "compound",
    benefits: ["reactive power", "agility"],
    tags: ["plyometrics", "agility"],
  },
  {
    name: "Ankle Hops",
    description: "Small, quick hops using only ankle extension.",
    instructions: "Keep legs straight, hop rapidly using only ankle/calf power.",
    category: "plyometric",
    muscleGroups: ["calves"],
    secondaryMuscles: [],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    force: "push",
    mechanic: "isolation",
    benefits: ["ankle stiffness", "reactive strength"],
    tags: ["plyometrics", "calves"],
  },

  // ============================================================================
  // CARDIO (20 exercises)
  // ============================================================================
  {
    name: "Running",
    description: "Steady state or interval running.",
    instructions: "Run at desired pace for set time or distance.",
    category: "cardio",
    muscleGroups: ["quadriceps", "hamstrings", "calves"],
    secondaryMuscles: ["glutes", "core"],
    equipment: ["treadmill"],
    difficulty: "beginner",
    force: "dynamic",
    mechanic: "compound",
    benefits: ["endurance", "cardiovascular health"],
    tags: ["cardio", "running"],
  },
  {
    name: "Rowing",
    description: "Full body cardio on rowing machine.",
    instructions: "Push with legs, pull handle to chest, extend arms, bend knees to return.",
    category: "cardio",
    muscleGroups: ["lats", "quadriceps", "hamstrings"],
    secondaryMuscles: ["biceps", "core", "shoulders"],
    equipment: ["rowing machine"],
    difficulty: "beginner",
    force: "pull",
    mechanic: "compound",
    benefits: ["endurance", "full body conditioning"],
    tags: ["cardio", "rowing", "crossfit"],
  },
  {
    name: "Cycling",
    description: "Stationary or outdoor cycling.",
    instructions: "Pedal at desired resistance and cadence.",
    category: "cardio",
    muscleGroups: ["quadriceps", "hamstrings", "calves"],
    secondaryMuscles: ["glutes"],
    equipment: ["bike", "stationary bike"],
    difficulty: "beginner",
    force: "push",
    mechanic: "compound",
    benefits: ["endurance", "low impact"],
    tags: ["cardio", "cycling"],
  },
  {
    name: "Jump Rope",
    description: "Continuous jumping while swinging rope.",
    instructions: "Swing rope overhead and jump as it passes under feet.",
    category: "cardio",
    muscleGroups: ["calves", "shoulders"],
    secondaryMuscles: ["forearms", "core"],
    equipment: ["jump rope"],
    difficulty: "intermediate",
    force: "push",
    mechanic: "compound",
    benefits: ["conditioning", "coordination"],
    tags: ["cardio", "crossfit"],
  },
  {
    name: "Double Under",
    description: "Jump rope passing twice per jump.",
    instructions: "Jump higher than normal, spin rope faster to pass twice under feet per jump.",
    category: "cardio",
    muscleGroups: ["calves", "shoulders"],
    secondaryMuscles: ["forearms", "core"],
    equipment: ["jump rope"],
    difficulty: "advanced",
    force: "push",
    mechanic: "compound",
    benefits: ["conditioning", "coordination"],
    tags: ["cardio", "crossfit", "skill"],
  },
  {
    name: "Assault Bike",
    description: "Fan bike with arm and leg action.",
    instructions: "Push and pull handles while pedaling for total body cardio.",
    category: "cardio",
    muscleGroups: ["full body"],
    secondaryMuscles: [],
    equipment: ["assault bike"],
    difficulty: "intermediate",
    force: "push",
    mechanic: "compound",
    benefits: ["conditioning", "full body"],
    tags: ["cardio", "crossfit", "hiit"],
  },
  {
    name: "Ski Erg",
    description: "Pulling cardio machine mimicking cross-country skiing.",
    instructions: "Pull handles down with lat drive while hinging at hips.",
    category: "cardio",
    muscleGroups: ["lats", "core", "triceps"],
    secondaryMuscles: ["shoulders", "hamstrings"],
    equipment: ["ski erg"],
    difficulty: "beginner",
    force: "pull",
    mechanic: "compound",
    benefits: ["conditioning", "upper body"],
    tags: ["cardio", "crossfit"],
  },
  {
    name: "Stair Climber",
    description: "Continuous stair climbing on machine.",
    instructions: "Step on stairs at set pace, maintain upright posture.",
    category: "cardio",
    muscleGroups: ["quadriceps", "glutes", "calves"],
    secondaryMuscles: ["hamstrings"],
    equipment: ["stair climber"],
    difficulty: "beginner",
    force: "push",
    mechanic: "compound",
    benefits: ["endurance", "leg conditioning"],
    tags: ["cardio", "stairs"],
  },
  {
    name: "Elliptical",
    description: "Low impact cardio machine.",
    instructions: "Move feet in elliptical pattern with arm handles.",
    category: "cardio",
    muscleGroups: ["quadriceps", "glutes", "hamstrings"],
    secondaryMuscles: ["arms"],
    equipment: ["elliptical"],
    difficulty: "beginner",
    force: "push",
    mechanic: "compound",
    benefits: ["endurance", "low impact"],
    tags: ["cardio"],
  },
  {
    name: "Swimming",
    description: "Full body aquatic cardio.",
    instructions: "Swim laps using various strokes.",
    category: "cardio",
    muscleGroups: ["lats", "shoulders", "core"],
    secondaryMuscles: ["chest", "triceps", "legs"],
    equipment: ["pool"],
    difficulty: "intermediate",
    force: "pull",
    mechanic: "compound",
    benefits: ["endurance", "full body", "low impact"],
    tags: ["cardio", "swimming"],
  },
  {
    name: "Battle Ropes",
    description: "Alternating or simultaneous rope waves.",
    instructions: "Create waves in heavy ropes using arm movements.",
    category: "cardio",
    muscleGroups: ["shoulders", "core"],
    secondaryMuscles: ["arms", "back"],
    equipment: ["battle ropes"],
    difficulty: "intermediate",
    force: "dynamic",
    mechanic: "compound",
    benefits: ["conditioning", "upper body"],
    tags: ["cardio", "hiit"],
  },
  {
    name: "Sprinting",
    description: "Maximum effort short distance running.",
    instructions: "Run at maximum speed for short distances.",
    category: "cardio",
    muscleGroups: ["quadriceps", "hamstrings", "glutes"],
    secondaryMuscles: ["calves", "hip flexors"],
    equipment: ["track"],
    difficulty: "intermediate",
    force: "push",
    mechanic: "compound",
    benefits: ["speed", "power", "conditioning"],
    tags: ["cardio", "sprinting", "hiit"],
  },
  {
    name: "Hill Sprints",
    description: "Sprinting up incline.",
    instructions: "Sprint up hill, walk down for recovery, repeat.",
    category: "cardio",
    muscleGroups: ["quadriceps", "glutes", "calves"],
    secondaryMuscles: ["hamstrings", "core"],
    equipment: ["hill"],
    difficulty: "intermediate",
    force: "push",
    mechanic: "compound",
    benefits: ["power", "conditioning"],
    tags: ["cardio", "sprinting"],
  },
  {
    name: "Sled Push",
    description: "Pushing weighted sled for distance.",
    instructions: "Drive sled forward with extended arms and leg drive.",
    category: "cardio",
    muscleGroups: ["quadriceps", "glutes"],
    secondaryMuscles: ["shoulders", "core", "calves"],
    equipment: ["sled"],
    difficulty: "intermediate",
    force: "push",
    mechanic: "compound",
    benefits: ["conditioning", "leg power"],
    tags: ["cardio", "conditioning"],
  },
  {
    name: "Sled Pull",
    description: "Pulling weighted sled backward.",
    instructions: "Walk backward pulling sled via rope or handles.",
    category: "cardio",
    muscleGroups: ["hamstrings", "glutes"],
    secondaryMuscles: ["core", "back"],
    equipment: ["sled"],
    difficulty: "intermediate",
    force: "pull",
    mechanic: "compound",
    benefits: ["conditioning", "posterior chain"],
    tags: ["cardio", "conditioning"],
  },
  {
    name: "Farmers Carry",
    description: "Walking while holding heavy weights.",
    instructions: "Hold heavy weights at sides, walk with upright posture.",
    category: "cardio",
    muscleGroups: ["traps", "forearms", "core"],
    secondaryMuscles: ["full body"],
    equipment: ["dumbbells", "farmer handles"],
    difficulty: "beginner",
    force: "static",
    mechanic: "compound",
    benefits: ["grip strength", "conditioning"],
    tags: ["cardio", "strongman", "carries"],
  },
  {
    name: "Walking",
    description: "Low intensity steady state cardio.",
    instructions: "Walk at moderate pace for set time or distance.",
    category: "cardio",
    muscleGroups: ["quadriceps", "calves"],
    secondaryMuscles: ["glutes", "hamstrings"],
    equipment: ["treadmill"],
    difficulty: "beginner",
    force: "dynamic",
    mechanic: "compound",
    benefits: ["recovery", "low intensity cardio"],
    tags: ["cardio", "walking"],
  },
  {
    name: "Incline Walking",
    description: "Walking on incline for increased intensity.",
    instructions: "Walk on treadmill with elevated incline.",
    category: "cardio",
    muscleGroups: ["glutes", "hamstrings", "calves"],
    secondaryMuscles: ["quadriceps"],
    equipment: ["treadmill"],
    difficulty: "beginner",
    force: "push",
    mechanic: "compound",
    benefits: ["conditioning", "glute activation"],
    tags: ["cardio", "walking"],
  },
  {
    name: "Mountain Climbers",
    description: "Plank position running movement.",
    instructions: "In plank, drive knees alternately towards chest rapidly.",
    category: "cardio",
    muscleGroups: ["core", "hip flexors"],
    secondaryMuscles: ["shoulders", "quadriceps"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    force: "dynamic",
    mechanic: "compound",
    benefits: ["conditioning", "core"],
    tags: ["cardio", "bodyweight", "hiit"],
  },
  {
    name: "High Knees",
    description: "Running in place with exaggerated knee lift.",
    instructions: "Run in place driving knees high rapidly.",
    category: "cardio",
    muscleGroups: ["hip flexors", "quadriceps"],
    secondaryMuscles: ["calves", "core"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    force: "push",
    mechanic: "compound",
    benefits: ["conditioning", "warmup"],
    tags: ["cardio", "warmup"],
  },

  // ============================================================================
  // GYMNASTICS / CALISTHENICS (25 exercises)
  // ============================================================================
  {
    name: "Pull-up",
    description: "Vertical pulling with overhand grip.",
    instructions: "Hang from bar, pull chin over bar, lower with control.",
    category: "strength",
    muscleGroups: ["lats", "biceps"],
    secondaryMuscles: ["rhomboids", "rear deltoids", "core"],
    equipment: ["pull-up bar"],
    difficulty: "intermediate",
    force: "pull",
    mechanic: "compound",
    benefits: ["strength", "grip"],
    tags: ["calisthenics", "back", "fundamental"],
  },
  {
    name: "Chin-up",
    description: "Vertical pulling with underhand grip.",
    instructions: "Hang from bar with palms facing you, pull chin over bar.",
    category: "strength",
    muscleGroups: ["lats", "biceps"],
    secondaryMuscles: ["rhomboids", "core"],
    equipment: ["pull-up bar"],
    difficulty: "intermediate",
    force: "pull",
    mechanic: "compound",
    benefits: ["strength", "bicep development"],
    tags: ["calisthenics", "back"],
  },
  {
    name: "Muscle-up",
    description: "Pull-up transitioning to dip on bar or rings.",
    instructions: "Explosive pull-up, transition over bar/rings into dip position, press to lockout.",
    category: "skill",
    muscleGroups: ["lats", "chest", "triceps"],
    secondaryMuscles: ["core", "shoulders"],
    equipment: ["pull-up bar", "rings"],
    difficulty: "advanced",
    force: "pull",
    mechanic: "compound",
    benefits: ["strength", "coordination"],
    tags: ["calisthenics", "skill", "crossfit"],
  },
  {
    name: "Dip",
    description: "Parallel bar pressing for chest and triceps.",
    instructions: "Support on bars, lower until upper arms parallel, press up to lockout.",
    category: "strength",
    muscleGroups: ["chest", "triceps"],
    secondaryMuscles: ["anterior deltoids"],
    equipment: ["parallel bars", "dip station"],
    difficulty: "intermediate",
    force: "push",
    mechanic: "compound",
    benefits: ["strength", "muscle growth"],
    tags: ["calisthenics", "pressing"],
  },
  {
    name: "Push-up",
    description: "Fundamental horizontal pushing exercise.",
    instructions: "Hands shoulder-width, lower chest to floor, push up to lockout.",
    category: "strength",
    muscleGroups: ["chest", "triceps", "anterior deltoids"],
    secondaryMuscles: ["core"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    force: "push",
    mechanic: "compound",
    benefits: ["strength", "endurance"],
    tags: ["calisthenics", "fundamental"],
  },
  {
    name: "Diamond Push-up",
    description: "Close hand push-up for triceps emphasis.",
    instructions: "Hands together forming diamond, lower chest to hands, push up.",
    category: "strength",
    muscleGroups: ["triceps", "chest"],
    secondaryMuscles: ["shoulders"],
    equipment: ["bodyweight"],
    difficulty: "intermediate",
    force: "push",
    mechanic: "compound",
    benefits: ["tricep development"],
    tags: ["calisthenics", "triceps"],
  },
  {
    name: "Pike Push-up",
    description: "Push-up in pike position for shoulder emphasis.",
    instructions: "Hips high in pike position, lower head towards floor, push up.",
    category: "strength",
    muscleGroups: ["shoulders", "triceps"],
    secondaryMuscles: ["chest"],
    equipment: ["bodyweight"],
    difficulty: "intermediate",
    force: "push",
    mechanic: "compound",
    benefits: ["shoulder strength", "handstand prep"],
    tags: ["calisthenics", "shoulders"],
  },
  {
    name: "Handstand Push-up",
    description: "Vertical pressing in handstand position.",
    instructions: "In handstand against wall, lower head to floor, press back up.",
    category: "skill",
    muscleGroups: ["shoulders", "triceps"],
    secondaryMuscles: ["core", "traps"],
    equipment: ["wall"],
    difficulty: "advanced",
    force: "push",
    mechanic: "compound",
    benefits: ["overhead strength", "balance"],
    tags: ["calisthenics", "skill", "crossfit"],
  },
  {
    name: "Handstand Hold",
    description: "Static handstand against wall or freestanding.",
    instructions: "Kick up to handstand, hold position with straight body.",
    category: "skill",
    muscleGroups: ["shoulders", "core"],
    secondaryMuscles: ["triceps", "wrists"],
    equipment: ["wall"],
    difficulty: "intermediate",
    force: "static",
    mechanic: "compound",
    benefits: ["balance", "shoulder stability"],
    tags: ["calisthenics", "skill", "gymnastics"],
  },
  {
    name: "L-Sit",
    description: "Seated hold with legs extended horizontally.",
    instructions: "Support on hands, lift legs parallel to floor, hold.",
    category: "skill",
    muscleGroups: ["core", "hip flexors"],
    secondaryMuscles: ["triceps", "shoulders"],
    equipment: ["parallettes", "floor"],
    difficulty: "intermediate",
    force: "static",
    mechanic: "isolation",
    benefits: ["core strength", "compression"],
    tags: ["calisthenics", "skill", "gymnastics"],
  },
  {
    name: "Pistol Squat",
    description: "Single leg squat to full depth.",
    instructions: "Squat on one leg with other extended forward, stand back up.",
    category: "strength",
    muscleGroups: ["quadriceps", "glutes"],
    secondaryMuscles: ["hamstrings", "core"],
    equipment: ["bodyweight"],
    difficulty: "advanced",
    force: "push",
    mechanic: "compound",
    benefits: ["unilateral strength", "mobility"],
    tags: ["calisthenics", "skill", "legs"],
  },
  {
    name: "Plank",
    description: "Static core hold in push-up position.",
    instructions: "Hold body straight from head to heels, forearms or hands on floor.",
    category: "strength",
    muscleGroups: ["core"],
    secondaryMuscles: ["shoulders", "glutes"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    force: "static",
    mechanic: "isolation",
    benefits: ["core stability"],
    tags: ["core", "fundamental"],
  },
  {
    name: "Side Plank",
    description: "Lateral core hold.",
    instructions: "Support on one forearm, stack feet, hold body straight.",
    category: "strength",
    muscleGroups: ["obliques", "core"],
    secondaryMuscles: ["shoulders"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    force: "static",
    mechanic: "isolation",
    benefits: ["lateral stability"],
    tags: ["core"],
  },
  {
    name: "Hollow Body Hold",
    description: "Gymnastics core position with curved lower back.",
    instructions: "Lie on back, lift shoulders and legs, press lower back to floor.",
    category: "skill",
    muscleGroups: ["core"],
    secondaryMuscles: ["hip flexors"],
    equipment: ["bodyweight"],
    difficulty: "intermediate",
    force: "static",
    mechanic: "isolation",
    benefits: ["core strength", "gymnastics foundation"],
    tags: ["core", "gymnastics"],
  },
  {
    name: "Arch Body Hold",
    description: "Opposite of hollow, arched position face down.",
    instructions: "Lie face down, lift arms and legs, squeeze back extensors.",
    category: "skill",
    muscleGroups: ["lower back", "glutes"],
    secondaryMuscles: ["hamstrings"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    force: "static",
    mechanic: "isolation",
    benefits: ["back strength"],
    tags: ["core", "gymnastics"],
  },
  {
    name: "Ring Row",
    description: "Horizontal pull on gymnastics rings.",
    instructions: "Hang from rings, body straight, pull chest to rings.",
    category: "strength",
    muscleGroups: ["lats", "rhomboids"],
    secondaryMuscles: ["biceps", "core"],
    equipment: ["rings"],
    difficulty: "beginner",
    force: "pull",
    mechanic: "compound",
    benefits: ["pull-up progression"],
    tags: ["calisthenics", "back"],
  },
  {
    name: "Ring Dip",
    description: "Dip on unstable rings.",
    instructions: "Support on rings, lower until upper arms parallel, press up.",
    category: "strength",
    muscleGroups: ["chest", "triceps"],
    secondaryMuscles: ["shoulders", "core"],
    equipment: ["rings"],
    difficulty: "advanced",
    force: "push",
    mechanic: "compound",
    benefits: ["stability", "strength"],
    tags: ["calisthenics", "rings", "crossfit"],
  },
  {
    name: "Toes to Bar",
    description: "Hanging leg raise touching bar with toes.",
    instructions: "Hang from bar, swing legs up to touch bar with toes.",
    category: "strength",
    muscleGroups: ["core", "hip flexors"],
    secondaryMuscles: ["lats", "grip"],
    equipment: ["pull-up bar"],
    difficulty: "intermediate",
    force: "pull",
    mechanic: "compound",
    benefits: ["core strength", "grip"],
    tags: ["core", "crossfit"],
  },
  {
    name: "Knees to Elbow",
    description: "Hanging knee raise to elbows.",
    instructions: "Hang from bar, bring knees up to touch elbows.",
    category: "strength",
    muscleGroups: ["core", "hip flexors"],
    secondaryMuscles: ["lats"],
    equipment: ["pull-up bar"],
    difficulty: "intermediate",
    force: "pull",
    mechanic: "compound",
    benefits: ["core strength"],
    tags: ["core", "crossfit"],
  },
  {
    name: "Hanging Leg Raise",
    description: "Hanging core exercise lifting straight legs.",
    instructions: "Hang from bar, raise straight legs parallel to floor.",
    category: "strength",
    muscleGroups: ["core", "hip flexors"],
    secondaryMuscles: ["grip"],
    equipment: ["pull-up bar"],
    difficulty: "intermediate",
    force: "pull",
    mechanic: "isolation",
    benefits: ["core strength"],
    tags: ["core"],
  },
  {
    name: "Inverted Row",
    description: "Bodyweight row under bar or rings.",
    instructions: "Lie under bar, grip and pull chest to bar, lower with control.",
    category: "strength",
    muscleGroups: ["lats", "rhomboids"],
    secondaryMuscles: ["biceps", "core"],
    equipment: ["barbell", "smith machine"],
    difficulty: "beginner",
    force: "pull",
    mechanic: "compound",
    benefits: ["pull-up progression"],
    tags: ["calisthenics", "back"],
  },
  {
    name: "Archer Push-up",
    description: "Wide push-up shifting weight side to side.",
    instructions: "Wide push-up position, lower towards one hand, push back up.",
    category: "strength",
    muscleGroups: ["chest", "triceps"],
    secondaryMuscles: ["core"],
    equipment: ["bodyweight"],
    difficulty: "advanced",
    force: "push",
    mechanic: "compound",
    benefits: ["unilateral strength"],
    tags: ["calisthenics", "progression"],
  },
  {
    name: "Bodyweight Squat",
    description: "Air squat without weight.",
    instructions: "Feet shoulder-width, squat to parallel or below, stand up.",
    category: "strength",
    muscleGroups: ["quadriceps", "glutes"],
    secondaryMuscles: ["hamstrings", "core"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    force: "push",
    mechanic: "compound",
    benefits: ["movement foundation"],
    tags: ["calisthenics", "fundamental"],
  },
  {
    name: "Lunge",
    description: "Alternating stepping leg exercise.",
    instructions: "Step forward, lower back knee to floor, push back to start.",
    category: "strength",
    muscleGroups: ["quadriceps", "glutes"],
    secondaryMuscles: ["hamstrings"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    force: "push",
    mechanic: "compound",
    benefits: ["leg strength", "balance"],
    tags: ["legs", "fundamental"],
  },
  {
    name: "Walking Lunge",
    description: "Continuous lunges moving forward.",
    instructions: "Lunge forward, bring back leg through to next lunge.",
    category: "strength",
    muscleGroups: ["quadriceps", "glutes"],
    secondaryMuscles: ["hamstrings", "core"],
    equipment: ["bodyweight", "dumbbells"],
    difficulty: "beginner",
    force: "push",
    mechanic: "compound",
    benefits: ["leg strength", "conditioning"],
    tags: ["legs", "conditioning"],
  },

  // ============================================================================
  // MOBILITY / FLEXIBILITY (30 exercises)
  // ============================================================================
  {
    name: "Hip Flexor Stretch",
    description: "Kneeling stretch for hip flexors.",
    instructions: "Kneel on one knee, push hips forward, feel stretch in hip flexor.",
    category: "flexibility",
    muscleGroups: ["hip flexors"],
    secondaryMuscles: ["quadriceps"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    force: "static",
    mechanic: "isolation",
    benefits: ["flexibility", "hip mobility"],
    tags: ["stretching", "hips"],
  },
  {
    name: "Pigeon Pose",
    description: "Deep hip opener from yoga.",
    instructions: "Front leg bent, back leg extended, fold forward over front leg.",
    category: "flexibility",
    muscleGroups: ["glutes", "hip rotators"],
    secondaryMuscles: ["hip flexors"],
    equipment: ["bodyweight"],
    difficulty: "intermediate",
    force: "static",
    mechanic: "isolation",
    benefits: ["hip flexibility"],
    tags: ["yoga", "hips"],
  },
  {
    name: "90/90 Stretch",
    description: "Hip mobility with both legs at 90 degrees.",
    instructions: "Sit with both legs bent at 90 degrees, rotate hips between positions.",
    category: "flexibility",
    muscleGroups: ["hip rotators", "glutes"],
    secondaryMuscles: [],
    equipment: ["bodyweight"],
    difficulty: "intermediate",
    force: "dynamic",
    mechanic: "isolation",
    benefits: ["hip mobility"],
    tags: ["mobility", "hips"],
  },
  {
    name: "World's Greatest Stretch",
    description: "Dynamic full body stretch sequence.",
    instructions: "Lunge position, rotate and reach, multiple movement patterns.",
    category: "flexibility",
    muscleGroups: ["hip flexors", "thoracic spine", "hamstrings"],
    secondaryMuscles: ["glutes", "shoulders"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    force: "dynamic",
    mechanic: "compound",
    benefits: ["full body mobility"],
    tags: ["warmup", "mobility"],
  },
  {
    name: "Cat-Cow",
    description: "Spinal mobility exercise on all fours.",
    instructions: "Alternate between arching and rounding spine.",
    category: "flexibility",
    muscleGroups: ["spine"],
    secondaryMuscles: ["core"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    force: "dynamic",
    mechanic: "isolation",
    benefits: ["spinal mobility"],
    tags: ["mobility", "warmup", "yoga"],
  },
  {
    name: "Thoracic Rotation",
    description: "Upper back rotation stretch.",
    instructions: "On all fours or side lying, rotate thoracic spine while reaching.",
    category: "flexibility",
    muscleGroups: ["thoracic spine"],
    secondaryMuscles: ["shoulders"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    force: "dynamic",
    mechanic: "isolation",
    benefits: ["upper back mobility"],
    tags: ["mobility", "spine"],
  },
  {
    name: "Downward Dog",
    description: "Yoga pose stretching posterior chain.",
    instructions: "Inverted V position, press heels towards floor, push through shoulders.",
    category: "flexibility",
    muscleGroups: ["hamstrings", "calves", "shoulders"],
    secondaryMuscles: ["lats"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    force: "static",
    mechanic: "compound",
    benefits: ["flexibility", "shoulder stability"],
    tags: ["yoga"],
  },
  {
    name: "Upward Dog",
    description: "Yoga pose opening chest and hip flexors.",
    instructions: "Press up from floor, chest forward, hips off ground.",
    category: "flexibility",
    muscleGroups: ["hip flexors", "chest"],
    secondaryMuscles: ["lower back"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    force: "static",
    mechanic: "compound",
    benefits: ["flexibility"],
    tags: ["yoga"],
  },
  {
    name: "Child's Pose",
    description: "Resting pose stretching back and hips.",
    instructions: "Kneel and sit back on heels, reach arms forward, relax.",
    category: "flexibility",
    muscleGroups: ["lower back", "lats"],
    secondaryMuscles: ["hips"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    force: "static",
    mechanic: "compound",
    benefits: ["relaxation", "stretching"],
    tags: ["yoga", "recovery"],
  },
  {
    name: "Couch Stretch",
    description: "Intense hip flexor and quad stretch.",
    instructions: "Knee against wall, other foot forward in lunge, drive hips forward.",
    category: "flexibility",
    muscleGroups: ["hip flexors", "quadriceps"],
    secondaryMuscles: [],
    equipment: ["wall"],
    difficulty: "intermediate",
    force: "static",
    mechanic: "isolation",
    benefits: ["hip flexibility"],
    tags: ["mobility", "hips"],
  },
  {
    name: "Hamstring Stretch",
    description: "Seated or standing hamstring stretch.",
    instructions: "Extend leg, hinge at hips reaching towards toes.",
    category: "flexibility",
    muscleGroups: ["hamstrings"],
    secondaryMuscles: ["calves"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    force: "static",
    mechanic: "isolation",
    benefits: ["hamstring flexibility"],
    tags: ["stretching"],
  },
  {
    name: "Quad Stretch",
    description: "Standing or lying quadriceps stretch.",
    instructions: "Pull heel towards glute, keep knees together.",
    category: "flexibility",
    muscleGroups: ["quadriceps"],
    secondaryMuscles: ["hip flexors"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    force: "static",
    mechanic: "isolation",
    benefits: ["quad flexibility"],
    tags: ["stretching"],
  },
  {
    name: "Calf Stretch",
    description: "Wall or step calf stretch.",
    instructions: "Press heel down with leg extended, lean into wall.",
    category: "flexibility",
    muscleGroups: ["calves"],
    secondaryMuscles: [],
    equipment: ["wall"],
    difficulty: "beginner",
    force: "static",
    mechanic: "isolation",
    benefits: ["calf flexibility"],
    tags: ["stretching"],
  },
  {
    name: "Chest Stretch",
    description: "Doorway or corner chest stretch.",
    instructions: "Place arm on wall, rotate body away, feel chest stretch.",
    category: "flexibility",
    muscleGroups: ["chest"],
    secondaryMuscles: ["anterior deltoids"],
    equipment: ["wall"],
    difficulty: "beginner",
    force: "static",
    mechanic: "isolation",
    benefits: ["chest flexibility", "posture"],
    tags: ["stretching"],
  },
  {
    name: "Lat Stretch",
    description: "Hanging or doorway lat stretch.",
    instructions: "Hold onto bar or doorframe, lean away to stretch lat.",
    category: "flexibility",
    muscleGroups: ["lats"],
    secondaryMuscles: ["triceps"],
    equipment: ["pull-up bar", "doorway"],
    difficulty: "beginner",
    force: "static",
    mechanic: "isolation",
    benefits: ["lat flexibility"],
    tags: ["stretching"],
  },
  {
    name: "Shoulder Dislocate",
    description: "Shoulder mobility with dowel or band.",
    instructions: "Hold dowel wide, pass overhead and behind back, return.",
    category: "flexibility",
    muscleGroups: ["shoulders"],
    secondaryMuscles: ["chest"],
    equipment: ["PVC pipe", "band"],
    difficulty: "intermediate",
    force: "dynamic",
    mechanic: "isolation",
    benefits: ["shoulder mobility"],
    tags: ["mobility", "shoulders"],
  },
  {
    name: "Wall Slide",
    description: "Shoulder and thoracic mobility against wall.",
    instructions: "Back against wall, slide arms up and down maintaining contact.",
    category: "flexibility",
    muscleGroups: ["shoulders", "thoracic spine"],
    secondaryMuscles: ["traps"],
    equipment: ["wall"],
    difficulty: "beginner",
    force: "dynamic",
    mechanic: "isolation",
    benefits: ["shoulder mobility", "posture"],
    tags: ["mobility", "shoulders"],
  },
  {
    name: "Foam Roll Back",
    description: "Self-massage for upper back.",
    instructions: "Lie on foam roller, roll upper back, pause on tight spots.",
    category: "flexibility",
    muscleGroups: ["upper back"],
    secondaryMuscles: [],
    equipment: ["foam roller"],
    difficulty: "beginner",
    force: "static",
    mechanic: "isolation",
    benefits: ["tissue quality", "mobility"],
    tags: ["recovery", "foam rolling"],
  },
  {
    name: "Foam Roll Quads",
    description: "Self-massage for quadriceps.",
    instructions: "Face down on roller, roll from hip to knee on quads.",
    category: "flexibility",
    muscleGroups: ["quadriceps"],
    secondaryMuscles: [],
    equipment: ["foam roller"],
    difficulty: "beginner",
    force: "static",
    mechanic: "isolation",
    benefits: ["tissue quality"],
    tags: ["recovery", "foam rolling"],
  },
  {
    name: "Foam Roll IT Band",
    description: "Self-massage for lateral thigh.",
    instructions: "Lie on side, roll from hip to knee on outer thigh.",
    category: "flexibility",
    muscleGroups: ["IT band"],
    secondaryMuscles: ["quadriceps"],
    equipment: ["foam roller"],
    difficulty: "beginner",
    force: "static",
    mechanic: "isolation",
    benefits: ["tissue quality"],
    tags: ["recovery", "foam rolling"],
  },
  {
    name: "Foam Roll Glutes",
    description: "Self-massage for glutes.",
    instructions: "Sit on roller, cross ankle over knee, roll glute.",
    category: "flexibility",
    muscleGroups: ["glutes"],
    secondaryMuscles: ["hip rotators"],
    equipment: ["foam roller"],
    difficulty: "beginner",
    force: "static",
    mechanic: "isolation",
    benefits: ["tissue quality"],
    tags: ["recovery", "foam rolling"],
  },
  {
    name: "Foam Roll Lats",
    description: "Self-massage for lats.",
    instructions: "Lie on side, arm overhead, roll lat area.",
    category: "flexibility",
    muscleGroups: ["lats"],
    secondaryMuscles: [],
    equipment: ["foam roller"],
    difficulty: "beginner",
    force: "static",
    mechanic: "isolation",
    benefits: ["tissue quality"],
    tags: ["recovery", "foam rolling"],
  },
  {
    name: "Foam Roll Calves",
    description: "Self-massage for calves.",
    instructions: "Sit with calf on roller, roll from ankle to knee.",
    category: "flexibility",
    muscleGroups: ["calves"],
    secondaryMuscles: [],
    equipment: ["foam roller"],
    difficulty: "beginner",
    force: "static",
    mechanic: "isolation",
    benefits: ["tissue quality"],
    tags: ["recovery", "foam rolling"],
  },
  {
    name: "Lacrosse Ball Pec",
    description: "Deep tissue release for pectorals.",
    instructions: "Place ball against wall, lean into pec, move around tight spots.",
    category: "flexibility",
    muscleGroups: ["chest"],
    secondaryMuscles: [],
    equipment: ["lacrosse ball"],
    difficulty: "intermediate",
    force: "static",
    mechanic: "isolation",
    benefits: ["tissue quality"],
    tags: ["recovery", "trigger point"],
  },
  {
    name: "Lacrosse Ball Glute",
    description: "Deep tissue release for glutes and piriformis.",
    instructions: "Sit on ball, roll around glute, pause on trigger points.",
    category: "flexibility",
    muscleGroups: ["glutes", "piriformis"],
    secondaryMuscles: [],
    equipment: ["lacrosse ball"],
    difficulty: "intermediate",
    force: "static",
    mechanic: "isolation",
    benefits: ["tissue quality"],
    tags: ["recovery", "trigger point"],
  },
  {
    name: "Banded Hip Distraction",
    description: "Joint mobilization with band.",
    instructions: "Loop band around hip, step away creating tension, move into various positions.",
    category: "flexibility",
    muscleGroups: ["hips"],
    secondaryMuscles: [],
    equipment: ["resistance band"],
    difficulty: "intermediate",
    force: "dynamic",
    mechanic: "isolation",
    benefits: ["joint mobility"],
    tags: ["mobility", "banded"],
  },
  {
    name: "Banded Shoulder Distraction",
    description: "Joint mobilization for shoulder.",
    instructions: "Band around wrist, step away, move shoulder through various positions.",
    category: "flexibility",
    muscleGroups: ["shoulders"],
    secondaryMuscles: [],
    equipment: ["resistance band"],
    difficulty: "intermediate",
    force: "dynamic",
    mechanic: "isolation",
    benefits: ["joint mobility"],
    tags: ["mobility", "banded"],
  },
  {
    name: "Ankle Mobility",
    description: "Knee-over-toe ankle stretch.",
    instructions: "Foot on ground, drive knee forward over toes.",
    category: "flexibility",
    muscleGroups: ["ankles", "calves"],
    secondaryMuscles: [],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    force: "dynamic",
    mechanic: "isolation",
    benefits: ["ankle mobility"],
    tags: ["mobility", "ankles"],
  },
  {
    name: "Deep Squat Hold",
    description: "Isometric hold in deep squat position.",
    instructions: "Squat as deep as possible, hold position with upright torso.",
    category: "flexibility",
    muscleGroups: ["hips", "ankles"],
    secondaryMuscles: ["quadriceps", "glutes"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    force: "static",
    mechanic: "compound",
    benefits: ["squat mobility"],
    tags: ["mobility", "fundamental"],
  },

  // ============================================================================
  // SPORT-SPECIFIC / AGILITY (30 exercises)
  // ============================================================================
  {
    name: "Ladder Drill - In-Out",
    description: "Agility ladder stepping in and out.",
    instructions: "Step both feet in, then both feet out, moving down ladder.",
    category: "sport",
    muscleGroups: ["calves", "hip flexors"],
    secondaryMuscles: ["quadriceps"],
    equipment: ["agility ladder"],
    difficulty: "beginner",
    force: "dynamic",
    mechanic: "compound",
    benefits: ["agility", "footwork"],
    tags: ["agility", "sport"],
  },
  {
    name: "Ladder Drill - Lateral",
    description: "Side-to-side agility ladder work.",
    instructions: "Move laterally through ladder with quick feet.",
    category: "sport",
    muscleGroups: ["hip abductors", "calves"],
    secondaryMuscles: ["quadriceps"],
    equipment: ["agility ladder"],
    difficulty: "beginner",
    force: "dynamic",
    mechanic: "compound",
    benefits: ["lateral agility"],
    tags: ["agility", "sport"],
  },
  {
    name: "Cone Drill - Figure 8",
    description: "Running figure 8 pattern around cones.",
    instructions: "Sprint and cut around cones in figure 8 pattern.",
    category: "sport",
    muscleGroups: ["quadriceps", "glutes"],
    secondaryMuscles: ["calves", "core"],
    equipment: ["cones"],
    difficulty: "intermediate",
    force: "dynamic",
    mechanic: "compound",
    benefits: ["change of direction"],
    tags: ["agility", "sport"],
  },
  {
    name: "Cone Drill - 5-10-5",
    description: "Pro agility shuttle drill.",
    instructions: "5 yards right, 10 yards left, 5 yards right.",
    category: "sport",
    muscleGroups: ["quadriceps", "glutes"],
    secondaryMuscles: ["calves"],
    equipment: ["cones"],
    difficulty: "intermediate",
    force: "dynamic",
    mechanic: "compound",
    benefits: ["change of direction", "acceleration"],
    tags: ["agility", "combine"],
  },
  {
    name: "T-Drill",
    description: "T-shaped agility course.",
    instructions: "Sprint forward, shuffle left, shuffle right, backpedal.",
    category: "sport",
    muscleGroups: ["quadriceps", "hip abductors"],
    secondaryMuscles: ["calves"],
    equipment: ["cones"],
    difficulty: "intermediate",
    force: "dynamic",
    mechanic: "compound",
    benefits: ["multi-directional agility"],
    tags: ["agility", "sport"],
  },
  {
    name: "Backpedal",
    description: "Running backwards for sport-specific conditioning.",
    instructions: "Run backwards with short quick steps, stay low.",
    category: "sport",
    muscleGroups: ["quadriceps", "calves"],
    secondaryMuscles: ["glutes"],
    equipment: ["none"],
    difficulty: "beginner",
    force: "dynamic",
    mechanic: "compound",
    benefits: ["sport-specific movement"],
    tags: ["agility", "sport"],
  },
  {
    name: "Lateral Shuffle",
    description: "Side-to-side shuffling movement.",
    instructions: "Stay low, shuffle laterally without crossing feet.",
    category: "sport",
    muscleGroups: ["hip abductors", "quadriceps"],
    secondaryMuscles: ["calves"],
    equipment: ["none"],
    difficulty: "beginner",
    force: "dynamic",
    mechanic: "compound",
    benefits: ["lateral movement"],
    tags: ["agility", "sport"],
  },
  {
    name: "Carioca",
    description: "Lateral crossover stepping drill.",
    instructions: "Move laterally crossing feet front and back.",
    category: "sport",
    muscleGroups: ["hip rotators", "hip abductors"],
    secondaryMuscles: ["core"],
    equipment: ["none"],
    difficulty: "beginner",
    force: "dynamic",
    mechanic: "compound",
    benefits: ["hip mobility", "coordination"],
    tags: ["agility", "warmup"],
  },
  {
    name: "Sprint Start",
    description: "Explosive acceleration from standing or blocks.",
    instructions: "Drive out of stance with powerful arm and leg action.",
    category: "sport",
    muscleGroups: ["quadriceps", "glutes", "hamstrings"],
    secondaryMuscles: ["calves", "core"],
    equipment: ["track"],
    difficulty: "intermediate",
    force: "push",
    mechanic: "compound",
    benefits: ["acceleration", "power"],
    tags: ["sprinting", "speed"],
  },
  {
    name: "A-Skip",
    description: "Skipping drill for running mechanics.",
    instructions: "Skip while driving knee high with each step.",
    category: "sport",
    muscleGroups: ["hip flexors", "calves"],
    secondaryMuscles: ["quadriceps"],
    equipment: ["none"],
    difficulty: "beginner",
    force: "dynamic",
    mechanic: "compound",
    benefits: ["running mechanics"],
    tags: ["warmup", "sprinting"],
  },
  {
    name: "B-Skip",
    description: "Skipping drill with leg extension.",
    instructions: "A-skip with leg extending forward before ground contact.",
    category: "sport",
    muscleGroups: ["hip flexors", "hamstrings"],
    secondaryMuscles: ["calves"],
    equipment: ["none"],
    difficulty: "intermediate",
    force: "dynamic",
    mechanic: "compound",
    benefits: ["running mechanics"],
    tags: ["warmup", "sprinting"],
  },
  {
    name: "High Knee Run",
    description: "Running with exaggerated knee drive.",
    instructions: "Run driving knees to hip height with each stride.",
    category: "sport",
    muscleGroups: ["hip flexors", "calves"],
    secondaryMuscles: ["quadriceps", "core"],
    equipment: ["none"],
    difficulty: "beginner",
    force: "dynamic",
    mechanic: "compound",
    benefits: ["running mechanics", "conditioning"],
    tags: ["warmup", "sprinting"],
  },
  {
    name: "Butt Kicks",
    description: "Running with heels kicking towards glutes.",
    instructions: "Run with focus on bringing heels to glutes quickly.",
    category: "sport",
    muscleGroups: ["hamstrings", "calves"],
    secondaryMuscles: ["quadriceps"],
    equipment: ["none"],
    difficulty: "beginner",
    force: "dynamic",
    mechanic: "compound",
    benefits: ["running mechanics"],
    tags: ["warmup", "sprinting"],
  },
  {
    name: "Wall Drive",
    description: "Sprint drill against wall for drive phase.",
    instructions: "Lean against wall, drive knees alternately mimicking sprint start.",
    category: "sport",
    muscleGroups: ["hip flexors", "glutes"],
    secondaryMuscles: ["core", "calves"],
    equipment: ["wall"],
    difficulty: "beginner",
    force: "dynamic",
    mechanic: "compound",
    benefits: ["sprint mechanics"],
    tags: ["sprinting", "technique"],
  },
  {
    name: "Resisted Sprint",
    description: "Sprinting against band or sled resistance.",
    instructions: "Sprint while pulling against resistance from sled or band.",
    category: "sport",
    muscleGroups: ["quadriceps", "glutes", "hamstrings"],
    secondaryMuscles: ["calves", "core"],
    equipment: ["sled", "resistance band"],
    difficulty: "intermediate",
    force: "push",
    mechanic: "compound",
    benefits: ["acceleration", "power"],
    tags: ["sprinting", "resisted"],
  },
  {
    name: "Overspeed Sprint",
    description: "Sprinting with assistance for supramaximal speed.",
    instructions: "Sprint downhill or with band assistance to run faster than max.",
    category: "sport",
    muscleGroups: ["hamstrings", "hip flexors"],
    secondaryMuscles: ["quadriceps", "calves"],
    equipment: ["hill", "band"],
    difficulty: "advanced",
    force: "dynamic",
    mechanic: "compound",
    benefits: ["max velocity"],
    tags: ["sprinting", "advanced"],
  },
  {
    name: "Kettlebell Swing",
    description: "Hip hinge power exercise with kettlebell.",
    instructions: "Hinge at hips, swing kettlebell between legs, drive hips to swing up.",
    category: "strength",
    muscleGroups: ["glutes", "hamstrings"],
    secondaryMuscles: ["core", "shoulders", "back"],
    equipment: ["kettlebell"],
    difficulty: "intermediate",
    force: "pull",
    mechanic: "compound",
    benefits: ["power", "conditioning"],
    tags: ["kettlebell", "hiit", "crossfit"],
  },
  {
    name: "Kettlebell Snatch",
    description: "Single arm swing to overhead in one motion.",
    instructions: "Swing kettlebell and punch through to overhead in one movement.",
    category: "strength",
    muscleGroups: ["full body"],
    secondaryMuscles: [],
    equipment: ["kettlebell"],
    difficulty: "advanced",
    force: "pull",
    mechanic: "compound",
    benefits: ["power", "conditioning"],
    tags: ["kettlebell", "skill"],
  },
  {
    name: "Kettlebell Clean",
    description: "Swing to rack position.",
    instructions: "Swing kettlebell and catch in rack position at shoulder.",
    category: "strength",
    muscleGroups: ["glutes", "shoulders"],
    secondaryMuscles: ["core", "biceps"],
    equipment: ["kettlebell"],
    difficulty: "intermediate",
    force: "pull",
    mechanic: "compound",
    benefits: ["power", "technique"],
    tags: ["kettlebell"],
  },
  {
    name: "Turkish Get-up",
    description: "Floor to standing while holding weight overhead.",
    instructions: "Lie down with weight overhead, stand up through specific sequence while keeping weight overhead.",
    category: "strength",
    muscleGroups: ["full body"],
    secondaryMuscles: [],
    equipment: ["kettlebell", "dumbbell"],
    difficulty: "advanced",
    force: "dynamic",
    mechanic: "compound",
    benefits: ["stability", "mobility", "strength"],
    tags: ["kettlebell", "skill"],
  },
  {
    name: "Wall Ball",
    description: "Squat and throw medicine ball to target.",
    instructions: "Squat holding ball at chest, stand and throw to target on wall, catch and repeat.",
    category: "cardio",
    muscleGroups: ["quadriceps", "glutes", "shoulders"],
    secondaryMuscles: ["core", "triceps"],
    equipment: ["medicine ball", "wall"],
    difficulty: "intermediate",
    force: "push",
    mechanic: "compound",
    benefits: ["conditioning", "power"],
    tags: ["crossfit", "hiit"],
  },
  {
    name: "Thruster",
    description: "Front squat into overhead press.",
    instructions: "Front squat, drive up and press weight overhead in one fluid motion.",
    category: "strength",
    muscleGroups: ["quadriceps", "glutes", "shoulders"],
    secondaryMuscles: ["core", "triceps"],
    equipment: ["barbell", "dumbbells"],
    difficulty: "intermediate",
    force: "push",
    mechanic: "compound",
    benefits: ["conditioning", "full body strength"],
    tags: ["crossfit", "hiit"],
  },
  {
    name: "Sumo Deadlift High Pull",
    description: "Wide stance deadlift to high pull.",
    instructions: "Sumo stance, deadlift and pull to chin height in one motion.",
    category: "strength",
    muscleGroups: ["glutes", "traps"],
    secondaryMuscles: ["hamstrings", "shoulders"],
    equipment: ["barbell", "kettlebell"],
    difficulty: "intermediate",
    force: "pull",
    mechanic: "compound",
    benefits: ["power", "conditioning"],
    tags: ["crossfit"],
  },
  {
    name: "Box Step-up",
    description: "Stepping onto elevated box.",
    instructions: "Step onto box, drive through heel, step down, alternate legs.",
    category: "strength",
    muscleGroups: ["quadriceps", "glutes"],
    secondaryMuscles: ["hamstrings"],
    equipment: ["plyo box"],
    difficulty: "beginner",
    force: "push",
    mechanic: "compound",
    benefits: ["leg strength", "unilateral"],
    tags: ["legs", "crossfit"],
  },
  {
    name: "Sandbag Clean",
    description: "Cleaning sandbag to shoulder.",
    instructions: "Deadlift sandbag, explosively clean to shoulder.",
    category: "strength",
    muscleGroups: ["full body"],
    secondaryMuscles: [],
    equipment: ["sandbag"],
    difficulty: "intermediate",
    force: "pull",
    mechanic: "compound",
    benefits: ["functional strength"],
    tags: ["strongman", "functional"],
  },
  {
    name: "Sandbag Carry",
    description: "Carrying sandbag for distance.",
    instructions: "Hold sandbag in bear hug or on shoulder, walk for distance.",
    category: "cardio",
    muscleGroups: ["core", "shoulders"],
    secondaryMuscles: ["full body"],
    equipment: ["sandbag"],
    difficulty: "intermediate",
    force: "static",
    mechanic: "compound",
    benefits: ["conditioning", "grip"],
    tags: ["strongman", "carries"],
  },
  {
    name: "Tire Flip",
    description: "Flipping large tire for power.",
    instructions: "Get under tire edge, drive with legs and hips, flip over.",
    category: "strength",
    muscleGroups: ["full body"],
    secondaryMuscles: [],
    equipment: ["tire"],
    difficulty: "advanced",
    force: "push",
    mechanic: "compound",
    benefits: ["power", "conditioning"],
    tags: ["strongman"],
  },
  {
    name: "Sledgehammer Swing",
    description: "Swinging sledgehammer onto tire.",
    instructions: "Swing sledgehammer overhead and strike tire.",
    category: "cardio",
    muscleGroups: ["core", "shoulders", "back"],
    secondaryMuscles: ["forearms"],
    equipment: ["sledgehammer", "tire"],
    difficulty: "intermediate",
    force: "dynamic",
    mechanic: "compound",
    benefits: ["rotational power", "conditioning"],
    tags: ["strongman", "conditioning"],
  },
  {
    name: "Rope Climb",
    description: "Climbing vertical rope.",
    instructions: "Use legs to grip rope, pull with arms, ascend to top.",
    category: "strength",
    muscleGroups: ["lats", "biceps", "grip"],
    secondaryMuscles: ["core", "legs"],
    equipment: ["climbing rope"],
    difficulty: "advanced",
    force: "pull",
    mechanic: "compound",
    benefits: ["pulling strength", "grip"],
    tags: ["crossfit", "skill"],
  },
  {
    name: "Legless Rope Climb",
    description: "Rope climb without using legs.",
    instructions: "Climb rope using only arms without leg assistance.",
    category: "strength",
    muscleGroups: ["lats", "biceps", "grip"],
    secondaryMuscles: ["core"],
    equipment: ["climbing rope"],
    difficulty: "advanced",
    force: "pull",
    mechanic: "compound",
    benefits: ["upper body strength"],
    tags: ["crossfit", "advanced"],
  },
];

// Helper to generate SQL INSERT statements
function generateExerciseInserts() {
  const values = EXERCISES.map((ex, i) => {
    const muscleGroups = JSON.stringify(ex.muscleGroups || []).replace(/'/g, "''");
    const secondaryMuscles = JSON.stringify(ex.secondaryMuscles || []).replace(/'/g, "''");
    const equipment = JSON.stringify(ex.equipment || []).replace(/'/g, "''");
    const benefits = JSON.stringify(ex.benefits || []).replace(/'/g, "''");
    const tags = JSON.stringify(ex.tags || []).replace(/'/g, "''");
    
    return `(
      gen_random_uuid(),
      '${ex.name.replace(/'/g, "''")}',
      '${(ex.description || '').replace(/'/g, "''")}',
      '${(ex.instructions || '').replace(/'/g, "''")}',
      '${ex.category}',
      '${muscleGroups}'::jsonb,
      '${secondaryMuscles}'::jsonb,
      '${equipment}'::jsonb,
      '${ex.difficulty}',
      '${ex.force}',
      '${ex.mechanic}',
      '${benefits}'::jsonb,
      '${tags}'::jsonb,
      true,
      false,
      'system',
      NOW(),
      NOW()
    )`;
  });
  
  return `INSERT INTO exercises (
    id, name, description, instructions, category, muscle_groups, secondary_muscles,
    equipment, difficulty, force, mechanic, benefits, tags, is_active, is_custom, source, created_at, updated_at
  ) VALUES ${values.join(',\n')};`;
}

console.log(`// Total exercises: ${EXERCISES.length}`);
console.log(generateExerciseInserts());
