/**
 * Seed Badge Definitions
 *
 * Run with: npx tsx scripts/seed-badges.ts
 *
 * This will upsert all badges — safe to re-run to update icons, rarity, and unlockMessage.
 */

import { db } from "../src/lib/db";
import { badgeDefinitions } from "../src/lib/db/schema";
import { sql } from "drizzle-orm";

interface BadgeDefinition {
  name: string;
  description: string;
  icon: string;
  category: string;
  tier: "bronze" | "silver" | "gold" | "platinum";
  rarity: "common" | "uncommon" | "rare" | "epic" | "legendary";
  unlockMessage: string;
  criteria: Record<string, unknown>;
  criteriaDescription: string;
  isAutomatic: boolean;
  displayOrder: number;
}

const BADGE_DEFINITIONS: BadgeDefinition[] = [
  // ============================================================================
  // STRENGTH BADGES — Bench Press (💪 = upper body push)
  // ============================================================================

  {
    name: "135 Bench Club",
    description: "Bench press 135 lbs (1 plate)",
    icon: "💪",
    category: "strength",
    tier: "bronze",
    rarity: "uncommon",
    unlockMessage: "One plate on each side — you're officially in the game!",
    criteria: { type: "pr_single", exercises: ["bench press"], singleValue: 135 },
    criteriaDescription: "Bench press 135 lbs for 1 rep",
    isAutomatic: true,
    displayOrder: 1,
  },
  {
    name: "225 Bench Club",
    description: "Bench press 225 lbs (2 plates)",
    icon: "💪",
    category: "strength",
    tier: "silver",
    rarity: "rare",
    unlockMessage: "Two plates! You just entered an elite club.",
    criteria: { type: "pr_single", exercises: ["bench press"], singleValue: 225 },
    criteriaDescription: "Bench press 225 lbs for 1 rep",
    isAutomatic: true,
    displayOrder: 2,
  },
  {
    name: "315 Bench Club",
    description: "Bench press 315 lbs (3 plates)",
    icon: "💪",
    category: "strength",
    tier: "gold",
    rarity: "epic",
    unlockMessage: "Three plates on bench? That's seriously impressive.",
    criteria: { type: "pr_single", exercises: ["bench press"], singleValue: 315 },
    criteriaDescription: "Bench press 315 lbs for 1 rep",
    isAutomatic: true,
    displayOrder: 3,
  },
  {
    name: "405 Bench Club",
    description: "Bench press 405 lbs (4 plates)",
    icon: "💪",
    category: "strength",
    tier: "platinum",
    rarity: "legendary",
    unlockMessage: "Four plates. You are a freak of nature. Respect.",
    criteria: { type: "pr_single", exercises: ["bench press"], singleValue: 405 },
    criteriaDescription: "Bench press 405 lbs for 1 rep",
    isAutomatic: true,
    displayOrder: 4,
  },

  // ============================================================================
  // STRENGTH BADGES — Squat (🦵 = legs)
  // ============================================================================

  {
    name: "225 Squat Club",
    description: "Squat 225 lbs (2 plates)",
    icon: "🦵",
    category: "strength",
    tier: "bronze",
    rarity: "uncommon",
    unlockMessage: "Two plates deep — your legs are getting serious!",
    criteria: { type: "pr_single", exercises: ["squat", "back squat"], singleValue: 225 },
    criteriaDescription: "Squat 225 lbs for 1 rep",
    isAutomatic: true,
    displayOrder: 10,
  },
  {
    name: "315 Squat Club",
    description: "Squat 315 lbs (3 plates)",
    icon: "🦵",
    category: "strength",
    tier: "silver",
    rarity: "rare",
    unlockMessage: "Three plates in the hole. Your legs don't skip leg day.",
    criteria: { type: "pr_single", exercises: ["squat", "back squat"], singleValue: 315 },
    criteriaDescription: "Squat 315 lbs for 1 rep",
    isAutomatic: true,
    displayOrder: 11,
  },
  {
    name: "405 Squat Club",
    description: "Squat 405 lbs (4 plates)",
    icon: "🦵",
    category: "strength",
    tier: "gold",
    rarity: "epic",
    unlockMessage: "Four plates ATG. That's powerlifter territory.",
    criteria: { type: "pr_single", exercises: ["squat", "back squat"], singleValue: 405 },
    criteriaDescription: "Squat 405 lbs for 1 rep",
    isAutomatic: true,
    displayOrder: 12,
  },
  {
    name: "495 Squat Club",
    description: "Squat 495 lbs (5 plates)",
    icon: "🦵",
    category: "strength",
    tier: "platinum",
    rarity: "legendary",
    unlockMessage: "Five plates. The bar is bending. You're built different.",
    criteria: { type: "pr_single", exercises: ["squat", "back squat"], singleValue: 495 },
    criteriaDescription: "Squat 495 lbs for 1 rep",
    isAutomatic: true,
    displayOrder: 13,
  },

  // ============================================================================
  // STRENGTH BADGES — Deadlift (💀 = dead-lift pun)
  // ============================================================================

  {
    name: "315 Deadlift Club",
    description: "Deadlift 315 lbs (3 plates)",
    icon: "💀",
    category: "strength",
    tier: "bronze",
    rarity: "uncommon",
    unlockMessage: "Three plates off the floor. The deadlift journey begins!",
    criteria: { type: "pr_single", exercises: ["deadlift"], singleValue: 315 },
    criteriaDescription: "Deadlift 315 lbs for 1 rep",
    isAutomatic: true,
    displayOrder: 20,
  },
  {
    name: "405 Deadlift Club",
    description: "Deadlift 405 lbs (4 plates)",
    icon: "💀",
    category: "strength",
    tier: "silver",
    rarity: "rare",
    unlockMessage: "Four plates. The earth trembles when you pull.",
    criteria: { type: "pr_single", exercises: ["deadlift"], singleValue: 405 },
    criteriaDescription: "Deadlift 405 lbs for 1 rep",
    isAutomatic: true,
    displayOrder: 21,
  },
  {
    name: "495 Deadlift Club",
    description: "Deadlift 495 lbs (5 plates)",
    icon: "💀",
    category: "strength",
    tier: "gold",
    rarity: "epic",
    unlockMessage: "Five plates. You're pulling serious weight off this planet.",
    criteria: { type: "pr_single", exercises: ["deadlift"], singleValue: 495 },
    criteriaDescription: "Deadlift 495 lbs for 1 rep",
    isAutomatic: true,
    displayOrder: 22,
  },
  {
    name: "585 Deadlift Club",
    description: "Deadlift 585 lbs (6 plates)",
    icon: "💀",
    category: "strength",
    tier: "platinum",
    rarity: "legendary",
    unlockMessage: "Six plates. You are genuinely superhuman.",
    criteria: { type: "pr_single", exercises: ["deadlift"], singleValue: 585 },
    criteriaDescription: "Deadlift 585 lbs for 1 rep",
    isAutomatic: true,
    displayOrder: 23,
  },

  // ============================================================================
  // STRENGTH BADGES — Combined Totals (🏆 = total achievement)
  // ============================================================================

  {
    name: "500lb Club",
    description: "Combined squat, bench, deadlift total of 500 lbs",
    icon: "🏆",
    category: "strength",
    tier: "bronze",
    rarity: "uncommon",
    unlockMessage: "Your big three total is climbing. Keep pushing all three!",
    criteria: { type: "pr_total", exercises: ["squat", "back squat", "bench press", "deadlift"], totalValue: 500 },
    criteriaDescription: "Squat + Bench + Deadlift total = 500 lbs",
    isAutomatic: true,
    displayOrder: 30,
  },
  {
    name: "1000lb Club",
    description: "Combined squat, bench, deadlift total of 1000 lbs",
    icon: "🏆",
    category: "strength",
    tier: "silver",
    rarity: "rare",
    unlockMessage: "Welcome to the 1000lb Club. That's a lifetime milestone.",
    criteria: { type: "pr_total", exercises: ["squat", "back squat", "bench press", "deadlift"], totalValue: 1000 },
    criteriaDescription: "Squat + Bench + Deadlift total = 1000 lbs",
    isAutomatic: true,
    displayOrder: 31,
  },
  {
    name: "1500lb Club",
    description: "Combined squat, bench, deadlift total of 1500 lbs",
    icon: "🏆",
    category: "strength",
    tier: "gold",
    rarity: "epic",
    unlockMessage: "1500 total. You're stronger than 99% of people alive.",
    criteria: { type: "pr_total", exercises: ["squat", "back squat", "bench press", "deadlift"], totalValue: 1500 },
    criteriaDescription: "Squat + Bench + Deadlift total = 1500 lbs",
    isAutomatic: true,
    displayOrder: 32,
  },
  {
    name: "2000lb Club",
    description: "Combined squat, bench, deadlift total of 2000 lbs",
    icon: "🏆",
    category: "strength",
    tier: "platinum",
    rarity: "legendary",
    unlockMessage: "A literal TON. You're among the strongest humans on earth.",
    criteria: { type: "pr_total", exercises: ["squat", "back squat", "bench press", "deadlift"], totalValue: 2000 },
    criteriaDescription: "Squat + Bench + Deadlift total = 2000 lbs",
    isAutomatic: true,
    displayOrder: 33,
  },

  // ============================================================================
  // SKILL BADGES — Gymnastics (🤸 = tumbling)
  // ============================================================================

  {
    name: "Back Tuck",
    description: "Achieved a standing back tuck",
    icon: "🤸",
    category: "skill",
    tier: "silver",
    rarity: "rare",
    unlockMessage: "You just flipped backwards in the air. That takes serious guts.",
    criteria: { type: "skill_achieved", skillName: "back_tuck", skillStatus: "achieved" },
    criteriaDescription: "Mark back tuck skill as achieved",
    isAutomatic: true,
    displayOrder: 100,
  },
  {
    name: "Back Handspring",
    description: "Achieved a standing back handspring",
    icon: "🤸",
    category: "skill",
    tier: "silver",
    rarity: "rare",
    unlockMessage: "Standing back handspring unlocked! Your power and courage are next level.",
    criteria: { type: "skill_achieved", skillName: "back_handspring", skillStatus: "achieved" },
    criteriaDescription: "Mark back handspring skill as achieved",
    isAutomatic: true,
    displayOrder: 101,
  },
  {
    name: "Back Layout",
    description: "Achieved a back layout",
    icon: "🤸",
    category: "skill",
    tier: "gold",
    rarity: "epic",
    unlockMessage: "Full layout! You've got elite body control and air awareness.",
    criteria: { type: "skill_achieved", skillName: "back_layout", skillStatus: "achieved" },
    criteriaDescription: "Mark back layout skill as achieved",
    isAutomatic: true,
    displayOrder: 102,
  },

  // ============================================================================
  // SKILL BADGES — Calisthenics
  // ============================================================================

  {
    name: "Handstand Hero",
    description: "Achieved a freestanding handstand",
    icon: "🙌",
    category: "skill",
    tier: "silver",
    rarity: "rare",
    unlockMessage: "Balancing upside down like it's nothing. Gravity who?",
    criteria: { type: "skill_achieved", skillName: "handstand", skillStatus: "achieved" },
    criteriaDescription: "Mark handstand skill as achieved",
    isAutomatic: true,
    displayOrder: 110,
  },
  {
    name: "Handstand Walker",
    description: "Achieved a handstand walk",
    icon: "🙌",
    category: "skill",
    tier: "gold",
    rarity: "epic",
    unlockMessage: "Walking on your hands? That's a whole different level of balance.",
    criteria: { type: "skill_achieved", skillName: "handstand_walk", skillStatus: "achieved" },
    criteriaDescription: "Mark handstand walk skill as achieved",
    isAutomatic: true,
    displayOrder: 111,
  },
  {
    name: "Muscle Up Master",
    description: "Achieved a muscle up",
    icon: "🔱",
    category: "skill",
    tier: "gold",
    rarity: "epic",
    unlockMessage: "The ultimate pull-to-push combo. You just defied the bar.",
    criteria: { type: "skill_achieved", skillName: "muscle_up", skillStatus: "achieved" },
    criteriaDescription: "Mark muscle up skill as achieved",
    isAutomatic: true,
    displayOrder: 120,
  },
  {
    name: "Strict Muscle Up",
    description: "Achieved a strict muscle up",
    icon: "🔱",
    category: "skill",
    tier: "platinum",
    rarity: "legendary",
    unlockMessage: "A strict muscle up. No kip, no momentum — pure strength. Legendary.",
    criteria: { type: "skill_achieved", skillName: "strict_muscle_up", skillStatus: "achieved" },
    criteriaDescription: "Mark strict muscle up skill as achieved",
    isAutomatic: true,
    displayOrder: 121,
  },
  {
    name: "Pistol Pro",
    description: "Achieved a pistol squat",
    icon: "🦵",
    category: "skill",
    tier: "silver",
    rarity: "rare",
    unlockMessage: "One leg, full depth. Your balance and strength are dialed.",
    criteria: { type: "skill_achieved", skillName: "pistol_squat", skillStatus: "achieved" },
    criteriaDescription: "Mark pistol squat skill as achieved",
    isAutomatic: true,
    displayOrder: 130,
  },

  // ============================================================================
  // TRACK BADGES — Mile (🏃 = running)
  // ============================================================================

  {
    name: "Sub-8 Minute Mile",
    description: "Run a mile in under 8 minutes",
    icon: "🏃",
    category: "track",
    tier: "bronze",
    rarity: "common",
    unlockMessage: "Sub-8! You're faster than most people who hit the track.",
    criteria: { type: "track_time", trackDistance: 1609, trackTime: 480 },
    criteriaDescription: "Complete a mile run in under 8 minutes",
    isAutomatic: true,
    displayOrder: 200,
  },
  {
    name: "Sub-7 Minute Mile",
    description: "Run a mile in under 7 minutes",
    icon: "🏃",
    category: "track",
    tier: "silver",
    rarity: "uncommon",
    unlockMessage: "Sub-7 mile! Your cardio engine is running hot.",
    criteria: { type: "track_time", trackDistance: 1609, trackTime: 420 },
    criteriaDescription: "Complete a mile run in under 7 minutes",
    isAutomatic: true,
    displayOrder: 201,
  },
  {
    name: "Sub-6 Minute Mile",
    description: "Run a mile in under 6 minutes",
    icon: "🏃",
    category: "track",
    tier: "gold",
    rarity: "rare",
    unlockMessage: "Sub-6. You're outrunning most competitive runners. Speed demon!",
    criteria: { type: "track_time", trackDistance: 1609, trackTime: 360 },
    criteriaDescription: "Complete a mile run in under 6 minutes",
    isAutomatic: true,
    displayOrder: 202,
  },
  {
    name: "Sub-5 Minute Mile",
    description: "Run a mile in under 5 minutes",
    icon: "🏃",
    category: "track",
    tier: "platinum",
    rarity: "legendary",
    unlockMessage: "Sub-5 minute mile. That's elite D1 / professional speed. Incredible.",
    criteria: { type: "track_time", trackDistance: 1609, trackTime: 300 },
    criteriaDescription: "Complete a mile run in under 5 minutes",
    isAutomatic: true,
    displayOrder: 203,
  },

  // ============================================================================
  // CONSISTENCY BADGES — Streaks (🔥 = streak fire)
  // ============================================================================

  {
    name: "Week Warrior",
    description: "7 day workout streak",
    icon: "🔥",
    category: "consistency",
    tier: "bronze",
    rarity: "common",
    unlockMessage: "7 days straight! Consistency is the real superpower.",
    criteria: { type: "streak", streakDays: 7 },
    criteriaDescription: "Work out for 7 consecutive days",
    isAutomatic: true,
    displayOrder: 300,
  },
  {
    name: "Month Crusher",
    description: "30 day workout streak",
    icon: "🔥",
    category: "consistency",
    tier: "silver",
    rarity: "uncommon",
    unlockMessage: "30 days! You've turned working out into a habit.",
    criteria: { type: "streak", streakDays: 30 },
    criteriaDescription: "Work out for 30 consecutive days",
    isAutomatic: true,
    displayOrder: 301,
  },
  {
    name: "Century Streak",
    description: "100 day workout streak",
    icon: "🔥",
    category: "consistency",
    tier: "gold",
    rarity: "epic",
    unlockMessage: "100 days without missing. You're a machine.",
    criteria: { type: "streak", streakDays: 100 },
    criteriaDescription: "Work out for 100 consecutive days",
    isAutomatic: true,
    displayOrder: 302,
  },
  {
    name: "Year Round",
    description: "365 day workout streak",
    icon: "🔥",
    category: "consistency",
    tier: "platinum",
    rarity: "legendary",
    unlockMessage: "365 straight days. A full year of never missing. Absolute legend.",
    criteria: { type: "streak", streakDays: 365 },
    criteriaDescription: "Work out for 365 consecutive days",
    isAutomatic: true,
    displayOrder: 303,
  },

  // ============================================================================
  // CONSISTENCY BADGES — Workout Count (✅ = completed)
  // ============================================================================

  {
    name: "First 10",
    description: "Complete 10 workouts",
    icon: "✅",
    category: "consistency",
    tier: "bronze",
    rarity: "common",
    unlockMessage: "10 workouts logged! You're building momentum.",
    criteria: { type: "workout_count", workoutCount: 10 },
    criteriaDescription: "Complete 10 total workouts",
    isAutomatic: true,
    displayOrder: 310,
  },
  {
    name: "Fifty Strong",
    description: "Complete 50 workouts",
    icon: "✅",
    category: "consistency",
    tier: "silver",
    rarity: "uncommon",
    unlockMessage: "50 workouts! Halfway to the century club.",
    criteria: { type: "workout_count", workoutCount: 50 },
    criteriaDescription: "Complete 50 total workouts",
    isAutomatic: true,
    displayOrder: 311,
  },
  {
    name: "Century Club",
    description: "Complete 100 workouts",
    icon: "✅",
    category: "consistency",
    tier: "gold",
    rarity: "rare",
    unlockMessage: "100 workouts. Triple digits. That's dedication personified.",
    criteria: { type: "workout_count", workoutCount: 100 },
    criteriaDescription: "Complete 100 total workouts",
    isAutomatic: true,
    displayOrder: 312,
  },
  {
    name: "500 Strong",
    description: "Complete 500 workouts",
    icon: "✅",
    category: "consistency",
    tier: "platinum",
    rarity: "epic",
    unlockMessage: "500 workouts. You've put in more work than most people dream of.",
    criteria: { type: "workout_count", workoutCount: 500 },
    criteriaDescription: "Complete 500 total workouts",
    isAutomatic: true,
    displayOrder: 313,
  },

  // ============================================================================
  // SOCIAL BADGES
  // ============================================================================

  {
    name: "Circle Creator",
    description: "Create your first circle",
    icon: "👥",
    category: "social",
    tier: "bronze",
    rarity: "common",
    unlockMessage: "Your first circle is live! Time to rally your crew.",
    criteria: { type: "circles_created", circleCount: 1 },
    criteriaDescription: "Create 1 circle",
    isAutomatic: true,
    displayOrder: 400,
  },
  {
    name: "Community Builder",
    description: "Create 5 circles",
    icon: "👥",
    category: "social",
    tier: "silver",
    rarity: "uncommon",
    unlockMessage: "5 circles! You're building a fitness community.",
    criteria: { type: "circles_created", circleCount: 5 },
    criteriaDescription: "Create 5 circles",
    isAutomatic: true,
    displayOrder: 401,
  },
  {
    name: "Rising Star",
    description: "Get 10 followers",
    icon: "⭐",
    category: "social",
    tier: "bronze",
    rarity: "uncommon",
    unlockMessage: "10 people are watching your journey. Keep inspiring!",
    criteria: { type: "followers", followerCount: 10 },
    criteriaDescription: "Have 10 followers",
    isAutomatic: true,
    displayOrder: 410,
  },
  {
    name: "Popular",
    description: "Get 50 followers",
    icon: "⭐",
    category: "social",
    tier: "silver",
    rarity: "rare",
    unlockMessage: "50 followers! Your fitness journey is motivating people.",
    criteria: { type: "followers", followerCount: 50 },
    criteriaDescription: "Have 50 followers",
    isAutomatic: true,
    displayOrder: 411,
  },
  {
    name: "Influencer",
    description: "Get 100 followers",
    icon: "⭐",
    category: "social",
    tier: "gold",
    rarity: "epic",
    unlockMessage: "100 followers. You're a fitness influencer now!",
    criteria: { type: "followers", followerCount: 100 },
    criteriaDescription: "Have 100 followers",
    isAutomatic: true,
    displayOrder: 412,
  },

  // ============================================================================
  // SPORT BADGES — All sports use their sport emoji
  // ============================================================================

  {
    name: "Baseball Player",
    description: "Baseball athlete",
    icon: "⚾",
    category: "sport",
    tier: "bronze",
    rarity: "common",
    unlockMessage: "Play ball! Your baseball identity is locked in.",
    criteria: { type: "sport", sport: "baseball" },
    criteriaDescription: "Add baseball to your sports",
    isAutomatic: true,
    displayOrder: 500,
  },
  {
    name: "Basketball Player",
    description: "Basketball athlete",
    icon: "🏀",
    category: "sport",
    tier: "bronze",
    rarity: "common",
    unlockMessage: "Hoops life! Ball is life.",
    criteria: { type: "sport", sport: "basketball" },
    criteriaDescription: "Add basketball to your sports",
    isAutomatic: true,
    displayOrder: 501,
  },
  {
    name: "Football Player",
    description: "Football athlete",
    icon: "🏈",
    category: "sport",
    tier: "bronze",
    rarity: "common",
    unlockMessage: "Gridiron warrior! Friday night lights energy.",
    criteria: { type: "sport", sport: "football" },
    criteriaDescription: "Add football to your sports",
    isAutomatic: true,
    displayOrder: 502,
  },
  {
    name: "Soccer Player",
    description: "Soccer athlete",
    icon: "⚽",
    category: "sport",
    tier: "bronze",
    rarity: "common",
    unlockMessage: "The beautiful game! Your pitch, your rules.",
    criteria: { type: "sport", sport: "soccer" },
    criteriaDescription: "Add soccer to your sports",
    isAutomatic: true,
    displayOrder: 503,
  },
  {
    name: "Hockey Player",
    description: "Hockey athlete",
    icon: "🏒",
    category: "sport",
    tier: "bronze",
    rarity: "common",
    unlockMessage: "Ice or field, you bring the intensity!",
    criteria: { type: "sport", sport: "hockey" },
    criteriaDescription: "Add hockey to your sports",
    isAutomatic: true,
    displayOrder: 504,
  },
  {
    name: "Tennis Player",
    description: "Tennis athlete",
    icon: "🎾",
    category: "sport",
    tier: "bronze",
    rarity: "common",
    unlockMessage: "Game, set, match! Court warrior unlocked.",
    criteria: { type: "sport", sport: "tennis" },
    criteriaDescription: "Add tennis to your sports",
    isAutomatic: true,
    displayOrder: 505,
  },
  {
    name: "Golfer",
    description: "Golf enthusiast",
    icon: "⛳",
    category: "sport",
    tier: "bronze",
    rarity: "common",
    unlockMessage: "Fore! Time to work on that swing.",
    criteria: { type: "sport", sport: "golf" },
    criteriaDescription: "Add golf to your sports",
    isAutomatic: true,
    displayOrder: 506,
  },
  {
    name: "Swimmer",
    description: "Swimming athlete",
    icon: "🏊",
    category: "sport",
    tier: "bronze",
    rarity: "common",
    unlockMessage: "Dive in! The pool is your playground.",
    criteria: { type: "sport", sport: "swimming" },
    criteriaDescription: "Add swimming to your sports",
    isAutomatic: true,
    displayOrder: 507,
  },
  {
    name: "CrossFit Athlete",
    description: "CrossFit practitioner",
    icon: "⚡",
    category: "sport",
    tier: "bronze",
    rarity: "common",
    unlockMessage: "WOD life! Ready for anything they throw at you.",
    criteria: { type: "sport", sport: "crossfit" },
    criteriaDescription: "Add CrossFit to your sports",
    isAutomatic: true,
    displayOrder: 508,
  },
  {
    name: "Powerlifter",
    description: "Powerlifting athlete",
    icon: "🏋️",
    category: "sport",
    tier: "bronze",
    rarity: "common",
    unlockMessage: "Squat, bench, dead. The big three are your world.",
    criteria: { type: "sport", sport: "powerlifting" },
    criteriaDescription: "Add powerlifting to your sports",
    isAutomatic: true,
    displayOrder: 509,
  },
  {
    name: "Runner",
    description: "Running enthusiast",
    icon: "🏃",
    category: "sport",
    tier: "bronze",
    rarity: "common",
    unlockMessage: "Lace up! Every mile makes you stronger.",
    criteria: { type: "sport", sport: "running" },
    criteriaDescription: "Add running to your sports",
    isAutomatic: true,
    displayOrder: 510,
  },
  {
    name: "Cyclist",
    description: "Cycling athlete",
    icon: "🚴",
    category: "sport",
    tier: "bronze",
    rarity: "common",
    unlockMessage: "Pedal power! Two wheels, endless roads.",
    criteria: { type: "sport", sport: "cycling" },
    criteriaDescription: "Add cycling to your sports",
    isAutomatic: true,
    displayOrder: 511,
  },
  {
    name: "Triathlete",
    description: "Triathlon competitor",
    icon: "🏊",
    category: "sport",
    tier: "silver",
    rarity: "uncommon",
    unlockMessage: "Swim, bike, run. You don't pick one — you do all three.",
    criteria: { type: "sport", sport: "triathlon" },
    criteriaDescription: "Add triathlon to your sports",
    isAutomatic: true,
    displayOrder: 512,
  },
  {
    name: "Martial Artist",
    description: "Martial arts practitioner",
    icon: "🥋",
    category: "sport",
    tier: "bronze",
    rarity: "common",
    unlockMessage: "Discipline, respect, power. The way of the warrior.",
    criteria: { type: "sport", sport: "martial_arts" },
    criteriaDescription: "Add martial arts to your sports",
    isAutomatic: true,
    displayOrder: 513,
  },
  {
    name: "Yogi",
    description: "Yoga practitioner",
    icon: "🧘",
    category: "sport",
    tier: "bronze",
    rarity: "common",
    unlockMessage: "Namaste! Flexibility and mindfulness unlocked.",
    criteria: { type: "sport", sport: "yoga" },
    criteriaDescription: "Add yoga to your sports",
    isAutomatic: true,
    displayOrder: 514,
  },
  {
    name: "Pickleball Player",
    description: "Pickleball enthusiast",
    icon: "🏓",
    category: "sport",
    tier: "bronze",
    rarity: "common",
    unlockMessage: "Dink! The fastest growing sport and you're in it.",
    criteria: { type: "sport", sport: "pickleball" },
    criteriaDescription: "Add pickleball to your sports",
    isAutomatic: true,
    displayOrder: 515,
  },

  // ============================================================================
  // CROSSFIT BENCHMARK BADGES
  // ============================================================================

  {
    name: "Fran Finisher",
    description: "Complete the Fran WOD",
    icon: "⏱️",
    category: "challenge",
    tier: "bronze",
    rarity: "uncommon",
    unlockMessage: "Fran complete! 21-15-9 and you survived.",
    criteria: { type: "challenge_complete", challengeId: "fran" },
    criteriaDescription: "Complete Fran (21-15-9 Thrusters & Pull-ups)",
    isAutomatic: true,
    displayOrder: 600,
  },
  {
    name: "Fran Under 5",
    description: "Complete Fran in under 5 minutes",
    icon: "⚡",
    category: "challenge",
    tier: "silver",
    rarity: "rare",
    unlockMessage: "Sub-5 Fran! That's competitive CrossFit pace.",
    criteria: { type: "challenge_complete", challengeId: "fran_sub5" },
    criteriaDescription: "Finish Fran in under 5 minutes",
    isAutomatic: true,
    displayOrder: 601,
  },
  {
    name: "Fran Under 3",
    description: "Complete Fran in under 3 minutes",
    icon: "💎",
    category: "challenge",
    tier: "platinum",
    rarity: "legendary",
    unlockMessage: "Sub-3 Fran. Games-level athlete. Absolutely elite.",
    criteria: { type: "challenge_complete", challengeId: "fran_sub3" },
    criteriaDescription: "Finish Fran in under 3 minutes",
    isAutomatic: true,
    displayOrder: 602,
  },
  {
    name: "Grace Finisher",
    description: "Complete the Grace WOD (30 C&J)",
    icon: "⏱️",
    category: "challenge",
    tier: "bronze",
    rarity: "uncommon",
    unlockMessage: "30 clean & jerks for time? You just Grace'd it.",
    criteria: { type: "challenge_complete", challengeId: "grace" },
    criteriaDescription: "Complete Grace (30 Clean & Jerks)",
    isAutomatic: true,
    displayOrder: 610,
  },
  {
    name: "Sub-3 Grace",
    description: "Complete Grace in under 3 minutes",
    icon: "⚡",
    category: "challenge",
    tier: "gold",
    rarity: "epic",
    unlockMessage: "Sub-3 Grace. 30 reps in under 3 minutes is insane speed.",
    criteria: { type: "challenge_complete", challengeId: "grace_sub3" },
    criteriaDescription: "Finish Grace in under 3 minutes",
    isAutomatic: true,
    displayOrder: 611,
  },
  {
    name: "Murph Finisher",
    description: "Complete the Murph Hero WOD",
    icon: "🎖️",
    category: "challenge",
    tier: "silver",
    rarity: "rare",
    unlockMessage: "Murph complete. In honor of Lt. Michael Murphy. Respect.",
    criteria: { type: "challenge_complete", challengeId: "murph" },
    criteriaDescription: "Complete Murph (1 mi run, 100 pull-ups, 200 push-ups, 300 squats, 1 mi run)",
    isAutomatic: true,
    displayOrder: 620,
  },
  {
    name: "Murph Under 60",
    description: "Complete Murph in under 60 minutes",
    icon: "🎖️",
    category: "challenge",
    tier: "gold",
    rarity: "epic",
    unlockMessage: "Sub-60 Murph! That takes serious conditioning and heart.",
    criteria: { type: "challenge_complete", challengeId: "murph_sub60" },
    criteriaDescription: "Finish Murph in under 60 minutes",
    isAutomatic: true,
    displayOrder: 621,
  },
  {
    name: "Murph Under 45",
    description: "Complete Murph in under 45 minutes",
    icon: "💎",
    category: "challenge",
    tier: "platinum",
    rarity: "legendary",
    unlockMessage: "Sub-45 Murph. You are an absolute warrior.",
    criteria: { type: "challenge_complete", challengeId: "murph_sub45" },
    criteriaDescription: "Finish Murph in under 45 minutes",
    isAutomatic: true,
    displayOrder: 622,
  },
  {
    name: "Cindy Champion",
    description: "Complete 20+ rounds of Cindy",
    icon: "🔄",
    category: "challenge",
    tier: "silver",
    rarity: "rare",
    unlockMessage: "20+ rounds of Cindy! Your engine is relentless.",
    criteria: { type: "challenge_complete", challengeId: "cindy_20" },
    criteriaDescription: "20+ rounds of Cindy in 20 minutes",
    isAutomatic: true,
    displayOrder: 630,
  },
  {
    name: "Helen Hero",
    description: "Complete the Helen WOD",
    icon: "🏃",
    category: "challenge",
    tier: "bronze",
    rarity: "uncommon",
    unlockMessage: "Helen complete! Run, swing, pull — the perfect combo.",
    criteria: { type: "challenge_complete", challengeId: "helen" },
    criteriaDescription: "Complete 3 rounds of Helen",
    isAutomatic: true,
    displayOrder: 640,
  },
  {
    name: "Isabel Finisher",
    description: "Complete Isabel (30 Snatches)",
    icon: "⏱️",
    category: "challenge",
    tier: "silver",
    rarity: "rare",
    unlockMessage: "30 snatches for time. Fast, powerful, and technical.",
    criteria: { type: "challenge_complete", challengeId: "isabel" },
    criteriaDescription: "Complete Isabel (30 Snatches for time)",
    isAutomatic: true,
    displayOrder: 650,
  },
  {
    name: "DT Destroyer",
    description: "Complete the DT Hero WOD",
    icon: "🎖️",
    category: "challenge",
    tier: "silver",
    rarity: "rare",
    unlockMessage: "DT complete. A hero WOD that tests every ounce of grit.",
    criteria: { type: "challenge_complete", challengeId: "dt" },
    criteriaDescription: "Complete 5 rounds of DT",
    isAutomatic: true,
    displayOrder: 660,
  },

  // ============================================================================
  // BODYWEIGHT / CALISTHENICS REP BADGES
  // ============================================================================

  {
    name: "Pull-Up Pro",
    description: "Complete 20 strict pull-ups unbroken",
    icon: "🧗",
    category: "skill",
    tier: "silver",
    rarity: "rare",
    unlockMessage: "20 strict pull-ups! Your back is a weapon.",
    criteria: { type: "pr_single", exercises: ["pull up", "pull-up"], singleValue: 20 },
    criteriaDescription: "20 strict pull-ups in a row",
    isAutomatic: true,
    displayOrder: 700,
  },
  {
    name: "Push-Up Master",
    description: "Complete 50 push-ups unbroken",
    icon: "💪",
    category: "skill",
    tier: "silver",
    rarity: "uncommon",
    unlockMessage: "50 push-ups nonstop! Chest and triceps of steel.",
    criteria: { type: "pr_single", exercises: ["push up", "push-up"], singleValue: 50 },
    criteriaDescription: "50 push-ups in a row",
    isAutomatic: true,
    displayOrder: 710,
  },
  {
    name: "Century Push-Ups",
    description: "Complete 100 push-ups unbroken",
    icon: "💪",
    category: "skill",
    tier: "gold",
    rarity: "epic",
    unlockMessage: "100 push-ups without stopping. That's muscular endurance royalty.",
    criteria: { type: "pr_single", exercises: ["push up", "push-up"], singleValue: 100 },
    criteriaDescription: "100 push-ups in a row",
    isAutomatic: true,
    displayOrder: 711,
  },
  {
    name: "Dip Master",
    description: "Complete 30 dips unbroken",
    icon: "⬇️",
    category: "skill",
    tier: "silver",
    rarity: "rare",
    unlockMessage: "30 dips! Your triceps and chest are bulletproof.",
    criteria: { type: "pr_single", exercises: ["dip", "dips"], singleValue: 30 },
    criteriaDescription: "30 dips in a row",
    isAutomatic: true,
    displayOrder: 720,
  },
  {
    name: "L-Sit Legend",
    description: "Hold an L-sit for 30 seconds",
    icon: "🧘",
    category: "skill",
    tier: "silver",
    rarity: "rare",
    unlockMessage: "30 second L-sit! Core strength and hip flexor power unlocked.",
    criteria: { type: "skill_achieved", skillName: "l_sit", skillStatus: "achieved" },
    criteriaDescription: "30 second L-sit hold",
    isAutomatic: true,
    displayOrder: 730,
  },
  {
    name: "Human Flag",
    description: "Achieve a human flag",
    icon: "🚩",
    category: "skill",
    tier: "platinum",
    rarity: "legendary",
    unlockMessage: "The human flag. You're literally defying gravity sideways.",
    criteria: { type: "skill_achieved", skillName: "human_flag", skillStatus: "achieved" },
    criteriaDescription: "Hold a full human flag",
    isAutomatic: true,
    displayOrder: 740,
  },
  {
    name: "Planche Pioneer",
    description: "Achieve a planche",
    icon: "🦸",
    category: "skill",
    tier: "platinum",
    rarity: "legendary",
    unlockMessage: "Full planche. You've mastered one of the hardest bodyweight skills alive.",
    criteria: { type: "skill_achieved", skillName: "planche", skillStatus: "achieved" },
    criteriaDescription: "Hold a full planche",
    isAutomatic: true,
    displayOrder: 750,
  },
  {
    name: "Front Lever",
    description: "Achieve a front lever",
    icon: "📐",
    category: "skill",
    tier: "gold",
    rarity: "epic",
    unlockMessage: "Front lever locked! Insane lat and core strength.",
    criteria: { type: "skill_achieved", skillName: "front_lever", skillStatus: "achieved" },
    criteriaDescription: "Hold a full front lever",
    isAutomatic: true,
    displayOrder: 760,
  },

  // ============================================================================
  // BODYWEIGHT RATIO BADGES (⚖️ = ratio/balance)
  // ============================================================================

  {
    name: "Bodyweight Bench",
    description: "Bench press your bodyweight",
    icon: "⚖️",
    category: "strength",
    tier: "bronze",
    rarity: "uncommon",
    unlockMessage: "You can bench your own bodyweight! Solid foundation.",
    criteria: { type: "pr_bodyweight_ratio", exercises: ["bench press"], bodyweightRatio: 1.0 },
    criteriaDescription: "Bench 1x your bodyweight",
    isAutomatic: true,
    displayOrder: 800,
  },
  {
    name: "1.5x Bodyweight Bench",
    description: "Bench press 1.5x bodyweight",
    icon: "⚖️",
    category: "strength",
    tier: "silver",
    rarity: "rare",
    unlockMessage: "1.5x bodyweight bench! That's truly strong for any weight class.",
    criteria: { type: "pr_bodyweight_ratio", exercises: ["bench press"], bodyweightRatio: 1.5 },
    criteriaDescription: "Bench 1.5x your bodyweight",
    isAutomatic: true,
    displayOrder: 801,
  },
  {
    name: "2x Bodyweight Squat",
    description: "Squat 2x your bodyweight",
    icon: "⚖️",
    category: "strength",
    tier: "gold",
    rarity: "epic",
    unlockMessage: "Double bodyweight squat! You're squatting like an elite lifter.",
    criteria: { type: "pr_bodyweight_ratio", exercises: ["squat", "back squat"], bodyweightRatio: 2.0 },
    criteriaDescription: "Squat 2x your bodyweight",
    isAutomatic: true,
    displayOrder: 810,
  },
  {
    name: "2.5x Bodyweight Deadlift",
    description: "Deadlift 2.5x your bodyweight",
    icon: "⚖️",
    category: "strength",
    tier: "gold",
    rarity: "epic",
    unlockMessage: "2.5x bodyweight deadlift. That's world-class relative strength.",
    criteria: { type: "pr_bodyweight_ratio", exercises: ["deadlift"], bodyweightRatio: 2.5 },
    criteriaDescription: "Deadlift 2.5x your bodyweight",
    isAutomatic: true,
    displayOrder: 820,
  },
  {
    name: "3x Bodyweight Deadlift",
    description: "Deadlift 3x your bodyweight",
    icon: "⚖️",
    category: "strength",
    tier: "platinum",
    rarity: "legendary",
    unlockMessage: "3x bodyweight deadlift. You belong on a competition platform.",
    criteria: { type: "pr_bodyweight_ratio", exercises: ["deadlift"], bodyweightRatio: 3.0 },
    criteriaDescription: "Deadlift 3x your bodyweight",
    isAutomatic: true,
    displayOrder: 821,
  },

  // ============================================================================
  // 400m / SPRINT BADGES
  // ============================================================================

  {
    name: "Sub-60 400m",
    description: "Run 400m in under 60 seconds",
    icon: "🏃",
    category: "track",
    tier: "silver",
    rarity: "rare",
    unlockMessage: "Sub-60 quarter mile! That takes real speed endurance.",
    criteria: { type: "track_time", trackDistance: 400, trackTime: 60 },
    criteriaDescription: "Complete 400m in under 60 seconds",
    isAutomatic: true,
    displayOrder: 900,
  },
  {
    name: "Sub-55 400m",
    description: "Run 400m in under 55 seconds",
    icon: "🏃",
    category: "track",
    tier: "gold",
    rarity: "epic",
    unlockMessage: "Sub-55! You're running at a competitive track athlete pace.",
    criteria: { type: "track_time", trackDistance: 400, trackTime: 55 },
    criteriaDescription: "Complete 400m in under 55 seconds",
    isAutomatic: true,
    displayOrder: 901,
  },
  {
    name: "Sub-50 400m",
    description: "Run 400m in under 50 seconds",
    icon: "🏃",
    category: "track",
    tier: "platinum",
    rarity: "legendary",
    unlockMessage: "Sub-50 400m! That's collegiate / professional sprint speed.",
    criteria: { type: "track_time", trackDistance: 400, trackTime: 50 },
    criteriaDescription: "Complete 400m in under 50 seconds",
    isAutomatic: true,
    displayOrder: 902,
  },
  {
    name: "Sub-12 100m",
    description: "Run 100m in under 12 seconds",
    icon: "💨",
    category: "track",
    tier: "silver",
    rarity: "rare",
    unlockMessage: "Sub-12! You've got genuine speed in those legs.",
    criteria: { type: "track_time", trackDistance: 100, trackTime: 12 },
    criteriaDescription: "Complete 100m sprint in under 12 seconds",
    isAutomatic: true,
    displayOrder: 910,
  },
  {
    name: "Sub-11 100m",
    description: "Run 100m in under 11 seconds",
    icon: "💨",
    category: "track",
    tier: "gold",
    rarity: "epic",
    unlockMessage: "Sub-11 hundred! You're in serious sprinter territory.",
    criteria: { type: "track_time", trackDistance: 100, trackTime: 11 },
    criteriaDescription: "Complete 100m sprint in under 11 seconds",
    isAutomatic: true,
    displayOrder: 911,
  },

  // ============================================================================
  // PROGRAM COMPLETION BADGES (🎓 = graduation)
  // ============================================================================

  {
    name: "Program Graduate",
    description: "Complete your first training program",
    icon: "🎓",
    category: "program",
    tier: "bronze",
    rarity: "common",
    unlockMessage: "First program complete! Structured training pays off.",
    criteria: { type: "program_complete" },
    criteriaDescription: "Complete any training program",
    isAutomatic: true,
    displayOrder: 1000,
  },
  {
    name: "Multi-Program Master",
    description: "Complete 3 different training programs",
    icon: "🎓",
    category: "program",
    tier: "silver",
    rarity: "uncommon",
    unlockMessage: "3 programs finished! You're building a diverse training base.",
    criteria: { type: "program_complete", programId: "3_programs" },
    criteriaDescription: "Complete 3 different programs",
    isAutomatic: true,
    displayOrder: 1001,
  },
  {
    name: "Program Pro",
    description: "Complete 10 training programs",
    icon: "🎓",
    category: "program",
    tier: "gold",
    rarity: "rare",
    unlockMessage: "10 programs! You're a training methodology expert at this point.",
    criteria: { type: "program_complete", programId: "10_programs" },
    criteriaDescription: "Complete 10 different programs",
    isAutomatic: true,
    displayOrder: 1002,
  },

  // ============================================================================
  // OLYMPIC LIFTING BADGES (🏋️ = overhead lifting, correct for oly lifts)
  // ============================================================================

  {
    name: "Clean & Jerk 135",
    description: "Clean & Jerk 135 lbs",
    icon: "🏋️",
    category: "strength",
    tier: "bronze",
    rarity: "uncommon",
    unlockMessage: "135 C&J! You've got the technique and power to move weight overhead.",
    criteria: { type: "pr_single", exercises: ["clean and jerk", "clean & jerk"], singleValue: 135 },
    criteriaDescription: "Clean & Jerk 135 lbs",
    isAutomatic: true,
    displayOrder: 1100,
  },
  {
    name: "Clean & Jerk 185",
    description: "Clean & Jerk 185 lbs",
    icon: "🏋️",
    category: "strength",
    tier: "silver",
    rarity: "rare",
    unlockMessage: "185 C&J. That's a serious amount of weight going overhead.",
    criteria: { type: "pr_single", exercises: ["clean and jerk", "clean & jerk"], singleValue: 185 },
    criteriaDescription: "Clean & Jerk 185 lbs",
    isAutomatic: true,
    displayOrder: 1101,
  },
  {
    name: "Clean & Jerk 225",
    description: "Clean & Jerk 225 lbs",
    icon: "🏋️",
    category: "strength",
    tier: "gold",
    rarity: "epic",
    unlockMessage: "225 C&J! Two plates overhead is an impressive feat of athletic power.",
    criteria: { type: "pr_single", exercises: ["clean and jerk", "clean & jerk"], singleValue: 225 },
    criteriaDescription: "Clean & Jerk 225 lbs",
    isAutomatic: true,
    displayOrder: 1102,
  },
  {
    name: "Snatch 95",
    description: "Snatch 95 lbs",
    icon: "🏋️",
    category: "strength",
    tier: "bronze",
    rarity: "uncommon",
    unlockMessage: "95 lb snatch! The most technical lift in the gym, and you're doing it.",
    criteria: { type: "pr_single", exercises: ["snatch"], singleValue: 95 },
    criteriaDescription: "Snatch 95 lbs",
    isAutomatic: true,
    displayOrder: 1110,
  },
  {
    name: "Snatch 135",
    description: "Snatch 135 lbs",
    icon: "🏋️",
    category: "strength",
    tier: "silver",
    rarity: "rare",
    unlockMessage: "135 snatch! One plate overhead from the floor in one motion. Athletic.",
    criteria: { type: "pr_single", exercises: ["snatch"], singleValue: 135 },
    criteriaDescription: "Snatch 135 lbs",
    isAutomatic: true,
    displayOrder: 1111,
  },
  {
    name: "Snatch 185",
    description: "Snatch 185 lbs",
    icon: "🏋️",
    category: "strength",
    tier: "gold",
    rarity: "epic",
    unlockMessage: "185 snatch. That's competitive weightlifter level. Raw power and precision.",
    criteria: { type: "pr_single", exercises: ["snatch"], singleValue: 185 },
    criteriaDescription: "Snatch 185 lbs",
    isAutomatic: true,
    displayOrder: 1112,
  },

  // ============================================================================
  // MILESTONE BADGES
  // ============================================================================

  {
    name: "Welcome to the Team",
    description: "Complete your onboarding and join the community",
    icon: "🎉",
    category: "milestone",
    tier: "bronze",
    rarity: "common",
    unlockMessage: "You're officially part of the Repcir community! Let's get to work.",
    criteria: { type: "onboarding_complete" },
    criteriaDescription: "Complete the onboarding process",
    isAutomatic: true,
    displayOrder: 1200,
  },
  {
    name: "Profile Starter",
    description: "Fill out 50% of your profile",
    icon: "📋",
    category: "milestone",
    tier: "bronze",
    rarity: "common",
    unlockMessage: "Profile is halfway there! More data means better AI workouts.",
    criteria: { type: "profile_complete", profilePercent: 50 },
    criteriaDescription: "Complete 50% of your profile",
    isAutomatic: true,
    displayOrder: 1201,
  },
  {
    name: "Profile Pro",
    description: "Fill out 100% of your profile",
    icon: "⭐",
    category: "milestone",
    tier: "silver",
    rarity: "uncommon",
    unlockMessage: "100% profile complete! AI now has maximum context to personalize your training.",
    criteria: { type: "profile_complete", profilePercent: 100 },
    criteriaDescription: "Complete 100% of your profile",
    isAutomatic: true,
    displayOrder: 1202,
  },
  {
    name: "Goal Setter",
    description: "Set your first fitness goal",
    icon: "🎯",
    category: "milestone",
    tier: "bronze",
    rarity: "common",
    unlockMessage: "Goals set! Now you've got something to chase.",
    criteria: { type: "first_login" },
    criteriaDescription: "Set at least one fitness goal during onboarding",
    isAutomatic: true,
    displayOrder: 1203,
  },
  {
    name: "PR Pioneer",
    description: "Log your first personal record",
    icon: "📈",
    category: "milestone",
    tier: "bronze",
    rarity: "common",
    unlockMessage: "First PR logged! Every journey starts with tracking where you are.",
    criteria: { type: "pr_single", exercises: [], singleValue: 1 },
    criteriaDescription: "Add any personal record to track your progress",
    isAutomatic: true,
    displayOrder: 1204,
  },
];

async function seedBadges() {
  console.log("Seeding badge definitions...\n");

  try {
    let created = 0;
    let updated = 0;

    for (const badge of BADGE_DEFINITIONS) {
      try {
        const result = await db.insert(badgeDefinitions).values({
          name: badge.name,
          description: badge.description,
          icon: badge.icon,
          category: badge.category,
          tier: badge.tier,
          rarity: badge.rarity,
          unlockMessage: badge.unlockMessage,
          criteria: badge.criteria as any,
          criteriaDescription: badge.criteriaDescription,
          isAutomatic: badge.isAutomatic,
          displayOrder: badge.displayOrder,
        }).onConflictDoUpdate({
          target: badgeDefinitions.name,
          set: {
            description: badge.description,
            icon: badge.icon,
            category: badge.category,
            tier: badge.tier,
            rarity: badge.rarity,
            unlockMessage: badge.unlockMessage,
            criteria: badge.criteria as any,
            criteriaDescription: badge.criteriaDescription,
            displayOrder: badge.displayOrder,
          },
        });

        console.log(`  ${badge.icon} ${badge.name} (${badge.tier} / ${badge.rarity})`);
        created++;
      } catch (error: any) {
        // If name conflict doesn't work (no unique constraint on name), try insert + ignore
        console.log(`  [!] ${badge.name} - ${error.message?.slice(0, 60)}`);
      }
    }

    console.log(`\nDone! Processed ${BADGE_DEFINITIONS.length} badge definitions.`);
  } catch (error) {
    console.error("Failed to seed badges:", error);
    process.exit(1);
  }

  process.exit(0);
}

seedBadges();
