/**
 * Comprehensive seeding script for workouts, programs, and challenges
 * Run: npx tsx scripts/seed-workouts-programs-challenges.ts
 */

// Use the first circle ID for seeding
const SYSTEM_CIRCLE_ID = "51101c29-197c-4f41-915e-adfc9082ec1e";

// ============================================================================
// CROSSFIT-STYLE WORKOUTS (15)
// ============================================================================
export const CROSSFIT_WORKOUTS = [
  {
    name: "Fran",
    description: "Classic CrossFit benchmark workout. 21-15-9 reps of Thrusters and Pull-ups for time.",
    category: "hiit",
    difficulty: "advanced",
    estimatedDuration: 10,
    structureType: "for_time",
    timeCapSeconds: 600,
    scoringType: "time",
    isOfficial: true,
    tags: ["crossfit", "benchmark", "girl wod"],
    exercises: [
      { name: "Thruster", sets: 3, reps: "21,15,9", notes: "95/65 lbs" },
      { name: "Pull-up", sets: 3, reps: "21,15,9" },
    ],
  },
  {
    name: "Murph",
    description: "Hero WOD honoring Lt. Michael Murphy. 1 mile run, 100 pull-ups, 200 push-ups, 300 squats, 1 mile run.",
    category: "hiit",
    difficulty: "advanced",
    estimatedDuration: 60,
    structureType: "for_time",
    timeCapSeconds: 3600,
    scoringType: "time",
    isOfficial: true,
    tags: ["crossfit", "hero wod", "memorial day"],
    exercises: [
      { name: "Running", distance: 1, distanceUnit: "miles", notes: "Start" },
      { name: "Pull-up", reps: "100", notes: "Partition as needed" },
      { name: "Push-up", reps: "200", notes: "Partition as needed" },
      { name: "Bodyweight Squat", reps: "300", notes: "Partition as needed" },
      { name: "Running", distance: 1, distanceUnit: "miles", notes: "Finish" },
    ],
  },
  {
    name: "Cindy",
    description: "20-minute AMRAP of 5 pull-ups, 10 push-ups, 15 squats.",
    category: "hiit",
    difficulty: "intermediate",
    estimatedDuration: 20,
    structureType: "amrap",
    timeCapSeconds: 1200,
    scoringType: "rounds",
    isOfficial: true,
    tags: ["crossfit", "benchmark", "girl wod", "bodyweight"],
    exercises: [
      { name: "Pull-up", reps: "5" },
      { name: "Push-up", reps: "10" },
      { name: "Bodyweight Squat", reps: "15" },
    ],
  },
  {
    name: "Helen",
    description: "3 rounds for time: 400m run, 21 KB swings, 12 pull-ups.",
    category: "hiit",
    difficulty: "intermediate",
    estimatedDuration: 15,
    structureType: "for_time",
    roundsTarget: 3,
    scoringType: "time",
    isOfficial: true,
    tags: ["crossfit", "benchmark", "girl wod"],
    exercises: [
      { name: "Running", distance: 400, distanceUnit: "meters" },
      { name: "Kettlebell Swing", reps: "21", notes: "53/35 lbs" },
      { name: "Pull-up", reps: "12" },
    ],
  },
  {
    name: "Grace",
    description: "30 Clean & Jerks for time.",
    category: "strength",
    difficulty: "advanced",
    estimatedDuration: 5,
    structureType: "for_time",
    timeCapSeconds: 600,
    scoringType: "time",
    isOfficial: true,
    tags: ["crossfit", "benchmark", "girl wod", "olympic"],
    exercises: [
      { name: "Clean and Jerk", reps: "30", notes: "135/95 lbs" },
    ],
  },
  {
    name: "Isabel",
    description: "30 Snatches for time.",
    category: "strength",
    difficulty: "advanced",
    estimatedDuration: 5,
    structureType: "for_time",
    timeCapSeconds: 600,
    scoringType: "time",
    isOfficial: true,
    tags: ["crossfit", "benchmark", "girl wod", "olympic"],
    exercises: [
      { name: "Snatch", reps: "30", notes: "135/95 lbs" },
    ],
  },
  {
    name: "Death by Burpees",
    description: "EMOM starting with 1 burpee minute 1, 2 minute 2, etc. Continue until you can't complete the reps.",
    category: "hiit",
    difficulty: "intermediate",
    estimatedDuration: 20,
    structureType: "emom",
    emomIntervalSeconds: 60,
    scoringType: "rounds",
    isOfficial: true,
    tags: ["crossfit", "emom", "death by"],
    exercises: [
      { name: "Burpee", reps: "+1 each minute", notes: "Start with 1 rep, add 1 each minute" },
    ],
  },
  {
    name: "Death by Thrusters",
    description: "EMOM starting with 1 thruster minute 1, adding 1 each minute until failure.",
    category: "hiit",
    difficulty: "advanced",
    estimatedDuration: 15,
    structureType: "emom",
    emomIntervalSeconds: 60,
    scoringType: "rounds",
    isOfficial: true,
    tags: ["crossfit", "emom", "death by"],
    exercises: [
      { name: "Thruster", reps: "+1 each minute", notes: "75/55 lbs" },
    ],
  },
  {
    name: "Tabata Something Else",
    description: "8 rounds of 20s work/10s rest for each: Pull-ups, Push-ups, Sit-ups, Squats.",
    category: "hiit",
    difficulty: "intermediate",
    estimatedDuration: 20,
    structureType: "tabata",
    scoringType: "reps",
    isOfficial: true,
    tags: ["crossfit", "tabata", "bodyweight"],
    exercises: [
      { name: "Pull-up", sets: 8, duration: 20, notes: "20s on, 10s off" },
      { name: "Push-up", sets: 8, duration: 20, notes: "20s on, 10s off" },
      { name: "Sit-up", sets: 8, duration: 20, notes: "20s on, 10s off" },
      { name: "Bodyweight Squat", sets: 8, duration: 20, notes: "20s on, 10s off" },
    ],
  },
  {
    name: "Fight Gone Bad",
    description: "3 rounds of 1 minute each: Wall balls, SDLHP, Box jumps, Push press, Row (cal). 1 min rest between rounds.",
    category: "hiit",
    difficulty: "advanced",
    estimatedDuration: 20,
    structureType: "intervals",
    roundsTarget: 3,
    scoringType: "reps",
    isOfficial: true,
    tags: ["crossfit", "benchmark"],
    exercises: [
      { name: "Wall Ball", duration: 60, notes: "1 minute" },
      { name: "Sumo Deadlift High Pull", duration: 60, notes: "1 minute, 75/55 lbs" },
      { name: "Box Jump", duration: 60, notes: "1 minute, 20 inch" },
      { name: "Push Press", duration: 60, notes: "1 minute, 75/55 lbs" },
      { name: "Rowing", duration: 60, notes: "1 minute, calories" },
    ],
  },
  {
    name: "DT",
    description: "5 rounds for time: 12 deadlifts, 9 hang power cleans, 6 push jerks (155/105 lbs).",
    category: "strength",
    difficulty: "advanced",
    estimatedDuration: 15,
    structureType: "for_time",
    roundsTarget: 5,
    scoringType: "time",
    isOfficial: true,
    tags: ["crossfit", "hero wod", "barbell"],
    exercises: [
      { name: "Conventional Deadlift", reps: "12", notes: "155/105 lbs" },
      { name: "Hang Clean", reps: "9", notes: "155/105 lbs" },
      { name: "Push Jerk", reps: "6", notes: "155/105 lbs" },
    ],
  },
  {
    name: "The Chipper",
    description: "For time: 50 box jumps, 40 pull-ups, 30 KB swings, 20 walking lunges, 10 burpees.",
    category: "hiit",
    difficulty: "advanced",
    estimatedDuration: 25,
    structureType: "chipper",
    scoringType: "time",
    isOfficial: true,
    tags: ["crossfit", "chipper"],
    exercises: [
      { name: "Box Jump", reps: "50", notes: "24/20 inch" },
      { name: "Pull-up", reps: "40" },
      { name: "Kettlebell Swing", reps: "30", notes: "53/35 lbs" },
      { name: "Walking Lunge", reps: "20", notes: "Each leg" },
      { name: "Burpee", reps: "10" },
    ],
  },
  {
    name: "12-Minute AMRAP",
    description: "12-minute AMRAP: 6 deadlifts, 6 burpees over bar, 6 power snatches.",
    category: "hiit",
    difficulty: "intermediate",
    estimatedDuration: 12,
    structureType: "amrap",
    timeCapSeconds: 720,
    scoringType: "rounds",
    isOfficial: true,
    tags: ["crossfit", "amrap", "barbell"],
    exercises: [
      { name: "Conventional Deadlift", reps: "6", notes: "135/95 lbs" },
      { name: "Burpee", reps: "6", notes: "Over bar" },
      { name: "Power Snatch", reps: "6", notes: "75/55 lbs" },
    ],
  },
  {
    name: "EMOM 20",
    description: "Every minute on the minute for 20 minutes: Odd minutes 15 wall balls, Even minutes 10 toes-to-bar.",
    category: "hiit",
    difficulty: "intermediate",
    estimatedDuration: 20,
    structureType: "emom",
    emomIntervalSeconds: 60,
    scoringType: "none",
    isOfficial: true,
    tags: ["crossfit", "emom"],
    exercises: [
      { name: "Wall Ball", reps: "15", notes: "Odd minutes, 20/14 lbs" },
      { name: "Toes to Bar", reps: "10", notes: "Even minutes" },
    ],
  },
  {
    name: "Filthy Fifty",
    description: "For time: 50 reps each of box jumps, jumping pull-ups, KB swings, walking lunges, K2E, push press, back extensions, wall balls, burpees, double unders.",
    category: "hiit",
    difficulty: "advanced",
    estimatedDuration: 40,
    structureType: "chipper",
    scoringType: "time",
    isOfficial: true,
    tags: ["crossfit", "chipper", "benchmark"],
    exercises: [
      { name: "Box Jump", reps: "50", notes: "24/20 inch" },
      { name: "Pull-up", reps: "50", notes: "Jumping" },
      { name: "Kettlebell Swing", reps: "50", notes: "35/26 lbs" },
      { name: "Walking Lunge", reps: "50" },
      { name: "Knees to Elbow", reps: "50" },
      { name: "Push Press", reps: "50", notes: "45/35 lbs" },
      { name: "Arch Body Hold", reps: "50", notes: "Back extensions" },
      { name: "Wall Ball", reps: "50", notes: "20/14 lbs" },
      { name: "Burpee", reps: "50" },
      { name: "Double Under", reps: "50" },
    ],
  },
];

// ============================================================================
// BODYBUILDING WORKOUTS (15)
// ============================================================================
export const BODYBUILDING_WORKOUTS = [
  {
    name: "Arnold Chest & Back",
    description: "Classic Arnold-style push/pull superset workout for chest and back.",
    category: "strength",
    difficulty: "advanced",
    estimatedDuration: 60,
    structureType: "standard",
    isOfficial: true,
    tags: ["bodybuilding", "arnold", "superset", "push pull"],
    exercises: [
      { name: "Barbell Bench Press", sets: 4, reps: "10,8,6,4", groupId: "A1", groupType: "superset" },
      { name: "Weighted Pull-up", sets: 4, reps: "10,8,6,4", groupId: "A2", groupType: "superset" },
      { name: "Incline Dumbbell Press", sets: 4, reps: "10", groupId: "B1", groupType: "superset" },
      { name: "Barbell Row", sets: 4, reps: "10", groupId: "B2", groupType: "superset" },
      { name: "Dumbbell Fly", sets: 3, reps: "12", groupId: "C1", groupType: "superset" },
      { name: "Dumbbell Row", sets: 3, reps: "12", groupId: "C2", groupType: "superset" },
      { name: "Dip", sets: 3, reps: "15" },
      { name: "Chin-up", sets: 3, reps: "AMRAP" },
    ],
  },
  {
    name: "Classic Arm Blaster",
    description: "High-volume bicep and tricep workout with supersets.",
    category: "strength",
    difficulty: "intermediate",
    estimatedDuration: 45,
    structureType: "standard",
    isOfficial: true,
    tags: ["bodybuilding", "arms", "superset"],
    exercises: [
      { name: "Barbell Curl", sets: 4, reps: "10", groupId: "A1", groupType: "superset" },
      { name: "Skull Crusher", sets: 4, reps: "10", groupId: "A2", groupType: "superset" },
      { name: "Dumbbell Curl", sets: 3, reps: "12", groupId: "B1", groupType: "superset" },
      { name: "Tricep Pushdown", sets: 3, reps: "12", groupId: "B2", groupType: "superset" },
      { name: "Hammer Curl", sets: 3, reps: "12", groupId: "C1", groupType: "superset" },
      { name: "Overhead Tricep Extension", sets: 3, reps: "12", groupId: "C2", groupType: "superset" },
      { name: "Concentration Curl", sets: 2, reps: "15", groupId: "D1", groupType: "superset" },
      { name: "Tricep Kickback", sets: 2, reps: "15", groupId: "D2", groupType: "superset" },
    ],
  },
  {
    name: "Leg Day Destroyer",
    description: "Complete leg workout targeting quads, hamstrings, glutes, and calves.",
    category: "strength",
    difficulty: "advanced",
    estimatedDuration: 75,
    structureType: "standard",
    isOfficial: true,
    tags: ["bodybuilding", "legs", "high volume"],
    exercises: [
      { name: "Barbell Back Squat", sets: 5, reps: "10,8,8,6,6", restBetweenSets: 180 },
      { name: "Leg Press", sets: 4, reps: "12", restBetweenSets: 120 },
      { name: "Romanian Deadlift", sets: 4, reps: "10", restBetweenSets: 120 },
      { name: "Walking Lunge", sets: 3, reps: "12 each", restBetweenSets: 90 },
      { name: "Leg Extension", sets: 3, reps: "15", groupId: "A1", groupType: "superset" },
      { name: "Leg Curl", sets: 3, reps: "15", groupId: "A2", groupType: "superset" },
      { name: "Calf Raise", sets: 4, reps: "15", restBetweenSets: 60 },
      { name: "Seated Calf Raise", sets: 3, reps: "20", restBetweenSets: 45 },
    ],
  },
  {
    name: "Shoulder Boulder Builder",
    description: "Complete shoulder workout for front, side, and rear delts plus traps.",
    category: "strength",
    difficulty: "intermediate",
    estimatedDuration: 50,
    structureType: "standard",
    isOfficial: true,
    tags: ["bodybuilding", "shoulders"],
    exercises: [
      { name: "Overhead Press", sets: 4, reps: "8", restBetweenSets: 120 },
      { name: "Arnold Press", sets: 3, reps: "10", restBetweenSets: 90 },
      { name: "Lateral Raise", sets: 4, reps: "12-15", restBetweenSets: 60 },
      { name: "Rear Delt Fly", sets: 4, reps: "15", restBetweenSets: 60 },
      { name: "Front Raise", sets: 3, reps: "12", restBetweenSets: 60 },
      { name: "Face Pull", sets: 3, reps: "15", restBetweenSets: 60 },
      { name: "Shrug", sets: 4, reps: "12", restBetweenSets: 60 },
    ],
  },
  {
    name: "Back Width & Thickness",
    description: "Complete back workout for width (lats) and thickness (middle back).",
    category: "strength",
    difficulty: "intermediate",
    estimatedDuration: 55,
    structureType: "standard",
    isOfficial: true,
    tags: ["bodybuilding", "back"],
    exercises: [
      { name: "Weighted Pull-up", sets: 4, reps: "8-10", restBetweenSets: 120, notes: "Width" },
      { name: "Barbell Row", sets: 4, reps: "8", restBetweenSets: 120, notes: "Thickness" },
      { name: "Lat Pulldown", sets: 3, reps: "12", restBetweenSets: 90 },
      { name: "Seated Cable Row", sets: 3, reps: "12", restBetweenSets: 90 },
      { name: "Dumbbell Row", sets: 3, reps: "10 each", restBetweenSets: 90 },
      { name: "Straight Arm Pulldown", sets: 3, reps: "15", restBetweenSets: 60 },
      { name: "Face Pull", sets: 3, reps: "15", restBetweenSets: 60 },
    ],
  },
  {
    name: "Push Day",
    description: "PPL Push day: Chest, shoulders, triceps.",
    category: "strength",
    difficulty: "intermediate",
    estimatedDuration: 60,
    structureType: "standard",
    isOfficial: true,
    tags: ["bodybuilding", "ppl", "push"],
    exercises: [
      { name: "Barbell Bench Press", sets: 4, reps: "6-8", restBetweenSets: 150 },
      { name: "Overhead Press", sets: 4, reps: "8-10", restBetweenSets: 120 },
      { name: "Incline Dumbbell Press", sets: 3, reps: "10-12", restBetweenSets: 90 },
      { name: "Cable Crossover", sets: 3, reps: "12-15", restBetweenSets: 60 },
      { name: "Lateral Raise", sets: 4, reps: "12-15", restBetweenSets: 60 },
      { name: "Tricep Pushdown", sets: 3, reps: "12", restBetweenSets: 60 },
      { name: "Overhead Tricep Extension", sets: 3, reps: "12", restBetweenSets: 60 },
    ],
  },
  {
    name: "Pull Day",
    description: "PPL Pull day: Back and biceps.",
    category: "strength",
    difficulty: "intermediate",
    estimatedDuration: 60,
    structureType: "standard",
    isOfficial: true,
    tags: ["bodybuilding", "ppl", "pull"],
    exercises: [
      { name: "Conventional Deadlift", sets: 3, reps: "5", restBetweenSets: 180 },
      { name: "Weighted Pull-up", sets: 4, reps: "6-8", restBetweenSets: 120 },
      { name: "Barbell Row", sets: 4, reps: "8-10", restBetweenSets: 120 },
      { name: "Lat Pulldown", sets: 3, reps: "10-12", restBetweenSets: 90 },
      { name: "Face Pull", sets: 3, reps: "15-20", restBetweenSets: 60 },
      { name: "Barbell Curl", sets: 3, reps: "10-12", restBetweenSets: 60 },
      { name: "Hammer Curl", sets: 3, reps: "12", restBetweenSets: 60 },
    ],
  },
  {
    name: "Legs Day (PPL)",
    description: "PPL Legs day: Quads, hamstrings, glutes, calves.",
    category: "strength",
    difficulty: "intermediate",
    estimatedDuration: 65,
    structureType: "standard",
    isOfficial: true,
    tags: ["bodybuilding", "ppl", "legs"],
    exercises: [
      { name: "Barbell Back Squat", sets: 4, reps: "6-8", restBetweenSets: 180 },
      { name: "Romanian Deadlift", sets: 4, reps: "8-10", restBetweenSets: 120 },
      { name: "Leg Press", sets: 3, reps: "10-12", restBetweenSets: 120 },
      { name: "Leg Curl", sets: 3, reps: "10-12", restBetweenSets: 90 },
      { name: "Leg Extension", sets: 3, reps: "12-15", restBetweenSets: 60 },
      { name: "Calf Raise", sets: 4, reps: "12-15", restBetweenSets: 60 },
    ],
  },
  {
    name: "Upper Body Hypertrophy",
    description: "High volume upper body workout for muscle growth.",
    category: "strength",
    difficulty: "intermediate",
    estimatedDuration: 70,
    structureType: "standard",
    isOfficial: true,
    tags: ["bodybuilding", "upper lower", "hypertrophy"],
    exercises: [
      { name: "Incline Bench Press", sets: 4, reps: "10-12", restBetweenSets: 90 },
      { name: "Lat Pulldown", sets: 4, reps: "10-12", restBetweenSets: 90 },
      { name: "Dumbbell Bench Press", sets: 3, reps: "12", restBetweenSets: 60 },
      { name: "Seated Cable Row", sets: 3, reps: "12", restBetweenSets: 60 },
      { name: "Lateral Raise", sets: 3, reps: "15", restBetweenSets: 45 },
      { name: "Rear Delt Fly", sets: 3, reps: "15", restBetweenSets: 45 },
      { name: "Dumbbell Curl", sets: 3, reps: "12", groupId: "A1", groupType: "superset" },
      { name: "Tricep Pushdown", sets: 3, reps: "12", groupId: "A2", groupType: "superset" },
    ],
  },
  {
    name: "Lower Body Hypertrophy",
    description: "High volume lower body workout for muscle growth.",
    category: "strength",
    difficulty: "intermediate",
    estimatedDuration: 60,
    structureType: "standard",
    isOfficial: true,
    tags: ["bodybuilding", "upper lower", "hypertrophy"],
    exercises: [
      { name: "Front Squat", sets: 4, reps: "10-12", restBetweenSets: 120 },
      { name: "Romanian Deadlift", sets: 4, reps: "10-12", restBetweenSets: 90 },
      { name: "Leg Press", sets: 3, reps: "15", restBetweenSets: 90 },
      { name: "Leg Curl", sets: 3, reps: "12-15", restBetweenSets: 60 },
      { name: "Leg Extension", sets: 3, reps: "15", restBetweenSets: 60 },
      { name: "Hip Thrust", sets: 3, reps: "12", restBetweenSets: 90 },
      { name: "Calf Raise", sets: 4, reps: "15-20", restBetweenSets: 45 },
    ],
  },
  {
    name: "Chest Specialization",
    description: "High volume chest-focused workout.",
    category: "strength",
    difficulty: "intermediate",
    estimatedDuration: 50,
    structureType: "standard",
    isOfficial: true,
    tags: ["bodybuilding", "chest", "specialization"],
    exercises: [
      { name: "Barbell Bench Press", sets: 5, reps: "8,8,6,6,4", restBetweenSets: 150 },
      { name: "Incline Dumbbell Press", sets: 4, reps: "10", restBetweenSets: 90 },
      { name: "Decline Bench Press", sets: 3, reps: "10", restBetweenSets: 90 },
      { name: "Cable Crossover", sets: 4, reps: "12-15", restBetweenSets: 60 },
      { name: "Dumbbell Fly", sets: 3, reps: "15", restBetweenSets: 60 },
      { name: "Dip", sets: 3, reps: "AMRAP", notes: "Lean forward for chest" },
    ],
  },
  {
    name: "German Volume Training - Chest",
    description: "10x10 methodology for chest with accessory work.",
    category: "strength",
    difficulty: "advanced",
    estimatedDuration: 60,
    structureType: "standard",
    isOfficial: true,
    tags: ["bodybuilding", "gvt", "high volume"],
    exercises: [
      { name: "Barbell Bench Press", sets: 10, reps: "10", restBetweenSets: 60, notes: "Use 60% 1RM" },
      { name: "Dumbbell Row", sets: 3, reps: "12", restBetweenSets: 60 },
      { name: "Incline Dumbbell Fly", sets: 3, reps: "12", restBetweenSets: 45 },
    ],
  },
  {
    name: "FST-7 Shoulders",
    description: "Fascia Stretch Training with 7 sets for the final exercise.",
    category: "strength",
    difficulty: "advanced",
    estimatedDuration: 55,
    structureType: "standard",
    isOfficial: true,
    tags: ["bodybuilding", "fst-7", "shoulders"],
    exercises: [
      { name: "Overhead Press", sets: 4, reps: "8-10", restBetweenSets: 90 },
      { name: "Dumbbell Lateral Raise", sets: 3, reps: "10-12", restBetweenSets: 60 },
      { name: "Rear Delt Fly", sets: 3, reps: "12", restBetweenSets: 60 },
      { name: "Cable Lateral Raise", sets: 7, reps: "10-12", restBetweenSets: 30, notes: "FST-7 - 30 sec rest only" },
    ],
  },
  {
    name: "Bro Split - Chest Monday",
    description: "Classic bro split chest day.",
    category: "strength",
    difficulty: "intermediate",
    estimatedDuration: 50,
    structureType: "standard",
    isOfficial: true,
    tags: ["bodybuilding", "bro split", "chest"],
    exercises: [
      { name: "Barbell Bench Press", sets: 4, reps: "8-10", restBetweenSets: 120 },
      { name: "Incline Bench Press", sets: 4, reps: "10", restBetweenSets: 90 },
      { name: "Dumbbell Fly", sets: 3, reps: "12", restBetweenSets: 60 },
      { name: "Cable Crossover", sets: 3, reps: "15", restBetweenSets: 60 },
      { name: "Pec Deck", sets: 3, reps: "15", restBetweenSets: 45 },
    ],
  },
  {
    name: "Full Body Pump",
    description: "Full body workout hitting all major muscle groups.",
    category: "strength",
    difficulty: "beginner",
    estimatedDuration: 60,
    structureType: "standard",
    isOfficial: true,
    tags: ["bodybuilding", "full body", "beginner"],
    exercises: [
      { name: "Barbell Back Squat", sets: 3, reps: "10", restBetweenSets: 120 },
      { name: "Barbell Bench Press", sets: 3, reps: "10", restBetweenSets: 90 },
      { name: "Barbell Row", sets: 3, reps: "10", restBetweenSets: 90 },
      { name: "Overhead Press", sets: 3, reps: "10", restBetweenSets: 90 },
      { name: "Romanian Deadlift", sets: 3, reps: "10", restBetweenSets: 90 },
      { name: "Dumbbell Curl", sets: 2, reps: "12", restBetweenSets: 60 },
      { name: "Tricep Pushdown", sets: 2, reps: "12", restBetweenSets: 60 },
    ],
  },
];

// ============================================================================
// STRENGTH WORKOUTS (10)
// ============================================================================
export const STRENGTH_WORKOUTS = [
  {
    name: "StrongLifts 5x5 - Workout A",
    description: "Squat, Bench Press, Barbell Row - 5 sets of 5 reps each.",
    category: "strength",
    difficulty: "beginner",
    estimatedDuration: 45,
    structureType: "standard",
    isOfficial: true,
    tags: ["strength", "5x5", "linear progression"],
    exercises: [
      { name: "Barbell Back Squat", sets: 5, reps: "5", restBetweenSets: 180 },
      { name: "Barbell Bench Press", sets: 5, reps: "5", restBetweenSets: 180 },
      { name: "Barbell Row", sets: 5, reps: "5", restBetweenSets: 180 },
    ],
  },
  {
    name: "StrongLifts 5x5 - Workout B",
    description: "Squat, Overhead Press, Deadlift - 5 sets of 5 reps (1x5 deadlift).",
    category: "strength",
    difficulty: "beginner",
    estimatedDuration: 45,
    structureType: "standard",
    isOfficial: true,
    tags: ["strength", "5x5", "linear progression"],
    exercises: [
      { name: "Barbell Back Squat", sets: 5, reps: "5", restBetweenSets: 180 },
      { name: "Overhead Press", sets: 5, reps: "5", restBetweenSets: 180 },
      { name: "Conventional Deadlift", sets: 1, reps: "5", restBetweenSets: 180 },
    ],
  },
  {
    name: "5/3/1 - Squat Day",
    description: "Wendler 5/3/1 squat day with BBB accessory work.",
    category: "strength",
    difficulty: "intermediate",
    estimatedDuration: 60,
    structureType: "standard",
    isOfficial: true,
    tags: ["strength", "5/3/1", "periodization"],
    exercises: [
      { name: "Barbell Back Squat", sets: 3, reps: "5,3,1+", restBetweenSets: 240, notes: "Main work: 65%, 75%, 85%+" },
      { name: "Barbell Back Squat", sets: 5, reps: "10", restBetweenSets: 90, notes: "BBB: 50% TM" },
      { name: "Leg Curl", sets: 5, reps: "10", restBetweenSets: 60 },
      { name: "Hanging Leg Raise", sets: 5, reps: "15", restBetweenSets: 60 },
    ],
  },
  {
    name: "5/3/1 - Bench Day",
    description: "Wendler 5/3/1 bench press day with BBB accessory work.",
    category: "strength",
    difficulty: "intermediate",
    estimatedDuration: 60,
    structureType: "standard",
    isOfficial: true,
    tags: ["strength", "5/3/1", "periodization"],
    exercises: [
      { name: "Barbell Bench Press", sets: 3, reps: "5,3,1+", restBetweenSets: 240, notes: "Main work: 65%, 75%, 85%+" },
      { name: "Barbell Bench Press", sets: 5, reps: "10", restBetweenSets: 90, notes: "BBB: 50% TM" },
      { name: "Dumbbell Row", sets: 5, reps: "10", restBetweenSets: 60 },
      { name: "Face Pull", sets: 5, reps: "15-20", restBetweenSets: 60 },
    ],
  },
  {
    name: "5/3/1 - Deadlift Day",
    description: "Wendler 5/3/1 deadlift day with BBB accessory work.",
    category: "strength",
    difficulty: "intermediate",
    estimatedDuration: 60,
    structureType: "standard",
    isOfficial: true,
    tags: ["strength", "5/3/1", "periodization"],
    exercises: [
      { name: "Conventional Deadlift", sets: 3, reps: "5,3,1+", restBetweenSets: 300, notes: "Main work: 65%, 75%, 85%+" },
      { name: "Conventional Deadlift", sets: 5, reps: "10", restBetweenSets: 120, notes: "BBB: 50% TM" },
      { name: "Good Morning", sets: 5, reps: "10", restBetweenSets: 60 },
      { name: "Hanging Leg Raise", sets: 5, reps: "15", restBetweenSets: 60 },
    ],
  },
  {
    name: "5/3/1 - OHP Day",
    description: "Wendler 5/3/1 overhead press day with BBB accessory work.",
    category: "strength",
    difficulty: "intermediate",
    estimatedDuration: 60,
    structureType: "standard",
    isOfficial: true,
    tags: ["strength", "5/3/1", "periodization"],
    exercises: [
      { name: "Overhead Press", sets: 3, reps: "5,3,1+", restBetweenSets: 180, notes: "Main work: 65%, 75%, 85%+" },
      { name: "Overhead Press", sets: 5, reps: "10", restBetweenSets: 90, notes: "BBB: 50% TM" },
      { name: "Chin-up", sets: 5, reps: "10", restBetweenSets: 60 },
      { name: "Face Pull", sets: 5, reps: "15-20", restBetweenSets: 60 },
    ],
  },
  {
    name: "Heavy Singles Day",
    description: "Work up to heavy singles on squat, bench, or deadlift.",
    category: "strength",
    difficulty: "advanced",
    estimatedDuration: 75,
    structureType: "standard",
    isOfficial: true,
    tags: ["strength", "maximal", "1rm"],
    exercises: [
      { name: "Barbell Back Squat", sets: 8, reps: "5,3,2,1,1,1,1,1", restBetweenSets: 300, notes: "Build to max single" },
      { name: "Pause Squat", sets: 3, reps: "3", restBetweenSets: 180, notes: "70% of max single" },
    ],
  },
  {
    name: "Texas Method - Volume Day",
    description: "Monday volume day for the Texas Method.",
    category: "strength",
    difficulty: "intermediate",
    estimatedDuration: 90,
    structureType: "standard",
    isOfficial: true,
    tags: ["strength", "texas method", "intermediate"],
    exercises: [
      { name: "Barbell Back Squat", sets: 5, reps: "5", restBetweenSets: 240, notes: "90% of 5RM" },
      { name: "Barbell Bench Press", sets: 5, reps: "5", restBetweenSets: 180, notes: "90% of 5RM" },
      { name: "Conventional Deadlift", sets: 1, reps: "5", restBetweenSets: 300 },
    ],
  },
  {
    name: "Texas Method - Intensity Day",
    description: "Friday intensity day for the Texas Method.",
    category: "strength",
    difficulty: "intermediate",
    estimatedDuration: 75,
    structureType: "standard",
    isOfficial: true,
    tags: ["strength", "texas method", "intermediate"],
    exercises: [
      { name: "Barbell Back Squat", sets: 1, reps: "5", restBetweenSets: 300, notes: "5RM or new PR" },
      { name: "Barbell Bench Press", sets: 1, reps: "5", restBetweenSets: 240, notes: "5RM or new PR" },
      { name: "Power Clean", sets: 5, reps: "3", restBetweenSets: 180 },
    ],
  },
  {
    name: "Deadlift Specialization",
    description: "Deadlift-focused workout with variations.",
    category: "strength",
    difficulty: "advanced",
    estimatedDuration: 60,
    structureType: "standard",
    isOfficial: true,
    tags: ["strength", "deadlift", "specialization"],
    exercises: [
      { name: "Conventional Deadlift", sets: 5, reps: "3", restBetweenSets: 240, notes: "Heavy triples" },
      { name: "Deficit Deadlift", sets: 3, reps: "5", restBetweenSets: 180, notes: "2 inch deficit" },
      { name: "Romanian Deadlift", sets: 3, reps: "8", restBetweenSets: 120 },
      { name: "Good Morning", sets: 3, reps: "10", restBetweenSets: 90 },
      { name: "Barbell Row", sets: 3, reps: "8", restBetweenSets: 90 },
    ],
  },
];

// ============================================================================
// CARDIO WORKOUTS (10)
// ============================================================================
export const CARDIO_WORKOUTS = [
  {
    name: "Sprint Intervals",
    description: "8 rounds of 30-second sprints with 90-second rest.",
    category: "cardio",
    difficulty: "intermediate",
    estimatedDuration: 20,
    structureType: "intervals",
    isOfficial: true,
    tags: ["cardio", "hiit", "sprinting"],
    exercises: [
      { name: "Sprinting", sets: 8, duration: 30, restBetweenSets: 90, notes: "Max effort" },
    ],
  },
  {
    name: "Tempo Run",
    description: "5-minute warmup, 20-minute tempo run at 80% effort, 5-minute cooldown.",
    category: "cardio",
    difficulty: "intermediate",
    estimatedDuration: 30,
    structureType: "standard",
    isOfficial: true,
    tags: ["cardio", "running", "tempo"],
    exercises: [
      { name: "Running", duration: 300, notes: "Warmup - easy pace" },
      { name: "Running", duration: 1200, notes: "Tempo - 80% effort" },
      { name: "Running", duration: 300, notes: "Cooldown - easy pace" },
    ],
  },
  {
    name: "Rowing Intervals",
    description: "500m rowing intervals with equal rest.",
    category: "cardio",
    difficulty: "intermediate",
    estimatedDuration: 25,
    structureType: "intervals",
    isOfficial: true,
    tags: ["cardio", "rowing", "intervals"],
    exercises: [
      { name: "Rowing", sets: 6, distance: 500, distanceUnit: "meters", restBetweenSets: 120, notes: "Hard effort" },
    ],
  },
  {
    name: "Row Ladder",
    description: "250m, 500m, 750m, 1000m, 750m, 500m, 250m with 2:1 rest.",
    category: "cardio",
    difficulty: "advanced",
    estimatedDuration: 35,
    structureType: "ladder",
    scoringType: "time",
    isOfficial: true,
    tags: ["cardio", "rowing", "ladder"],
    exercises: [
      { name: "Rowing", distance: 250, distanceUnit: "meters", notes: "Hard effort, rest = 2x work time" },
      { name: "Rowing", distance: 500, distanceUnit: "meters", notes: "Hard effort, rest = 2x work time" },
      { name: "Rowing", distance: 750, distanceUnit: "meters", notes: "Hard effort, rest = 2x work time" },
      { name: "Rowing", distance: 1000, distanceUnit: "meters", notes: "Hard effort, rest = 2x work time" },
      { name: "Rowing", distance: 750, distanceUnit: "meters", notes: "Hard effort, rest = 2x work time" },
      { name: "Rowing", distance: 500, distanceUnit: "meters", notes: "Hard effort, rest = 2x work time" },
      { name: "Rowing", distance: 250, distanceUnit: "meters", notes: "Final sprint" },
    ],
  },
  {
    name: "Assault Bike Intervals",
    description: "10 rounds: 20 calories sprint, 40 seconds rest.",
    category: "cardio",
    difficulty: "advanced",
    estimatedDuration: 20,
    structureType: "intervals",
    isOfficial: true,
    tags: ["cardio", "assault bike", "hiit"],
    exercises: [
      { name: "Assault Bike", sets: 10, notes: "20 calories sprint, 40 sec rest" },
    ],
  },
  {
    name: "Hill Sprint Session",
    description: "10 hill sprints with walk-down recovery.",
    category: "cardio",
    difficulty: "intermediate",
    estimatedDuration: 30,
    structureType: "intervals",
    isOfficial: true,
    tags: ["cardio", "sprinting", "hills"],
    exercises: [
      { name: "Hill Sprints", sets: 10, duration: 20, notes: "Max effort up, walk down recovery" },
    ],
  },
  {
    name: "Long Slow Distance",
    description: "45-60 minute run at conversational pace.",
    category: "cardio",
    difficulty: "beginner",
    estimatedDuration: 50,
    structureType: "standard",
    isOfficial: true,
    tags: ["cardio", "running", "lsd", "aerobic"],
    exercises: [
      { name: "Running", duration: 3000, notes: "Easy pace - should be able to hold conversation" },
    ],
  },
  {
    name: "Fartlek Run",
    description: "30-minute run with random speed changes.",
    category: "cardio",
    difficulty: "intermediate",
    estimatedDuration: 30,
    structureType: "standard",
    isOfficial: true,
    tags: ["cardio", "running", "fartlek"],
    exercises: [
      { name: "Running", duration: 1800, notes: "Alternate between fast and slow based on landmarks or feel" },
    ],
  },
  {
    name: "Bike Pyramid",
    description: "Stationary bike pyramid: 1-2-3-4-5-4-3-2-1 minute intervals at high resistance.",
    category: "cardio",
    difficulty: "intermediate",
    estimatedDuration: 30,
    structureType: "ladder",
    isOfficial: true,
    tags: ["cardio", "cycling", "pyramid"],
    exercises: [
      { name: "Cycling", duration: 60, notes: "1 min hard, 1 min easy" },
      { name: "Cycling", duration: 120, notes: "2 min hard, 2 min easy" },
      { name: "Cycling", duration: 180, notes: "3 min hard, 3 min easy" },
      { name: "Cycling", duration: 240, notes: "4 min hard, 4 min easy" },
      { name: "Cycling", duration: 300, notes: "5 min hard, 5 min easy" },
      { name: "Cycling", duration: 240, notes: "4 min hard, 4 min easy" },
      { name: "Cycling", duration: 180, notes: "3 min hard, 3 min easy" },
      { name: "Cycling", duration: 120, notes: "2 min hard, 2 min easy" },
      { name: "Cycling", duration: 60, notes: "1 min hard, cooldown" },
    ],
  },
  {
    name: "Jump Rope Conditioning",
    description: "30 minutes of jump rope intervals and skill work.",
    category: "cardio",
    difficulty: "intermediate",
    estimatedDuration: 30,
    structureType: "intervals",
    isOfficial: true,
    tags: ["cardio", "jump rope", "conditioning"],
    exercises: [
      { name: "Jump Rope", duration: 120, notes: "Basic bouncing - warmup" },
      { name: "Jump Rope", sets: 5, duration: 60, restBetweenSets: 30, notes: "Fast singles" },
      { name: "Double Under", sets: 5, reps: "20", restBetweenSets: 30, notes: "Practice double unders" },
      { name: "Jump Rope", duration: 300, notes: "Mixed footwork - boxers, high knees, criss-cross" },
    ],
  },
];

// Export all for reference
export const ALL_WORKOUTS = [
  ...CROSSFIT_WORKOUTS,
  ...BODYBUILDING_WORKOUTS,
  ...STRENGTH_WORKOUTS,
  ...CARDIO_WORKOUTS,
];

console.log(`Total workouts: ${ALL_WORKOUTS.length}`);
